import type { PageContent } from "../types";

export const pages: PageContent[] = [
  {
    path: "compare",
    title: "Feature Comparison: ZapBuzzer vs the Usual Ways",
    description:
      "Compare ZapBuzzer with phone calls, WhatsApp groups, shouting down the hall and traditional helpdesks for office requests like coffee, prints, IT and courier.",
    h1: "How ZapBuzzer compares with the way offices ask for things today",
    eyebrow: "Compare",
    lead:
      "Most offices already have a system for internal requests. It is usually a mix of phone calls, a pantry WhatsApp group, a helpdesk built for IT tickets and somebody shouting a name down the corridor. This page puts those habits side by side with ZapBuzzer so you can see where each one breaks.",
    keywords: [
      "zapbuzzer comparison",
      "office request tool comparison",
      "whatsapp vs request system",
      "helpdesk alternative for office requests",
      "internal request crm",
    ],
    heroVisual: "before-after",
    sections: [
      {
        type: "prose",
        heading: "What we are actually comparing",
        paragraphs: [
          "ZapBuzzer is an internal-request CRM for the small, constant asks that keep an office running: two coffees to the boss cabin, 24 colour copies before a pitch, an AC stuck at 16°C in Conference Room B, a courier waiting at the gate. These are not projects and they are not IT incidents. They are short jobs that need the right person to say “I’ve got it” within a minute.",
          "So the fair comparison is not ZapBuzzer against a project tool. It is ZapBuzzer against whatever your office uses right now to get those small jobs done. In most offices we meet, that is one of four things: manual requests (walking over or shouting), WhatsApp groups, phone calls and intercoms, or a traditional helpdesk that was set up for IT and stretched to cover everything else.",
        ],
      },
      {
        type: "comparison",
        heading: "The short version",
        intro: "How the common approaches handle the things that matter for a quick office request.",
        columns: ["Calls, WhatsApp and walking over", "ZapBuzzer"],
        rows: [
          { label: "Who gets the request", a: "Whoever you happen to reach", b: "The whole responsible team, at once" },
          { label: "Who owns it", a: "Unclear, often two people or nobody", b: "The first person to tap Accept" },
          { label: "Requester knows status", a: "Only by calling again", b: "Sees name, photo and ETA" },
          { label: "Deadline", a: "None", b: "Every request is timed; SLA and escalation on Pro" },
          { label: "If nobody responds", a: "It quietly dies", b: "Notifications repeat till accepted" },
          { label: "Record afterwards", a: "Scrollback, if anything", b: "Request history, ratings and analytics" },
          { label: "Fair credit for staff", a: "None", b: "Ratings and scorecards (full scorecards on Pro)" },
        ],
      },
      {
        type: "visual",
        visual: "before-after",
        heading: "Same coffee, two very different mornings",
        body:
          "Done the old way, asking Raju to bring two coffees to the boss cabin cost 25 minutes and 3 phone calls, and the coffee arrived cold (1 cup). Sent through ZapBuzzer, the same order needed 0 phone calls, took 4 minutes and arrived hot (1 cup). Nothing about the pantry team changed. The way the request reached them did.",
        points: ["25 minutes vs 4 minutes", "3 phone calls vs 0", "Cold coffee vs hot coffee"],
      },
      {
        type: "features",
        heading: "Pick the comparison closest to your office",
        items: [
          { title: "vs Manual requests", body: "For offices where people walk to the pantry, shout across the floor or leave sticky notes at the print room." },
          { title: "vs WhatsApp", body: "For offices running a pantry group, a print group and an admin group, with requests buried under good-morning messages." },
          { title: "vs Phone calls", body: "For offices where the intercom and personal mobiles are the request system, and every ask costs someone a call." },
          { title: "vs Traditional helpdesk", body: "For offices that already have a ticketing tool for IT and are trying to push coffee and courier pickups through it." },
        ],
      },
      {
        type: "problem-solution",
        heading: "The pattern behind every comparison",
        problem: {
          title: "What the usual methods share",
          points: [
            "A request goes to one person instead of the team that could handle it",
            "Nobody explicitly takes ownership, so two people act or none do",
            "The requester has no idea whether anyone is on it",
            "There is no clock, so ‘in a bit’ can mean an hour",
            "Nothing is recorded, so the same problems repeat every week",
          ],
        },
        solution: {
          title: "What ZapBuzzer changes",
          points: [
            "One tap sends the request to the whole team on app, email and, on Pro, Telegram and WhatsApp",
            "First to accept owns it, visibly",
            "Requester sees who is coming and when",
            "Every request is timed; Pro adds SLA deadlines and an escalation chain",
            "History, ratings and analytics show what actually happens",
          ],
        },
      },
      {
        type: "scenario",
        heading: "A typical scenario: the pitch at 11",
        persona: "Kavya, Sales Lead",
        setting: "Client pitch in 10 minutes, deck not yet printed.",
        timeline: [
          { time: "10:50", event: "Kavya uploads the PDF and asks for 24 colour copies to Conference Room B." },
          { time: "10:50", event: "The print room team gets the request at the same time." },
          { time: "10:51", event: "One of them accepts; Kavya sees the name and the ETA." },
          { time: "10:57", event: "Prints are delivered to the room, with a photo attached to the request." },
          { time: "11:00", event: "The client sits down; Kavya rates the delivery." },
        ],
        outcome: "No chase call, no guessing which printer the file went to. As Kavya puts it: “Print jobs land at my desk before the client even sits down. Zero chase calls.”",
      },
      {
        type: "table",
        heading: "Which approach fits which office",
        headers: ["Office situation", "Usually works", "Where it breaks"],
        rows: [
          ["5 people, one pantry person", "Walking over", "Breaks the day that person is busy or on leave"],
          ["20–50 people, one floor", "WhatsApp group", "Breaks when the group gets noisy and requests overlap"],
          ["Busy leadership floor", "Phone calls", "Breaks during meetings and when the line is engaged"],
          ["IT team with a ticketing tool", "Helpdesk", "Breaks for 2-minute asks like coffee or an HDMI cable"],
          ["Any office with staff teams", "ZapBuzzer", "Start on Free for one floor; move to Pro as you grow"],
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "You do not have to switch everything at once",
        body:
          "Most offices start with one request type, usually coffee or printing, on the Free plan for one floor with up to 10 staff. Once the pantry group goes quiet, the rest of the office tends to ask for the same.",
      },
    ],
    faqs: [
      { q: "Is ZapBuzzer a replacement for our IT helpdesk?", a: "Not necessarily. ZapBuzzer is built for quick internal requests such as coffee, prints, facilities fixes and courier pickups. Some offices route small IT asks like an HDMI cable through ZapBuzzer and keep a separate tool for long-running IT incidents." },
      { q: "Can we keep using WhatsApp for notifications?", a: "Yes. On Pro, ZapBuzzer sends request alerts to WhatsApp and Telegram alongside the app and email. The difference is that the request now has an owner, a timer and a record, instead of being a message in a group." },
      { q: "What is the quickest way to test the comparison ourselves?", a: "Start the 14-day free trial, add one team such as the pantry, and route a week of requests through ZapBuzzer. No credit card or setup call is needed." },
      { q: "Does ZapBuzzer work for very small offices?", a: "Yes. The Free plan covers up to 10 staff in one location with email notifications and 30 days of history, which suits a single floor." },
    ],
    related: ["compare/whatsapp", "compare/phone-calls", "compare/manual-requests", "compare/helpdesk", "why-zapbuzzer", "features/first-accept-wins", "pricing", "free-trial"],
    cta: { title: "See the difference on your own floor", body: "Start a 14-day free trial, invite your pantry or print team, and compare a week of requests." },
  },
  {
    path: "compare/manual-requests",
    title: "ZapBuzzer vs Manual Office Requests",
    description:
      "Walking to the pantry, shouting names, leaving sticky notes: see how ZapBuzzer replaces manual office requests with one tap, clear ownership and timers.",
    h1: "Walking over, shouting names, sticky notes: the manual way vs one tap",
    eyebrow: "Compare",
    lead:
      "In a lot of offices the request system is a person walking to another person. It feels personal and it is free, but it costs more time than anyone notices. Here is how manual requests compare with ZapBuzzer, honestly.",
    keywords: ["manual office requests", "replace shouting in office", "office request system", "pantry request without calling", "zapbuzzer vs manual"],
    heroVisual: "mobile-app",
    sections: [
      {
        type: "prose",
        heading: "What ‘manual’ looks like on a normal Tuesday",
        paragraphs: [
          "Aarav is in a board call and wants coffee. He steps out, catches someone in the corridor and asks them to find Raju. Raju is on the 3rd floor restocking. The message gets passed twice and arrives as ‘someone wants tea’. Twenty-five minutes later a cold cup lands on the wrong desk.",
          "Nobody did anything wrong. The process simply depends on the right person being in the right place at the right moment, and on a message surviving several retellings. It is also invisible: there is no record that the request was made, how long it took or who eventually handled it.",
        ],
      },
      {
        type: "comparison",
        heading: "Manual requests vs ZapBuzzer, point by point",
        columns: ["Manual requests", "ZapBuzzer"],
        rows: [
          { label: "How you ask", a: "Walk over, shout or leave a note", b: "Choose a catalogue item, note anything extra, then hit Buzz" },
          { label: "Who hears it", a: "Whoever is nearby", b: "The whole responsible team" },
          { label: "Interruptions", a: "Requester leaves their desk or meeting", b: "Requester stays put" },
          { label: "Accuracy", a: "Details lost in retelling", b: "Item, note and destination travel with the request" },
          { label: "Ownership", a: "Implicit", b: "First to accept owns it" },
          { label: "Status", a: "Unknown until it arrives", b: "Accepted, started with ETA, delivered" },
          { label: "Record", a: "None", b: "History and ratings" },
        ],
      },
      {
        type: "visual",
        visual: "mobile-app",
        heading: "The walk to the pantry becomes a tap",
        body: "Employees see a grid of what they can ask for: coffee, tea, prints, IT help, facilities, courier. They choose a destination like Boss Cabin or Conference Room B, add a note if needed and tap Buzz.",
        points: ["Usual order one tap away", "Destination saved with the request", "Works from the web app or the mobile app"],
      },
      {
        type: "problem-solution",
        heading: "What manual requests really cost",
        problem: {
          title: "Hidden costs",
          points: [
            "Requesters leave meetings and desks to ask",
            "Staff get pulled in several directions by whoever reaches them first",
            "Quiet staff who do most of the work get no credit",
            "Managers cannot see where time goes",
          ],
        },
        solution: {
          title: "With ZapBuzzer",
          points: [
            "Requests are made from wherever people are",
            "Staff choose what to accept and their queue is visible",
            "Ratings give fair attribution to the person who delivered",
            "Analytics show busy hours and response times (full analytics on Pro)",
          ],
        },
      },
      {
        type: "scenario",
        heading: "A typical scenario: the CEO’s coffee",
        persona: "Aarav, CEO",
        setting: "In a board call, wants coffee without leaving the room.",
        timeline: [
          { time: "10:14", event: "Aarav taps Coffee, destination Boss Cabin." },
          { time: "10:14", event: "The pantry team is pinged; on Pro they also see it on Telegram." },
          { time: "10:14", event: "Raj accepts in 12 seconds; Aarav sees Raj’s name and photo." },
          { time: "10:18", event: "Coffee delivered; Aarav rates it later." },
        ],
        outcome: "Four minutes, no phone calls, nobody left the board call.",
      },
      {
        type: "audience",
        heading: "Who feels the change first",
        items: [
          { role: "Leadership", benefit: "Ask without stepping out of calls or sending someone." },
          { role: "Pantry and print staff", benefit: "One clear queue instead of being stopped in corridors." },
          { role: "Office manager", benefit: "Finally sees what gets asked for and how long it takes." },
          { role: "Everyone else", benefit: "Knows a request was received, and by whom." },
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Keeping the personal touch",
        body: "Requesters see the name and photo of the person handling their request and rate them when done. Staff are still people, not tickets; they just stop being chased.",
      },
      {"type":"table","heading":"Where a manual request spends its time","intro":"The same coffee from the before-and-after story, broken down.","headers":["Step","Manual","ZapBuzzer"],"rows":[["Asking","Leave the room, find someone","Tap in a few seconds"],["Reaching staff","Message relayed twice","Whole pantry team pinged"],["Confirming","Nobody confirms","Named owner after accept"],["Total","3 calls over 25 minutes; the coffee is cold","No calls, 4 minutes; the coffee is hot"]]},
      {"type":"checklist","heading":"Moving off manual without a fuss","items":["Put the five most common asks in the catalogue","Name destinations the way people already say them","Ask leadership to use it first; others follow","Let staff politely redirect corridor requests to the app for two weeks"]},
    ],
    faqs: [
      {"q":"Is ZapBuzzer impersonal compared with asking face to face?","a":"Requesters see the name and photo of the person handling their request and rate them afterwards, so the human connection stays. What disappears is the walking and waiting."},
      { q: "Our office is small. Is manual not good enough?", a: "It often is, until the one pantry person is busy or away. The Free plan covers up to 10 staff on one floor, so small offices can try a structured flow at no cost." },
      { q: "Do staff need smartphones?", a: "Staff can work from the web app or the Android app. Because the mobile app still rings when a phone is locked or set to silent, it suits staff who are moving around." },
      { q: "Will people still walk over anyway?", a: "Some will at first. Offices usually find habits shift once requesters see that a tap gets a named person and an ETA faster than walking over." },
      { q: "Can we see how long requests take now?", a: "Every request in ZapBuzzer is timed from buzz to delivery, so after a week you have a clear picture. Full analytics and scorecards are on Pro." },
    ],
    related: ["compare", "compare/phone-calls", "features/one-tap-requests", "use-cases/stop-office-chase-calls", "workflows/coffee-request", "pricing/free"],
    cta: { title: "Retire the corridor relay", body: "Try ZapBuzzer free for 14 days. You won't need a card or a setup call." },
  },
  {
    path: "compare/whatsapp",
    title: "ZapBuzzer vs WhatsApp Groups for Office Requests",
    description:
      "Why pantry and print WhatsApp groups lose requests, and how ZapBuzzer keeps WhatsApp alerts while adding ownership, timers, escalation and a proper record.",
    h1: "Your pantry WhatsApp group was never meant to be a request system",
    eyebrow: "Compare",
    lead:
      "WhatsApp groups are where office requests go to get buried. They are fast to set up and everyone is already there, which is why they spread. ZapBuzzer keeps the part that works, the ping on your phone, and fixes the part that does not.",
    keywords: ["whatsapp group office requests", "pantry whatsapp group alternative", "zapbuzzer vs whatsapp", "office requests on whatsapp", "whatsapp request tracking"],
    heroVisual: "notification-flow",
    sections: [
      {
        type: "prose",
        heading: "Why the group stops working",
        paragraphs: [
          "A pantry group starts with five people and one rule: post what you need. Six months later it has forty members, birthday wishes, forwarded videos and three different people asking for tea in the same minute. Someone replies ‘ok’ and nobody is sure which request that ‘ok’ was for.",
          "The core problem is that a chat message has no state. It cannot be accepted, started, delivered or overdue. It just scrolls up. Print files get lost the same way: a PDF posted at 10:40 is twelve messages up by 10:45.",
        ],
      },
      {
        type: "comparison",
        heading: "WhatsApp group vs ZapBuzzer",
        columns: ["WhatsApp group", "ZapBuzzer"],
        rows: [
          { label: "Request format", a: "Free text, often vague", b: "Catalogue item, note and destination" },
          { label: "Ownership", a: "An ‘ok’ that may or may not be for you", b: "Whoever taps Accept first becomes the owner" },
          { label: "Duplicates", a: "Two people make the same tea", b: "Once accepted, others see it is taken" },
          { label: "Missed messages", a: "Scroll past and it is gone", b: "Notifications repeat till accepted" },
          { label: "Deadlines", a: "None", b: "Timed requests; SLA and escalation on Pro" },
          { label: "Print files", a: "Lost in the scroll", b: "PDF attached with copies and colour set" },
          { label: "Reporting", a: "None", b: "History, ratings and analytics" },
        ],
      },
      {
        type: "visual",
        visual: "notification-flow",
        heading: "Still on WhatsApp, now with structure",
        body: "On Pro, one request fans out to the app, Telegram, WhatsApp and email at the same time. Staff keep getting pinged where they already look, but the request itself lives in ZapBuzzer with an owner and a timer.",
        points: ["App, Telegram, WhatsApp and email together on Pro", "Email notifications on Free", "Repeats until someone accepts"],
      },
      {
        type: "problem-solution",
        heading: "From noise to a queue",
        problem: {
          title: "In the group",
          points: ["Requests mixed with chat", "No way to tell what is pending", "Pantry staff answer whoever shouts loudest", "Office manager scrolls to find out what happened"],
        },
        solution: {
          title: "In ZapBuzzer",
          points: ["Each request is its own item", "Pending, accepted and delivered are clear states", "Staff see a queue and accept in order", "Office manager sees history and analytics"],
        },
      },
      {
        type: "scenario",
        heading: "A typical scenario: lunch for 12",
        persona: "Vivek, Operations",
        setting: "Team lunch for 12 people after a planning session.",
        timeline: [
          { time: "12:05", event: "Vivek picks items from the pantry catalogue and adds a note about two vegetarian plates." },
          { time: "12:05", event: "The pantry team is notified; the request is queued with every detail." },
          { time: "12:06", event: "A pantry staff member accepts and sets an ETA." },
          { time: "12:40", event: "Lunch is delivered; Vivek rates the delivery." },
          { time: "12:41", event: "The owner can see what the lunch order cost." },
        ],
        outcome: "No 40-message thread about who wanted what, and a clear record of cost for the owner.",
      },
      {
        type: "stats",
        heading: "Month-one results from pilot offices",
        items: [
          { value: "32s", label: "Average accept time" },
          { value: "96%", label: "On-time delivery" },
          { value: "−87%", label: "Phone calls" },
          { value: "4.8★", label: "Average staff rating" },
        ],
        note: "Figures from ZapBuzzer pilot offices in their first month.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "In Priya’s words",
        body: "“Coffee arrives before anyone asks twice. The pantry WhatsApp group is finally quiet.” — Priya, Office Manager",
      },
      {"type":"workflow","heading":"Moving requests out of the group in a week","steps":[{"title":"Day 1","body":"Pick one request type, usually coffee or prints, and set it up in the catalogue."},{"title":"Day 2","body":"Pin a message in the group asking people to send that request through ZapBuzzer instead."},{"title":"Days 3–5","body":"Pantry staff reply to stray group requests with a reminder to buzz it."},{"title":"End of week","body":"Look at accept times and decide which request type moves next."}]},
      {"type":"callout","tone":"info","title":"WhatsApp stays, as a channel","body":"On Pro, WhatsApp is one of the channels requests notify on. The difference is that the request itself has an owner, a state and a timer instead of being a line in a chat."},
    ],
    faqs: [
      {"q":"What about print files people currently send in the group?","a":"In ZapBuzzer the PDF is uploaded with the request itself, along with copies, colour and destination, so it never scrolls out of sight."},
      {"q":"Does the group admin lose control?","a":"The office manager gains it. Roles and permissions decide who handles what, and on Pro every action is audit-logged."},
      { q: "Do we need to shut down our WhatsApp group?", a: "No. Many offices keep it for chat. Requests simply move to ZapBuzzer, and on Pro the pantry still gets request alerts on WhatsApp." },
      { q: "Is WhatsApp notification available on the Free plan?", a: "No. Free includes email notifications plus the web and mobile app. Telegram and WhatsApp pings are part of Pro at ₹99 per seat per month." },
      { q: "Is ZapBuzzer just a WhatsApp bot?", a: "No. ZapBuzzer is an internal-request CRM with a catalogue, first-accept ownership, timers, ratings and analytics. WhatsApp is one of the channels it can notify on." },
      { q: "What happens if nobody responds on WhatsApp?", a: "Notifications repeat until someone accepts. On Pro, overdue requests also escalate through your escalation chain to a manager." },
      { q: "Can we try it alongside the group first?", a: "Yes. Start the 14-day trial, route one request type such as coffee through ZapBuzzer, and keep the group running for everything else until you are ready." },
    ],
    related: ["compare", "compare/phone-calls", "notifications/whatsapp", "use-cases/reduce-whatsapp-requests", "notifications/multi-channel", "pricing/pro", "free-trial"],
    cta: { title: "Make the pantry group quiet", body: "Start your 14-day free trial and move one request type out of WhatsApp this week." },
  },
  {
    path: "compare/phone-calls",
    title: "ZapBuzzer vs Phone Calls and Intercom Requests",
    description:
      "Three calls for one coffee is the norm in many offices. Compare phone and intercom requests with ZapBuzzer’s one-tap flow, named owner, ETA and fewer calls.",
    h1: "Three calls for one coffee: phone requests vs one tap",
    eyebrow: "Compare",
    lead:
      "ZapBuzzer started in a Pune office tired of phone tag. Calling the pantry, the print room or the admin desk feels direct, but every call interrupts two people and still leaves nothing on record. Here is how phone requests compare.",
    keywords: ["reduce office phone calls", "intercom requests alternative", "zapbuzzer vs phone calls", "phone tag office", "office request calls"],
    heroVisual: "before-after",
    sections: [
      {
        type: "prose",
        heading: "Why calls feel efficient and are not",
        paragraphs: [
          "A call gets an immediate human response, when it connects. In practice the pantry extension rings out because Raju is carrying a tray, the admin desk is engaged and the print room number is on a sticky note nobody can find. One coffee can take three calls.",
          "Calls also interrupt both sides. The requester stops what they are doing to dial and wait; the staff member stops what they are doing to answer. And when the call ends, nothing remains: no record of what was asked, who agreed and when it was done.",
        ],
      },
      {
        type: "comparison",
        heading: "Phone and intercom vs ZapBuzzer",
        columns: ["Phone and intercom", "ZapBuzzer"],
        rows: [
          { label: "Reaches", a: "One person, if they pick up", b: "The whole team at once" },
          { label: "Busy line or no answer", a: "Call again, and again", b: "Notifications repeat till accepted" },
          { label: "During meetings", a: "Requester has to step out", b: "Silent tap from the table" },
          { label: "Staff on the move", a: "Juggling a tray and a phone", b: "Mobile app rings even on silent; accept with one tap" },
          { label: "Confirmation", a: "A verbal ‘haan, coming’", b: "Name, photo and ETA on screen" },
          { label: "Record", a: "None", b: "Timed request with history and rating" },
        ],
      },
      {
        type: "visual",
        visual: "staff-queue",
        heading: "Staff get a queue instead of a ringing phone",
        body: "Instead of answering calls one at a time, staff see open requests with what, where and when. They accept what they can handle, and the requester gets confirmation automatically.",
      },
      {
        type: "stats",
        heading: "Pilot offices, first month",
        items: [
          { value: "−87%", label: "Phone calls" },
          { value: "32s", label: "Average accept time" },
          { value: "96%", label: "On-time delivery" },
        ],
        note: "Measured across ZapBuzzer pilot offices in their first month of use.",
      },
      {
        type: "scenario",
        heading: "A typical scenario: AC stuck at 16°C",
        persona: "Om, Engineer",
        setting: "Conference Room B is freezing ahead of a client call.",
        timeline: [
          { time: "14:02", event: "Om taps Facilities and notes the AC is stuck at 16°C in Conference Room B." },
          { time: "14:02", event: "The facilities team, including Deepak, is pinged together." },
          { time: "14:03", event: "Deepak accepts; Om sees him on it." },
          { time: "14:17", event: "On Pro, had it not been fixed within the 15-minute SLA, it would have escalated to a manager automatically." },
        ],
        outcome: "No hunting for the facilities extension. As Deepak says: “Facilities tickets auto-escalate now. Nothing rots in someone’s DMs.”",
      },
      {
        type: "problem-solution",
        heading: "What changes for reception and admin desks",
        problem: { title: "Today", points: ["The front desk phone is the default router for everything", "Calls arrive while visitors are waiting", "Requests are passed on verbally and forgotten"] },
        solution: { title: "With ZapBuzzer", points: ["Requests go directly to the responsible team", "Reception handles courier pickups through its own flow", "Every handoff is recorded"] },
      },
      {
        type: "callout",
        tone: "info",
        title: "Emergencies still matter",
        body: "The mobile app also lets people summon staff or security and raise an emergency with one tap. It rings through even on a silent or locked phone, so urgent asks are not lost to a busy line.",
      },
      {"type":"table","heading":"Counting the calls in one coffee","intro":"The before-and-after we hear most often, side by side.","headers":["","Phone","ZapBuzzer"],"rows":[["Calls made","3","0"],["Time to delivery","25 minutes","4 minutes"],["Coffee temperature","Cold","Hot"],["Record of the request","None","Timed, with an owner and a rating"]]},
      {"type":"workflow","heading":"How to measure your own call volume","steps":[{"title":"Week 0","body":"Ask pantry, print and admin staff to tally calls about requests for one week."},{"title":"Week 1","body":"Move the most-called request type into ZapBuzzer."},{"title":"Week 2","body":"Tally again and compare; check accept times in ZapBuzzer for the same requests."}]},
    ],
    faqs: [
      {"q":"What about the intercom?","a":"The intercom has the same limits as a phone: it reaches one extension, depends on someone being there and leaves no record. ZapBuzzer pings the whole team and records the request."},
      {"q":"How do staff know a request is urgent without a call?","a":"The note travels with the request, and on Pro each request has an SLA deadline that escalates if it runs over."},
      { q: "Will staff stop answering calls entirely?", a: "That is up to your office. Most find calls drop sharply once requests come through ZapBuzzer; pilot offices saw phone calls fall 87% in the first month." },
      { q: "What if a staff member’s phone is on silent?", a: "A silent or locked phone still rings with the ZapBuzzer mobile app, and notifications repeat until someone accepts." },
      { q: "Can older staff use it?", a: "Accepting a request is a single tap on a clear button. Requesters pick from a picture-style grid, so there is little to learn on either side." },
      { q: "Does it work without the mobile app?", a: "Yes. There is a web app as well. On Free, notifications go by email; on Pro you can add Telegram and WhatsApp." },
    ],
    related: ["compare", "compare/manual-requests", "use-cases/reduce-phone-calls", "use-cases/stop-office-chase-calls", "mobile-app", "workflows/ac-issue", "free-trial"],
    cta: { title: "End phone tag in your office", body: "Start free for 14 days and count your calls at the end of week one." },
  },
  {
    path: "compare/helpdesk",
    title: "ZapBuzzer vs a Traditional Helpdesk",
    description:
      "Helpdesks are built for IT tickets. Compare a traditional ticketing tool with ZapBuzzer for quick asks like coffee, prints, HDMI cables and courier pickups.",
    h1: "A helpdesk is built for tickets. Most office requests are not tickets.",
    eyebrow: "Compare",
    lead:
      "Traditional helpdesks are good at long-running issues: a laptop rebuild, a software licence, a network fault. They are slow and heavy for a two-minute ask like an HDMI cable or two coffees. ZapBuzzer is built for the short end.",
    keywords: ["helpdesk alternative office requests", "zapbuzzer vs helpdesk", "ticketing tool for facilities", "office request crm", "lightweight helpdesk"],
    heroVisual: "acceptance",
    sections: [
      {
        type: "prose",
        heading: "Different jobs, different tools",
        paragraphs: [
          "A helpdesk ticket usually starts with a form: category, subcategory, priority, description. It goes into a queue, gets triaged and is assigned. That process makes sense when the work takes hours or days and needs a careful trail.",
          "Tanvi’s HDMI cable does not need triage. She needs someone from IT to bring one to the meeting room in the next few minutes. If she has to fill a form and wait for assignment, she will just message someone directly, and the helpdesk never hears about it. ZapBuzzer is designed for that kind of request: one tap, the whole team pinged, first person free takes it.",
        ],
      },
      {
        type: "comparison",
        heading: "Traditional helpdesk vs ZapBuzzer",
        columns: ["Traditional helpdesk", "ZapBuzzer"],
        rows: [
          { label: "Built for", a: "IT incidents and longer tickets", b: "Quick internal requests across pantry, print, IT, facilities, courier" },
          { label: "Raising a request", a: "Form with several fields", b: "Choose a catalogue item, note anything extra, then hit Buzz" },
          { label: "Assignment", a: "Triage, then assign", b: "First to accept owns it" },
          { label: "Staff alerts", a: "Usually email or in-tool", b: "App and email; Telegram and WhatsApp on Pro; repeats till accepted" },
          { label: "Requester visibility", a: "Ticket status page", b: "Name, photo, ETA and delivery photo" },
          { label: "Feedback", a: "Optional survey", b: "1–5★ rating on every delivery" },
          { label: "Setup", a: "Often a project", b: "Live within an afternoon, with no consultant" },
        ],
      },
      {
        type: "visual",
        visual: "acceptance",
        heading: "No triage queue for a two-minute job",
        body: "A request goes to every member of the responsible team. The first person who is free taps Accept and owns it; the rest see it is taken. For small jobs, that beats waiting for a dispatcher.",
      },
      {
        type: "scenario",
        heading: "A typical scenario: the missing HDMI cable",
        persona: "Tanvi, Design",
        setting: "Presenting in five minutes, no HDMI cable in the room.",
        timeline: [
          { time: "15:25", event: "Tanvi taps IT and notes she needs an HDMI cable in Meeting Room 2." },
          { time: "15:25", event: "The IT desk is pinged together." },
          { time: "15:26", event: "Priya accepts and heads over." },
          { time: "15:28", event: "Cable delivered in 3 minutes; Tanvi rates it." },
        ],
        outcome: "The request is on record without anyone filing a ticket.",
      },
      {
        type: "table",
        heading: "Where each tool fits",
        headers: ["Request", "Helpdesk", "ZapBuzzer"],
        rows: [
          ["Laptop rebuild", "Good fit", "Possible, but not its focus"],
          ["HDMI cable to a meeting room", "Too heavy", "Good fit"],
          ["Projector stuck before a meeting", "Slow", "Good fit"],
          ["AC too cold", "Often not covered", "Good fit, with SLA and escalation on Pro"],
          ["Coffee to the boss cabin", "Not covered", "Good fit"],
          ["Courier pickup at reception", "Not covered", "Good fit, audit-trailed"],
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Need to connect ZapBuzzer to other systems?",
        body: "A REST API and webhooks are available on the Enterprise plan for organisations that want to connect ZapBuzzer with their own tools. Talk to us for details.",
      },
      {"type":"problem-solution","heading":"Why quick requests escape the helpdesk","problem":{"title":"What happens with a ticket tool","points":["People skip the form for small asks and message someone directly","Pantry, print and courier requests have no home at all","The two-minute jobs never show up in any report"]},"solution":{"title":"What happens with ZapBuzzer","points":["A tap is faster than messaging, so requests stay in the system","Every service team works from the same catalogue","Small jobs are timed and rated like everything else"]}},
      {"type":"checklist","heading":"Running both side by side","items":["Keep laptop builds, licences and network faults in the helpdesk","Move cables, projectors, AC, pantry, print and courier to ZapBuzzer","Tell IT staff which tool owns which kind of request","Review after a month and adjust the split"]},
    ],
    faqs: [
      {"q":"Will IT staff have to watch two tools?","a":"For a while, yes, but they serve different jobs. ZapBuzzer’s mobile app rings through for quick asks, so staff do not need to keep a second screen open."},
      {"q":"Does ZapBuzzer keep a record like a ticket?","a":"Yes. Every request is timed from buzz to delivery, with the owner, any delivery photo and the rating. Audit logs and reports are on Pro."},
      { q: "Should we replace our helpdesk with ZapBuzzer?", a: "Not if your IT team relies on it for complex incidents. Many offices keep the helpdesk for those and use ZapBuzzer for quick requests across pantry, print, facilities, courier and small IT asks." },
      { q: "Does ZapBuzzer have SLAs like a helpdesk?", a: "Every request is timed. SLA deadlines and an escalation chain that pushes overdue requests to a manager are part of the Pro plan." },
      { q: "Can ZapBuzzer send data to our helpdesk?", a: "The Enterprise plan includes a REST API and webhooks for connecting to other systems. Contact us to discuss your setup." },
      { q: "How long does setup take?", a: "Most offices are running in an afternoon. There are no setup fees and no consultant; you sign up and invite your team." },
    ],
    related: ["compare", "compare/whatsapp", "solutions/it-support", "workflows/hdmi-request", "sla", "pricing/enterprise", "demo"],
    cta: { title: "Keep tickets for tickets", body: "Move quick requests to ZapBuzzer with a 14-day free trial." },
  },
];
