import type { PageContent } from "../types";

export const pages: PageContent[] = [
  {
    path: "enterprise/enterprise-rollout",
    title: "Enterprise Rollout Plan for Office Request Software",
    description:
      "How groups and facility companies roll out ZapBuzzer across floors and sites: pilot one office, shape catalogues, add teams, then expand with a dedicated CSM.",
    h1: "Roll Out ZapBuzzer Across a Group, One Office at a Time",
    eyebrow: "Enterprise · Rollout",
    lead:
      "A rollout across a group of offices is not a big-bang software launch. It is one pantry, one print room and one IT desk learning that a tap replaces three phone calls, then the next site copying what worked.",
    keywords: [
      "enterprise rollout office software",
      "multi-office request system rollout",
      "facility company rollout",
      "zapbuzzer enterprise onboarding",
      "office request crm deployment",
    ],
    heroVisual: "request-dashboard",
    sections: [
      {
        type: "prose",
        eyebrow: "Why Rollout Matters",
        heading: "The Software Is Quick. The Habit Change Is the Real Project.",
        paragraphs: [
          "ZapBuzzer is designed so an office can go live within one afternoon: you sign up and invite your team, with no consultant and no setup fees. For a single floor that really is the whole story. For a group with several offices, or a facility company running pantries and mailrooms for many clients, the hard part is not configuration. It is getting 400 people to stop shouting “Raju, two coffees” down the corridor.",
          "An Enterprise rollout is paced around that habit change. You start where the pain is loudest, prove the numbers, and let each new site borrow a catalogue and routing setup that already works instead of designing from scratch.",
        ],
      },
      {
        type: "workflow",
        heading: "A Typical Rollout, Phase by Phase",
        intro: "Every group is different, and your dedicated CSM (customer success manager) will shape the plan with you. This is the pattern most rollouts follow.",
        steps: [
          { title: "Pick a Pilot Office", body: "Choose one site with a busy pantry and a print room that gets chased. Head office is often the right choice because leadership feels the difference first." },
          { title: "Build the Catalogue", body: "List what people actually ask for: coffee, tea, 24 colour copies, HDMI cable, AC too cold, courier pickup. Keep it short; you can add items later." },
          { title: "Set Up Teams and Routing", body: "Create the pantry team, print room, IT desk and facilities team so each request reaches the people who can act on it, with first-accept-wins deciding who owns it." },
          { title: "Agree SLAs and Escalation", body: "Decide what “late” means per category and who gets escalated to. A coffee and a broken projector before a board meeting deserve different clocks." },
          { title: "Run the Pilot for a Month", body: "Watch accept times, on-time delivery and ratings. In our pilot offices the first month averaged a 32-second accept time and 96% on-time delivery." },
          { title: "Template and Expand", body: "Copy the working setup to the next location, adjust for local staff and rooms, and repeat. Each site goes faster than the last." },
        ],
      },
      {
        type: "visual",
        visual: "request-dashboard",
        heading: "What the Pilot Office Sees on Day One",
        body: "Admins get a live queue of every request in the building: who asked, which team, who accepted, and how long it has been open. It is the first time many office managers can actually see the load on the pantry or the IT desk.",
        points: [
          "Every request timed from buzz to delivery",
          "Open, accepted, started and delivered states at a glance",
          "Overdue items stand out before anyone complains",
        ],
      },
      {
        type: "scenario",
        heading: "Pilot Week at a Pune Head Office",
        persona: "Priya, Office Manager",
        setting: "Week one of a group pilot; 120 staff, one pantry on the 3rd floor, one print room.",
        timeline: [
          { time: "Mon 09:30", event: "Priya invites the pantry team and print room staff; they install the Android app and join." },
          { time: "Mon 11:00", event: "Aarav taps Coffee → Boss Cabin during a board call. Raj accepts in 12 seconds." },
          { time: "Wed 15:10", event: "Kavya uploads a pitch PDF for 24 colour copies; they reach her desk before the client sits down." },
          { time: "Fri 17:00", event: "Priya reviews the week: average accept time, ratings, and which hours the pantry is busiest." },
        ],
        outcome: "By Friday the pantry WhatsApp group is quiet and Priya has numbers to show the other offices in the group.",
      },
      {
        type: "checklist",
        heading: "Before You Add the Next Location",
        items: [
          "Pilot staff are accepting from the app without reminders",
          "Catalogue items match what people actually request",
          "SLA times feel fair to both requesters and staff",
          "Escalation reaches a real manager who acts on it",
          "Office owner has reviewed costs and scorecards",
          "A short internal note explains how to buzz instead of calling",
        ],
      },
      {
        type: "stats",
        heading: "What Pilot Offices Saw in Month One",
        items: [
          { value: "32s", label: "Average Accept Time" },
          { value: "96%", label: "On-Time Delivery" },
          { value: "−87%", label: "Phone Calls" },
          { value: "4.8★", label: "Average Staff Rating" },
        ],
        note: "Figures from ZapBuzzer pilot offices in their first month. Your results depend on your office.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Start With the Loudest Request",
        body: "Do not launch every catalogue on day one. If coffee chase calls are the daily irritation, start with the pantry. Once people trust that a tap works, print, IT and courier follow easily.",
      },
      {
        type: "prose",
        heading: "Who Helps You on Enterprise",
        paragraphs: [
          "Enterprise customers get a dedicated customer success manager who knows your rollout plan and your sites. They help with sequencing, catalogue design and reading the first month of analytics. Enterprise options are planned with you during onboarding, not bolted on later. These include SSO (staff sign in with their company login), white-label with a custom domain (the app under your brand and web address), the REST API and webhooks (for connecting your own systems) and an on-prem deployment (running ZapBuzzer on your own servers).",
        ],
      },
    ],
    faqs: [
      { q: "How Long Does an Enterprise Rollout Take?", a: "A single office can be live in an afternoon. A group rollout is paced by how quickly each site adopts the habit, so most groups pilot one office for a few weeks and then expand site by site. Your CSM will help set a realistic timeline." },
      { q: "Can We Try ZapBuzzer Before Committing to Enterprise?", a: "Yes. ZapBuzzer offers a 14-day free trial with no credit card and no setup call. Many groups pilot one office on the trial or on Pro before moving to Enterprise for the whole group." },
      { q: "Do We Need a Consultant or IT Project?", a: "No. There are no setup fees and no consultant. Enterprise options like SSO or on-prem involve your IT team, and we work through them with you during onboarding." },
      { q: "Can Each Office Have Its Own Catalogue?", a: "Yes. Locations differ: one has a print room, another only a pantry. You can shape catalogues and teams per location while keeping one view for the group." },
      { q: "What Does the Dedicated CSM Do During Rollout?", a: "They help plan the order of sites, review catalogues and routing, and walk through early analytics with you. They are your single point of contact for Enterprise options." },
      { q: "Which Office Should We Pilot First?", a: "Pick a site with a busy pantry, print room or front desk and a manager keen to try it. Early analytics from that office show other sites what to expect before they go live." },
      { q: "How Do We Get Staff at Each Site to Actually Use It?", a: "Set up the catalogue items people already ask for, such as coffee, prints and IT help, and route them to teams. When requests arrive faster than a phone call, the habit spreads on its own." },
      { q: "When Should SSO and White-Label Be Switched on During Rollout?", a: "Identity and branding are usually set up after the pilot site, before the wider rollout, so every later office joins with company sign-in and your branding from day one." },
    ],
    related: ["enterprise", "enterprise/multi-location", "enterprise/enterprise-support", "how-it-works", "use-cases/office-manager", "pricing/enterprise-plan", "free-trial"],
    cta: { title: "Plan Your Rollout", body: "Tell us how many offices you run and where the chase calls hurt most. We will suggest a pilot and a path to the rest of the group." },
  },
  {
    path: "enterprise/security",
    title: "Enterprise Security for Office Requests",
    description:
      "How ZapBuzzer Enterprise approaches security: SSO and SAML sign-in, role-based permissions, full audit logs, owner-only spend and an on-prem option for groups.",
    h1: "Security That Fits How a Real Office Works",
    eyebrow: "Enterprise · Security",
    lead:
      "An internal-request tool sees who asked for what, where, and at what cost. Enterprise gives you the controls to keep that tidy: single sign-on, roles, an audit log of every action and, if you need it, an on-prem deployment.",
    keywords: [
      "office request software security",
      "enterprise sso saml office app",
      "audit log internal requests",
      "on-prem office request system",
      "role based access office crm",
    ],
    heroVisual: "roles",
    sections: [
      {
        type: "prose",
        heading: "What There Is to Protect",
        paragraphs: [
          "ZapBuzzer is not a bank, but it does hold real information: staff names and photos, who requested what and when, which rooms people sit in, and what a lunch order for twelve cost. In a group of offices that adds up to a detailed picture of daily operations.",
          "Our approach is simple and practical: people sign in the way your company already signs in, they see only what their role needs, every action leaves a trace, and costs stay with the owner. For groups with strict data requirements, Enterprise also offers an on-prem option.",
        ],
      },
      {
        type: "features",
        heading: "The Controls Available on Enterprise",
        items: [
          { title: "SSO and SAML", body: "Let staff sign in with your company identity provider instead of separate passwords. Leavers lose access when their company account is closed. Setup details are worked out with your IT team during onboarding." },
          { title: "Detailed Roles", body: "Requesters, staff, managers and owners each see different things. Permissions are set per role so a pantry staffer never sees owner-only spend." },
          { title: "Audit Log", body: "Every action is audit-logged: who buzzed, who accepted, who changed a setting. Useful for disputes and for internal reviews." },
          { title: "Owner-Only Spend View", body: "Request costs, such as a team lunch, are visible to the owner and not to everyone in the office." },
          { title: "On-Prem Option", body: "On-prem means running ZapBuzzer on your own servers. For groups that need this, we can plan it with you." },
          { title: "Server-Side Accounts", body: "Accounts and workspaces live on the server, not on individual phones, so a lost handset does not mean lost history." },
        ],
      },
      {
        type: "visual",
        visual: "roles",
        heading: "Least Access by Default",
        body: "A simple permissions table shows who can do what. Most people only need to buzz and rate; staff need to accept and deliver; managers need escalations and reports; owners see costs.",
        points: ["Requesters: buzz, track, rate", "Staff: accept, start, deliver", "Managers: escalations, team reports", "Owners: spend, settings, everything"],
      },
      {
        type: "problem-solution",
        heading: "From WhatsApp Groups to an Accountable Record",
        problem: {
          title: "Requests in Chat Apps",
          points: [
            "Personal numbers shared across the whole pantry group",
            "Ex-employees still sitting in the group months later",
            "No record of who agreed to do what",
            "Costs discussed in public threads",
          ],
        },
        solution: {
          title: "Requests in ZapBuzzer",
          points: [
            "Access tied to roles and, on Enterprise, to your SSO",
            "Removing a user removes their access",
            "Audit log shows each accept, start and delivery",
            "Spend visible only to the owner",
          ],
        },
      },
      {
        type: "scenario",
        heading: "An Access Review at a Facility Company",
        persona: "Deepak, Admin Head",
        setting: "Quarterly review of who can see what across three client sites.",
        timeline: [
          { time: "10:00", event: "Deepak opens the roles view and checks which staff have manager rights at each site." },
          { time: "10:20", event: "He spots a contractor who moved on last month; access already ended when the company account was closed through SSO." },
          { time: "10:35", event: "He pulls the audit log for a disputed late delivery and sees exactly when it was accepted and escalated." },
        ],
        outcome: "The review takes under an hour, with evidence instead of memory.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Need a Security Questionnaire Answered?",
        body: "Write to hello@zapbuzzer.com with your requirements. We answer honestly about what ZapBuzzer does today and discuss Enterprise options such as on-prem where your policy needs them.",
      },
      {
        type: "checklist",
        heading: "Good Practice for Your Own Setup",
        items: [
          "Give most people the requester role only",
          "Limit owner rights to the people who sign off spend",
          "Use SSO so leavers lose access automatically",
          "Review roles each quarter",
          "Check the audit log when a request is disputed",
        ],
      },
    ],
    faqs: [
      { q: "Does ZapBuzzer Hold Security Certifications?", a: "We do not list certifications on this site. If your procurement team has specific requirements, email hello@zapbuzzer.com and we will tell you plainly what we can and cannot meet, including whether an on-prem deployment helps." },
      { q: "Which Plan Includes SSO and SAML?", a: "SSO and SAML are part of the Enterprise plan. Pro includes roles and audit logs; Enterprise adds company sign-in, white-label, API access, a dedicated CSM and an on-prem option." },
      { q: "Can Staff See What a Lunch Order Cost?", a: "No. Request cost visibility is owner-only. Staff see what to deliver and where, not the spend." },
      { q: "What Happens to Data If a Phone Is Lost?", a: "Accounts and workspaces live on the server, so history is not stored only on the device. Removing or disabling that user stops access." },
      { q: "What Does the On-Prem Option Involve?", a: "It means running ZapBuzzer in your own environment rather than ours. The details depend on your infrastructure, so it is scoped with you during Enterprise onboarding." },
      { q: "Can We Restrict What Each Role Is Allowed to Do?", a: "Yes. Each role has its own permissions, so requesters, staff, managers and admins only see and do what their role allows." },
      { q: "Is Every Change in the Workspace Recorded for Security Reviews?", a: "Yes. Every action is audit-logged against a named person and a time, which gives your security team a trail to review." },
      { q: "How Do We Ask Security Questions Before Buying?", a: "Email hello@zapbuzzer.com with your questionnaire or requirements. We reply within one business day and will be clear about anything we cannot meet." },
    ],
    related: ["enterprise", "integrations/sso-and-saml", "enterprise/enterprise-permissions", "enterprise/enterprise-audit-logs", "administration/roles-and-permissions", "pricing/enterprise-plan", "contact-us"],
    cta: { title: "Talk Security With Us", body: "Share your requirements and we will walk through SSO, roles, audit logs and on-prem options for your group." },
  },
  {
    path: "enterprise/enterprise-administration",
    title: "Enterprise Administration Across Offices",
    description:
      "Administer ZapBuzzer for a whole group: central owners, local admins per office, shared catalogues, team routing, SLA policies and a CSM to help you run it.",
    h1: "Run Every Office’s Requests From One Place, Without Micromanaging Any of Them",
    eyebrow: "Enterprise · Administration",
    lead:
      "Group administration is about balance. Head office wants consistent standards and one view of performance; each site wants to run its own pantry and print room. Enterprise is set up for both.",
    keywords: [
      "enterprise office administration software",
      "central admin multiple offices",
      "office request admin console",
      "facility management administration",
    ],
    heroVisual: "request-dashboard",
    sections: [
      {
        type: "prose",
        heading: "Central Standards, Local Control",
        paragraphs: [
          "In a single office, one office manager can own everything: the catalogue, the teams, the SLAs. In a group, that person becomes a bottleneck. Enterprise administration splits the job sensibly. Owners at head office decide what “on time” means and who sees spend. Local admins add their own staff, rooms and items, and handle the day-to-day.",
          "So the Bengaluru office can add filter coffee to its menu without a ticket to Pune, while the group still reports on one consistent set of numbers.",
        ],
      },
      {
        type: "audience",
        heading: "Who Does What",
        items: [
          { role: "Group Owner", benefit: "Sets policies, sees spend and analytics across all locations, approves admin rights." },
          { role: "Location Admin", benefit: "Manages local staff, rooms, catalogue items and teams for one office." },
          { role: "Team Manager", benefit: "Receives escalations, watches scorecards and keeps the pantry or IT desk on time." },
          { role: "Staff", benefit: "Accept and deliver requests from the app, with fair credit for their work." },
          { role: "Employees", benefit: "Tap what they need and see who is on it." },
        ],
      },
      {
        type: "features",
        heading: "What Administrators Manage",
        items: [
          { title: "Catalogues", body: "Pantry, print, IT, facilities and courier items, shaped per location." },
          { title: "Teams and Routing", body: "Which team receives which category, so an AC complaint goes to facilities and not the pantry." },
          { title: "SLA and Escalation", body: "Deadlines per category and an escalation chain to managers when requests run late." },
          { title: "Notification Channels", body: "App, Telegram, WhatsApp and email pings, repeating until someone accepts." },
          { title: "Roles", body: "Who can buzz, accept, manage, or see owner-only spend." },
          { title: "Branding", body: "On Enterprise, white-label and a custom domain so the app looks like your own." },
        ],
      },
      {
        type: "visual",
        visual: "escalation",
        heading: "Escalation Policies Set Once, Applied Everywhere",
        body: "Admins define who gets escalated to when something runs late. A projector stuck before a board meeting climbs from the IT desk to the IT lead to the admin head, without anyone having to remember to chase.",
      },
      {
        type: "scenario",
        heading: "Opening a New Floor",
        persona: "Neha, Location Admin",
        setting: "The group leases a new 5th floor with two conference rooms and a mini pantry.",
        timeline: [
          { time: "09:00", event: "Neha adds the floor, Conference Room C and D, and the new mini pantry as destinations." },
          { time: "09:20", event: "She assigns two pantry staff and reuses the group’s standard coffee and tea items." },
          { time: "09:40", event: "Group SLAs and escalation apply automatically; she sends the invite link to the floor." },
          { time: "11:05", event: "First buzz from the floor: two teas to Conference Room C, accepted in under a minute." },
        ],
        outcome: "A new floor is live before lunch, with group standards intact.",
      },
      {
        type: "comparison",
        heading: "Admin Effort, Before and After",
        columns: ["Spreadsheets and Chat Groups", "ZapBuzzer Enterprise"],
        rows: [
          { label: "Adding Staff", a: "Add to five WhatsApp groups", b: "Invite once, assign to a team" },
          { label: "Changing a Policy", a: "Email every office manager", b: "Update once for the group" },
          { label: "Knowing Who Is Overloaded", a: "Guesswork", b: "Scorecards and request counts" },
          { label: "Removing a Leaver", a: "Hope someone remembers", b: "Remove the user, or let SSO handle it" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Keep Admin Rights Small",
        body: "Two or three location admins per office is usually plenty. Everyone else only needs to buzz or accept.",
      },
      {"type":"checklist","heading":"A Monthly Admin Routine","items":["Review escalations by team and adjust any SLA that fires every day.","Remove leavers and check new joiners landed on the right team.","Retire catalogue items nobody has requested in a month.","Skim the audit log for setting changes you did not expect.","Share one piece of good news from the scorecards with the staff."]},
      {"type":"callout","tone":"tip","title":"Change One Setting at a Time","body":"If you shorten the pantry SLA and change the escalation chain in the same week, you will not know which one moved the numbers. Make one change, watch for a week, then make the next."},
    ],
    faqs: [
      {"q":"How Many Admins Does a Group Need?","a":"Usually one per location plus one or two at group level. More admins than that tends to mean settings drift. Your CSM on Enterprise can suggest a structure for your offices."},
      { q: "Can Each Office Manage Its Own Catalogue?", a: "Yes. Location admins can shape items and teams for their site while group owners keep oversight. Exactly how you split rights is something your CSM can help design." },
      { q: "Is Administration Different on Pro?", a: "Pro already includes multi-location, roles, SLA with escalation chains and audit logs. Enterprise adds SSO, white-label, API and webhooks, an on-prem option and a dedicated CSM for groups." },
      { q: "Who Receives Escalations?", a: "Whoever you set in the escalation chain, typically the team manager first and then an admin head. Overdue requests escalate automatically." },
      { q: "Can We Change Settings Without Breaking Live Requests?", a: "Settings apply to how requests are handled going forward. If you are planning a big change, your CSM can help you time it outside peak hours." },
      { q: "How Many Admins Should Each Office Have?", a: "Two or three location admins per office is usually plenty. Everyone else only needs to buzz requests or accept them, which keeps admin rights small and easy to audit." },
      { q: "Can Admins See Who Changed a Setting?", a: "Yes. Every action is audit-logged, including changes to catalogues, teams, roles and settings, so admins can see who changed what and when." },
      { q: "Can We Run the Admin Console Under Our Own Brand?", a: "Enterprise includes white-label and a custom domain, which suits facility companies managing sites for clients. Talk to us about how far branding goes for your setup." },
    ],
    related: ["enterprise", "enterprise/enterprise-user-management", "enterprise/enterprise-permissions", "administration", "administration/team-management", "sla-and-escalation/escalation-chains", "pricing/enterprise-plan"],
    cta: { title: "See Group Administration", body: "Book a walkthrough and we will show how owners and location admins share the work." },
  },
  {
    path: "enterprise/enterprise-analytics",
    title: "Enterprise Analytics for Office Operations",
    description:
      "Compare accept times, on-time delivery, ratings and request volume across every office in your group. ZapBuzzer Enterprise analytics for operations leaders.",
    h1: "See How Every Office in the Group Really Runs",
    eyebrow: "Enterprise · Analytics",
    lead:
      "Every ZapBuzzer request is timed, from buzz to accept to delivery to rating. Across a group, those timings become a fair, side-by-side picture of how each office, team and person is doing.",
    keywords: [
      "office operations analytics",
      "multi-office performance dashboard",
      "staff scorecard analytics",
      "facility services analytics",
      "request accept time analytics",
    ],
    heroVisual: "analytics",
    sections: [
      {
        type: "prose",
        heading: "Questions Group Leaders Can Finally Answer",
        paragraphs: [
          "Which office has the slowest pantry? Is the print room at the Mumbai site overloaded on Monday mornings? Did the new facilities contractor actually improve AC response times? Without data, these are arguments. With ZapBuzzer, they are a few clicks.",
          "Full analytics and scorecards start on Pro. Enterprise adds what groups need around them: the REST API and webhooks, which send ZapBuzzer data automatically into your own reporting tools, and a dedicated CSM (customer success manager) to help you read the numbers.",
        ],
      },
      {
        type: "metrics",
        heading: "The Numbers That Matter",
        items: [
          { metric: "Accept Time", meaning: "How long from buzz until someone taps Accept. The clearest sign a team is paying attention." },
          { metric: "On-Time Delivery", meaning: "Share of requests delivered within their SLA." },
          { metric: "Escalations", meaning: "How often requests ran late enough to reach a manager." },
          { metric: "Ratings", meaning: "Average stars from requesters, per team and per person." },
          { metric: "Volume by Hour", meaning: "When the office buzzes most, so you can staff the pantry at 11 and 4." },
          { metric: "Cost", meaning: "Owner-only view of what requests such as lunches cost." },
        ],
      },
      {
        type: "visual",
        visual: "analytics",
        heading: "Key Numbers per Location, Side by Side",
        body: "Tiles show accept time, on-time percentage and ratings; the chart shows when requests peak. Filter by office or team to compare like with like.",
      },
      {
        type: "visual",
        visual: "scorecard",
        heading: "Scorecards That Credit People Fairly",
        body: "First-accept-wins means every request has a clear owner, so credit goes to whoever actually did the work. Scorecards show who is fastest and who earns 5 stars, which helps managers recognise good staff, not just chase slow ones.",
      },
      {
        type: "scenario",
        heading: "A Monthly Operations Review",
        persona: "Vivek, Operations Head",
        setting: "Group of four offices; monthly review with each office manager.",
        timeline: [
          { time: "Day 1", event: "Vivek opens analytics filtered by location and sees one office’s print on-time rate lagging the others." },
          { time: "Day 1", event: "Volume by hour shows a spike of colour print jobs between 9 and 10 on Mondays." },
          { time: "Day 3", event: "The office adds a second print staffer to Monday mornings." },
          { time: "Day 30", event: "On-time delivery for print at that site is back in line with the group." },
        ],
        outcome: "A staffing change based on evidence, not on whoever complained loudest.",
      },
      {
        type: "stats",
        heading: "ZapBuzzer at Scale",
        items: [
          { value: "200+", label: "Offices Onboarded" },
          { value: "1.2M", label: "Requests Routed" },
          { value: "14", label: "Cities" },
          { value: "99.9%", label: "Uptime" },
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Taking Data Into Your Own Tools",
        body: "If you want ZapBuzzer numbers in your own reporting dashboard, Enterprise includes REST API and webhook access. The details are shared during onboarding.",
      },
      {"type":"metrics","heading":"Signals That a Site Needs Attention","intro":"Patterns a group operations lead learns to spot.","items":[{"metric":"Accept Time Drifting Up","meaning":"Staff may be stretched or notifications muted; check team size and channels before blaming people."},{"metric":"Escalations Clustered by Hour","meaning":"A shift gap, such as nobody covering IT over lunch."},{"metric":"Ratings Dipping While On-Time % Holds","meaning":"Jobs are fast but rushed; worth a conversation with the team lead."},{"metric":"Volume Falling at One Site","meaning":"People may be going back to phone calls; check whether requests are accepted quickly enough to trust."}]},
      {"type":"scenario","heading":"Spotting a Slow Site Early","persona":"Group Operations Lead","setting":"A group with five offices reviews its monthly numbers.","timeline":[{"time":"Week 1","event":"The newest office shows accept times well above the group’s other sites."},{"time":"Week 1","event":"The hourly view shows most slow accepts between 1pm and 3pm."},{"time":"Week 2","event":"The local admin confirms the pantry team takes lunch at the same time. Shifts are staggered."},{"time":"Week 4","event":"Afternoon accept times fall in line with the other offices; escalations at that site drop."}],"outcome":"A staffing fix, found from timestamps, made without a single site visit."},
    ],
    faqs: [
      {"q":"Can Each Location See Only Its Own Analytics?","a":"Yes, through role permissions. Location admins can be limited to their site while group roles see every office."},
      {"q":"How Do We Avoid Comparing a 20-person Office With a 400-person One Unfairly?","a":"Compare rates and times rather than totals: on-time %, median accept time and rating, not request counts. And compare each site with its own past months as well as with the others."},
      { q: "Are Analytics Included on Pro?", a: "Yes. Full analytics and scorecards are part of Pro. Enterprise builds on them with API and webhook access, white-label and a dedicated CSM." },
      { q: "Can We Compare Offices?", a: "Yes. Because every request is timed the same way, you can compare locations, teams and people on the same measures." },
      { q: "How Do Group-Wide Scorecards Stay Fair to Staff at Smaller Sites?", a: "Scorecards are designed to be people-first: they show fair credit, accept times and ratings for the work each person actually did, so good work is visible wherever it happens rather than ranked purely by volume." },
      { q: "Which Measures Can We Track Across All Our Sites?", a: "Every request is timed, so you can look at accept time, on-time delivery against SLA, ratings and when each office buzzes most. Pilot offices averaged a 32-second accept time and 96% on-time delivery in month one." },
      { q: "Can We Export Data to Our Own Reporting Tool?", a: "On Enterprise you can pull data through the REST API or receive webhooks. We share the specifics during onboarding rather than publishing them." },
      { q: "Who Sees Spend Data?", a: "Only owners. Cost visibility is owner-only by design." },
    ],
    related: ["enterprise", "enterprise/enterprise-reporting", "analytics", "analytics/team-performance", "analytics/staff-analytics", "developers/api-documentation", "pricing/enterprise-plan"],
    cta: { title: "See Group Analytics", body: "Try the read-only demo or book a walkthrough to see analytics across locations." },
  },
  {
    path: "enterprise/multi-location",
    title: "Multi-Location Office Request Management",
    description:
      "Run pantry, print, IT, facilities and courier requests across many offices and cities. How ZapBuzzer handles multiple locations for groups and facility firms.",
    h1: "Many Offices, Many Cities, One Way of Getting Things Done",
    eyebrow: "Enterprise · Multi-Location",
    lead:
      "Multi-location starts on Pro. For groups and facility companies running a dozen sites, Enterprise adds what makes a large group easier to run: SSO (sign-in with company accounts), your own branding, API access for connecting your systems, on-prem hosting on your own servers if you need it, and a dedicated CSM (customer success manager).",
    keywords: [
      "multi location office management",
      "multiple office request system",
      "facility company software multiple sites",
      "group office operations",
    ],
    heroVisual: "notification-flow",
    sections: [
      {
        type: "problem-solution",
        heading: "What Breaks When You Add the Second Office",
        problem: {
          title: "Without One System",
          points: [
            "Each office invents its own WhatsApp group and rules",
            "Head office has no idea how sites compare",
            "Staff moving between offices learn a new process each time",
            "A request at the wrong site goes to the wrong pantry",
          ],
        },
        solution: {
          title: "With ZapBuzzer",
          points: [
            "Every location uses the same tap-to-request flow",
            "Requests route to the team at the right site",
            "Analytics compare locations on equal terms",
            "Staff and admins can be scoped per location",
          ],
        },
      },
      {
        type: "workflow",
        heading: "How a Request Finds the Right Building",
        steps: [
          { title: "Employee Taps", body: "Tanvi in the Bengaluru office taps IT → HDMI cable → Conference Room B." },
          { title: "Location Decides the Team", body: "Her location means the request goes to the Bengaluru IT desk, not Pune’s." },
          { title: "Team Is Pinged", body: "Local IT staff are notified on app, Telegram, WhatsApp and email, repeating until someone accepts." },
          { title: "First Accept Owns It", body: "Priya at the Bengaluru IT desk accepts and brings the cable in 3 minutes." },
          { title: "Group Sees It", body: "The request counts toward Bengaluru’s numbers in group analytics." },
        ],
      },
      {
        type: "visual",
        visual: "notification-flow",
        heading: "Local Pings, Group Visibility",
        body: "One request fans out only to the people who can act on it at that site, while the record rolls up to the group dashboard.",
      },
      {
        type: "scenario",
        heading: "A Facility Company With Client Sites",
        persona: "Deepak, Admin Head at a Facility Services Firm",
        setting: "Runs pantry and mailroom for several client offices across two cities.",
        timeline: [
          { time: "08:45", event: "Pantry staff at each client site start their shift on the app." },
          { time: "11:00", event: "Peak coffee hour; Deepak’s dashboard shows open requests per site." },
          { time: "11:12", event: "One site’s request runs past its SLA and escalates to that site’s supervisor automatically." },
          { time: "18:00", event: "Deepak reviews on-time rates per client site for his weekly report." },
        ],
        outcome: "He can show each client their own numbers, and with white-label the app carries his brand.",
      },
      {
        type: "table",
        heading: "Multi-Location by Plan",
        headers: ["", "Free", "Pro", "Enterprise"],
        rows: [
          ["Locations", "1", "Multiple", "Multiple"],
          ["Staff", "Up to 10", "Unlimited", "Unlimited"],
          ["Notifications", "Email", "App, Telegram, WhatsApp, email", "App, Telegram, WhatsApp, email"],
          ["SSO + SAML", "—", "—", "Yes"],
          ["White-label + custom domain", "—", "—", "Yes"],
          ["Dedicated CSM", "—", "—", "Yes"],
        ],
      },
      {
        type: "checklist",
        heading: "Setting Up a New Location",
        items: [
          "Name the location and add rooms and destinations",
          "Create local teams: pantry, print, IT, facilities, courier",
          "Reuse the group catalogue, then add local items",
          "Assign a location admin",
          "Confirm SLA and escalation contacts for the site",
        ],
      },
      {
        type: "stats",
        items: [
          { value: "14", label: "Cities With ZapBuzzer Offices" },
          { value: "200+", label: "Offices Onboarded" },
        ],
      },
      {"type":"checklist","heading":"Signs You Have Outgrown One Location","items":["Requests from one building get answered by staff in another.","Your pantry team in one office keeps getting pinged for print jobs at another.","Group leaders ask for numbers per site and you can only give one total.","A new office is opening and you want it to start with the same standards.","You run facilities for several client sites and need to keep them apart."]},
      {"type":"callout","tone":"info","title":"Free Covers One Location","body":"The Free plan is built for trying ZapBuzzer on one floor: up to 10 staff and one location. Adding offices means moving to Pro, which includes multi-location at ₹99 per seat per month."},
      {"type":"prose","heading":"Keeping Sites Consistent Without Making Them Identical","paragraphs":["A Pune head office might have a full pantry, a print room and an IT desk; a small sales office in another city might only have a pantry and a receptionist who handles couriers. Forcing the same catalogue on both creates buttons nobody can answer.","The pattern that works is a shared core with local additions: the same request names and SLA ideas everywhere, so reports compare cleanly, plus items that exist only where a team can deliver them."]},
    ],
    faqs: [
      {"q":"Can an Employee Visiting Another Office Buzz There?","a":"Requests carry a destination, so a visitor can buzz for something where they are. How visiting users are set up across sites is worth agreeing with your admins so pings reach the right local team."},
      { q: "Do I Need Enterprise for More Than One Office?", a: "No. Multi-location is included on Pro at ₹99 per seat per month. Enterprise is for groups that also need SSO, white-label, API access, on-prem or a dedicated CSM." },
      { q: "Can a Person Belong to More Than One Location?", a: "Staff who move between sites can be set up to work where they are needed. Your admin decides how teams are organised per site." },
      { q: "Does Each Location Get Its Own SLA?", a: "You can tune SLA and escalation for your categories and teams, so a busy head office and a small branch need not share the same expectations." },
      { q: "Can a Facility Company Keep Client Sites Separate?", a: "Yes, sites can be organised separately with their own teams and reporting. Talk to us about the structure that suits your client contracts." },
      { q: "Is There a Limit on Locations?", a: "Pro supports multiple locations. For very large estates, Enterprise pricing is custom and shaped around your group." },
      { q: "Can Head Office See Requests From Every Location in One Place?", a: "Yes. Locations run in one account, so group owners keep one view while each site has its own catalogue, teams and analytics." },
      { q: "Can Different Offices Offer Different Catalogue Items?", a: "Yes. One site may have a print room and another only a pantry, so each location can have its own catalogue items routed to its own teams." },
    ],
    related: ["enterprise", "enterprise/enterprise-rollout", "enterprise/enterprise-analytics", "features/request-routing", "use-cases/better-facilities-operations", "pricing/pro-plan", "pricing/enterprise-plan"],
    cta: { title: "Bring Every Office Onto One System", body: "Tell us your sites and cities and we will suggest a setup." },
  },
  {
    path: "enterprise/enterprise-user-management",
    title: "Enterprise User Management and Onboarding",
    description:
      "Invite, organise and remove users across a group with ZapBuzzer Enterprise: teams, roles, locations, SSO sign-in and clean offboarding when people leave.",
    h1: "Joiners, Movers and Leavers, Handled Without a Spreadsheet",
    eyebrow: "Enterprise · Users",
    lead:
      "In a group of offices, people join every week, move floors, switch teams and leave. User management in ZapBuzzer keeps the right people on the right teams, and with SSO (single sign-on) on Enterprise, people sign in with their company accounts, so access follows your company directory.",
    keywords: [
      "enterprise user management",
      "office app user provisioning",
      "sso user onboarding office",
      "staff offboarding access",
    ],
    heroVisual: "staff-queue",
    sections: [
      {
        type: "prose",
        heading: "Two Kinds of Users",
        paragraphs: [
          "Most of your users are requesters: employees who tap Coffee or Print and get on with their day. A smaller group are staff: pantry, print room, IT, facilities and mailroom people who accept and deliver. Getting the second group right matters most, because a missing pantry staffer means unanswered buzzes.",
          "On Free, a workspace holds up to 10 staff. Pro and Enterprise remove the limit and price per seat.",
        ],
      },
      {
        type: "workflow",
        heading: "The User Lifecycle",
        steps: [
          { title: "Join", body: "Invite by email, or on Enterprise let people sign in through SSO with their company account." },
          { title: "Place", body: "Assign a location, a team and a role: requester, staff, manager or owner." },
          { title: "Work", body: "Staff accept from the app; their accept times and ratings build up on their scorecard." },
          { title: "Move", body: "When someone changes office or team, update their location or team and requests route accordingly." },
          { title: "Leave", body: "Remove the user. With SSO, closing the company account ends access too. History stays for reporting." },
        ],
      },
      {
        type: "visual",
        visual: "staff-queue",
        heading: "Staff on the Right Team See the Right Queue",
        body: "A pantry staffer sees pantry requests with Accept buttons; they never see IT tickets. Placement is what makes first-accept-wins work.",
      },
      {
        type: "scenario",
        heading: "Monday Joiners at a Growing Office",
        persona: "Priya, Office Manager",
        setting: "Eight new hires and one new pantry staffer start on the same Monday.",
        timeline: [
          { time: "09:15", event: "New hires sign in with their company accounts through SSO and land as requesters." },
          { time: "09:20", event: "Priya places Ramesh, the new pantry staffer, on the 3rd-floor pantry team." },
          { time: "10:05", event: "Ramesh accepts his first chai order from the app and delivers it to Conference Room B." },
        ],
        outcome: "Nobody waited for a password, and the pantry had an extra pair of hands by mid-morning.",
      },
      {
        type: "features",
        heading: "What Helps at Scale",
        items: [
          { title: "SSO Sign-In", body: "Enterprise only. People use the login they already have." },
          { title: "Teams per Location", body: "Keep the Pune pantry and the Mumbai pantry separate." },
          { title: "Roles", body: "Permissions per role, so promoting someone to manager is one change." },
          { title: "Audit Trail", body: "Who added, moved or removed a user is logged." },
        ],
      },
      {
        type: "checklist",
        heading: "Offboarding Checklist",
        items: [
          "Remove or disable the user in ZapBuzzer, or close their SSO account",
          "Check they are not the only member of a team",
          "Update escalation chains if they were a manager",
          "Keep history for reporting; it stays attached to past requests",
        ],
      },
      {
        type: "callout",
        tone: "warning",
        title: "Do Not Leave a Team Empty",
        body: "If the only print room staffer leaves, print requests have nobody to ring. Add a replacement or a backup before removing them.",
      },
      {"type":"comparison","heading":"Managing Users by Hand Versus With SSO","intro":"SSO and SAML are Enterprise options. Here is the practical difference for an admin team.","columns":["Separate ZapBuzzer Accounts","Sign-In Through Your Company Accounts"],"rows":[{"label":"Joiners","a":"Invited one by one","b":"Sign in with the account IT already gave them"},{"label":"Leavers","a":"Someone must remember to remove them","b":"Access follows your company account being closed"},{"label":"Passwords","a":"One more to remember","b":"The one they already use"},{"label":"Setup Effort","a":"None","b":"Done with your IT team and ours; talk to us for details"}]},
      {"type":"scenario","heading":"A Team Moves Floors","persona":"Location Admin","setting":"The design team moves from the 2nd floor to the 4th, which has its own pantry.","timeline":[{"time":"Friday","event":"The admin updates where the team’s pantry requests route, to the 4th-floor pantry."},{"time":"Friday","event":"Pantry staff on the 4th floor are told to expect more requests from Monday."},{"time":"Monday 10:05","event":"Tanvi buzzes for coffee; it reaches the 4th-floor pantry, not the old one."},{"time":"Monday 10:06","event":"Accepted in under a minute. Nobody on the 2nd floor gets a stray ping."}],"outcome":"Users kept their accounts and history; only where their requests go changed."},
    ],
    faqs: [
      {"q":"Can We Invite People in Bulk?","a":"Inviting your team is part of signing up, and Enterprise groups often manage access through SSO. For a large onboarding, your CSM will help plan the order and the approach."},
      {"q":"What Should Happen When a Staff Member Changes Team?","a":"Move them to the new team so they get that team’s pings and queue. Their past jobs and ratings stay with them, so their scorecard history is intact."},
      { q: "Do Employees Who Only Request Things Count as Seats?", a: "Pricing is per seat. For how seats are counted in your group, check the pricing page or ask us; Enterprise pricing is custom." },
      { q: "Can Users Sign in With Our Company Accounts?", a: "Yes, on Enterprise through SSO and SAML. The setup is done with your IT team during onboarding." },
      { q: "What Happens to a Leaver’s Past Requests?", a: "They stay in history so reports and audit logs remain accurate. The person simply loses access." },
      { q: "Can Someone Be Both a Requester and Staff?", a: "Yes. A staffer can buzz for things too. Their role decides what extra they can do." },
      { q: "How Do We Remove Access When Someone Leaves?", a: "Remove or disable the user. Accounts live on the server, so access stops even if they still have the app on their phone, and with SSO on Enterprise access follows your company identity system." },
      { q: "Can We Add Staff to the Right Team as They Join?", a: "Yes. Admins invite people and place them in teams per location, so new staff start receiving the requests routed to their team straight away." },
    ],
    related: ["enterprise", "enterprise/enterprise-permissions", "integrations/sso-and-saml", "administration/team-management", "administration/staff-assignment", "use-cases/hr-team", "pricing/enterprise-plan"],
    cta: { title: "Make Onboarding Painless", body: "Talk to us about SSO and user management for your group." },
  },
  {
    path: "enterprise/enterprise-permissions",
    title: "Enterprise Permissions and Role Controls",
    description:
      "Decide exactly who can buzz, accept, escalate, configure and see spend in ZapBuzzer. Detailed per-role permissions for groups and facility companies.",
    h1: "Everyone Gets the Buttons They Need, and No More",
    eyebrow: "Enterprise · Permissions",
    lead:
      "Clear permissions for each role keep a large workspace calm. Employees see a simple request grid, staff see their queue, managers see escalations, and only owners see what it all costs.",
    keywords: [
      "role based permissions office app",
      "enterprise permission matrix",
      "owner only spend visibility",
      "office request access control",
    ],
    heroVisual: "roles",
    sections: [
      {
        type: "visual",
        visual: "roles",
        heading: "The Permissions Matrix",
        body: "Roles map to actions. Changing what a role can do changes it for everyone in that role, which keeps a group of hundreds of users consistent.",
      },
      {
        type: "table",
        heading: "A Typical Setup",
        intro: "Your roles can differ; this is a common starting point.",
        headers: ["Action", "Employee", "Staff", "Manager", "Owner"],
        rows: [
          ["Buzz a request", "Yes", "Yes", "Yes", "Yes"],
          ["Accept and deliver", "—", "Yes", "Yes", "Yes"],
          ["Receive escalations", "—", "—", "Yes", "Yes"],
          ["Team reports and scorecards", "—", "Own", "Team", "All"],
          ["Edit catalogue and routing", "—", "—", "Optional", "Yes"],
          ["See request costs", "—", "—", "—", "Yes"],
        ],
      },
      {
        type: "prose",
        heading: "Why Fewer Permissions Makes the App Better",
        paragraphs: [
          "Permissions are usually talked about as security, and they are. But in an office request tool they also shape the experience. An employee who only sees Coffee, Print and IT taps faster. A pantry staffer who only sees pantry requests never accepts something they cannot deliver.",
          "Owner-only spend is a good example. When Vivek orders lunch for 12, the pantry needs to know what and where. They do not need the bill. The owner does.",
        ],
      },
      {
        type: "scenario",
        heading: "Promoting a Team Lead",
        persona: "Deepak, Admin Head",
        setting: "Raj from the pantry team becomes pantry supervisor.",
        timeline: [
          { time: "14:00", event: "Deepak changes Raj’s role from staff to manager for the pantry team." },
          { time: "14:01", event: "Raj now sees team scorecards and is added to the pantry escalation chain." },
          { time: "16:30", event: "A late snack order escalates; Raj gets it and reassigns it to a free colleague." },
        ],
        outcome: "One change, logged in the audit trail, and Raj has exactly the extra access his new job needs.",
      },
      {
        type: "features",
        heading: "Permission Principles We Recommend",
        items: [
          { title: "Default to Requester", body: "Everyone starts with the smallest role." },
          { title: "Scope by Location", body: "A location admin manages one site, not the group." },
          { title: "Keep Owners Few", body: "Owner rights include spend and settings." },
          { title: "Log Every Change", body: "Role changes appear in the audit log." },
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Plan Note",
        body: "Roles and audit logs are part of Pro. Enterprise adds SSO and SAML, so people sign in with their company accounts and their roles sit on top. It also adds a dedicated CSM (customer success manager) to help design your roles.",
      },
      {
        type: "checklist",
        heading: "Quarterly Permission Review",
        items: [
          "List everyone with owner rights and confirm each one",
          "Check managers are on the right escalation chains",
          "Remove staff roles from people who changed jobs",
          "Read recent role changes in the audit log",
        ],
      },
      {"type":"comparison","heading":"Shared Logins Versus Roles","intro":"Many offices start with one admin password passed around. Here is what changes when access follows roles.","columns":["One Shared Admin Login","Roles in ZapBuzzer"],"rows":[{"label":"Who Changed the Catalogue","a":"Anyone who knew the password; nobody can say who","b":"A named person, recorded in the audit log"},{"label":"When Someone Leaves","a":"Change the password and tell everyone again","b":"Remove that one user; everyone else carries on"},{"label":"Spend Data","a":"Visible to whoever is logged in","b":"Owner-only by design"},{"label":"New Site Admin","a":"Gets access to every office","b":"Can be scoped to their own location"},{"label":"Audit Questions","a":"Answered from memory","b":"Answered from the log"}]},
      {"type":"audience","heading":"What Each Role Typically Needs","items":[{"role":"Employee","benefit":"Buzz requests, track who is on them, rate the result. Nothing more is needed to get coffee to Conference Room B."},{"role":"Staff Member","benefit":"See their team’s queue, accept, start, deliver with a photo. No access to settings they would never use."},{"role":"Team Lead","benefit":"Their team’s scorecards and the ability to reassign, so they can run the pantry or IT desk without touching other teams."},{"role":"Location Admin","benefit":"Catalogue, teams and SLAs for one site, without seeing a sister office."},{"role":"Owner","benefit":"Everything, including request cost, which no other role sees."}]},
      {"type":"callout","tone":"tip","title":"Start Narrow, Widen on Request","body":"It is easier to grant a permission when someone asks for it than to take one back after people are used to it. Give new admins the smallest role that lets them do the job, and review after a month."},
    ],
    faqs: [
      {"q":"What Happens If We Give Someone the Wrong Role?","a":"Change it. The change applies to what they do next, and the change itself is recorded in the audit log. Their past actions stay recorded under their name."},
      {"q":"Do Permissions Affect Who Gets Notified?","a":"Notifications go to the team a request routes to, so team membership decides who is pinged. Roles decide what people can see and change once they open the app."},
      { q: "Can We Create Custom Roles?", a: "Each role has its own permissions. Exactly how you shape roles for a large group is something we work through with you on Enterprise." },
      { q: "Who Can See Costs?", a: "Cost visibility is owner-only. Staff and managers see the work, not the spend." },
      { q: "Are Permission Changes Logged?", a: "Yes. Every action is audit-logged, including changes to who can do what." },
      { q: "Can Location Admins See Other Offices?", a: "Admins can be scoped to their own location so they manage their site without seeing every other office." },
      { q: "Can a Requester See Requests Raised by Other People?", a: "That depends on the permissions you give their role. Many offices let reception view open requests while ordinary requesters only see their own." },
      { q: "Who Should Be Allowed to Change Escalation Settings?", a: "Keep it to owners and a few admins. Each role has its own permissions, and every change is audit-logged, so you can check later who adjusted an SLA or escalation chain." },
    ],
    related: ["enterprise", "enterprise/security", "enterprise/enterprise-user-management", "administration/roles-and-permissions", "administration/spend-visibility", "enterprise/enterprise-audit-logs", "pricing/enterprise-plan"],
    cta: { title: "Design Your Roles With Us", body: "A CSM can help you map your org chart to ZapBuzzer roles." },
  },
  {
    path: "enterprise/enterprise-audit-logs",
    title: "Enterprise Audit Logs for Every Office Request",
    description:
      "Every buzz, accept, escalation and setting change in ZapBuzzer is audit-logged. How groups use the log for disputes, reviews and courier accountability.",
    h1: "A Record of Who Did What, When, for Every Request",
    eyebrow: "Enterprise · Audit Logs",
    lead:
      "When the client asks why the parcel was not picked up, or a manager asks who changed the SLA, the answer should not depend on someone’s memory. ZapBuzzer audit-logs every action.",
    keywords: [
      "audit log office requests",
      "courier audit trail",
      "enterprise activity log",
      "facility request accountability",
    ],
    heroVisual: "audit-log",
    sections: [
      {
        type: "visual",
        visual: "audit-log",
        heading: "What a Log Row Tells You",
        body: "Each row records an action, who took it and when. Read together, rows tell the full story of a request or a configuration change.",
        points: ["Request buzzed, accepted, started, delivered, rated", "Escalations and who received them", "Changes to users, roles and settings"],
      },
      {
        type: "prose",
        heading: "Why Audit Logs Matter More in a Group",
        paragraphs: [
          "In a small office, everyone remembers who did what. Across several offices, with staff from facility contractors and dozens of admins, memory fails. The audit log is the shared, neutral record that settles questions without blame games.",
          "It also protects staff. When a requester says nobody came, the log shows that Raj accepted in 40 seconds and marked it delivered with a photo eight minutes later.",
        ],
      },
      {
        type: "scenario",
        heading: "The Missing Courier",
        persona: "Neha, Reception",
        setting: "A client says a document courier was never collected yesterday.",
        timeline: [
          { time: "10:00", event: "Neha opens yesterday’s courier pickup requests in the log." },
          { time: "10:02", event: "She sees the pickup was buzzed at 15:10, logged by the mailroom at 15:22 and marked delivered at 15:40." },
          { time: "10:05", event: "She shares the times with the client, who finds the parcel in their own mailroom." },
        ],
        outcome: "A five-minute check instead of an afternoon of phone calls.",
      },
      {
        type: "audience",
        heading: "Who Uses the Log",
        items: [
          { role: "Admin Heads", benefit: "Investigate disputes and late deliveries with facts." },
          { role: "Owners", benefit: "See who changed settings, roles and spend-related items." },
          { role: "Reception and Mailroom", benefit: "Prove courier pickups and handovers." },
          { role: "Facility Companies", benefit: "Show clients a clear service record." },
        ],
      },
      {
        type: "checklist",
        heading: "Good Habits",
        items: [
          "Check the log before escalating a complaint",
          "Review setting changes after any rollout",
          "Encourage staff to attach a delivery photo for important items",
          "Use reports for trends and the log for individual cases",
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Which Plan?",
        body: "Audit logs and reports are part of Pro. Enterprise adds API and webhook access, so activity can flow automatically into your own systems, plus SSO, white-label and a dedicated CSM.",
      },
      {
        type: "comparison",
        heading: "Chat History Versus an Audit Log",
        columns: ["WhatsApp Group", "ZapBuzzer Audit Log"],
        rows: [
          { label: "Who Agreed to Do It", a: "Whoever said “ok” first, maybe", b: "The person who tapped Accept" },
          { label: "When It Was Done", a: "Not recorded", b: "Timestamped delivery" },
          { label: "Setting Changes", a: "Not applicable", b: "Logged with who and when" },
          { label: "After Someone Leaves", a: "Messages may vanish", b: "History stays with the workspace" },
        ],
      },
      {"type":"workflow","heading":"Answering a Question From the Log","intro":"A typical way an admin head uses the log when something is disputed.","steps":[{"title":"Start With the Request","body":"Find the request in question, such as a projector fix in Conference Room B that a client says never happened."},{"title":"Read the Timeline","body":"See when it was buzzed, who accepted it, when it was started with an ETA and when it was marked delivered, with any photo attached."},{"title":"Check for Changes Around It","body":"Look for reassignments or escalations on that request, and whether anyone changed routing or SLA settings that week."},{"title":"Share the Facts","body":"Reply with what the record shows, not what people remember. Most disputes end here."}]},
      {"type":"table","heading":"Questions and Where the Answer Sits","headers":["Question","What the Log Shows"],"rows":[["Was the courier picked up?","The pickup request, who logged it and when"],["Why did facilities stop getting AC tickets?","The routing change, who made it and when"],["Who gave this person admin rights?","The role change and the user who made it"],["Did the escalation actually reach the manager?","The escalation event on that request"],["Who accepted the lunch order for 12?","The accept action, with the staff member’s name"]]},
      {"type":"callout","tone":"info","title":"A Log Is Only Useful If People Know It Exists","body":"Tell staff that actions are recorded. In practice this protects them: when a delivery is disputed, the person who did the work has a timestamp and often a photo on their side."},
    ],
    faqs: [
      {"q":"Does the Audit Log Slow Anything Down for Staff?","a":"No. Logging happens in the background as people tap Accept, Start and Delivered. Nobody fills in an extra form."},
      {"q":"Who Should Have Access to the Audit Log?","a":"Usually owners and admins, with location admins limited to their site. Access is set by role permissions, so you can keep it as narrow as your group needs."},
      { q: "What Actions Are Logged?", a: "Every action is audit-logged, from requests moving through their states to changes in users, roles and settings." },
      { q: "Can Staff Edit the Log?", a: "The audit log is a record of actions, not an editable document. That is what makes it useful in disputes." },
      { q: "Can We Set a Custom Audit Log Retention Period for Compliance?", a: "Free keeps the last 30 days of history, and Pro adds audit logs and reports. For specific retention requirements on Enterprise, talk to us and we will go through what is possible." },
      { q: "Can the Audit Log Settle a Dispute About a Missed Request?", a: "Yes. It shows who was notified, who accepted, when work started and when it was delivered, each with a name and timestamp, so the facts replace ‘I thought you’d do it’." },
      { q: "Which Plan Includes Audit Logs?", a: "Audit logs and reports are part of Pro at ₹99 per seat per month. Enterprise builds on them with API and webhook access for bringing data into your own tools." },
      { q: "Can We Export Audit Data?", a: "Reports are available on Pro, and on Enterprise you can bring data into your own tools via the REST API and webhooks. Specifics are shared during onboarding." },
    ],
    related: ["enterprise", "administration/audit-logs", "enterprise/security", "solutions/courier-and-reception/courier-tracking", "use-cases/staff-accountability", "enterprise/enterprise-reporting", "pricing/enterprise-plan"],
    cta: { title: "Settle Questions With Facts", body: "See the audit log in the read-only demo or book a walkthrough." },
  },
  {
    path: "enterprise/enterprise-reporting",
    title: "Enterprise Reporting for Office Services",
    description:
      "Monthly service reports for leadership and clients: volume, on-time rates, escalations, ratings and owner-only cost, built from ZapBuzzer request data.",
    h1: "Reports Leadership Reads and Clients Trust",
    eyebrow: "Enterprise · Reporting",
    lead:
      "Analytics is for running the office day to day. Reporting is for the monthly conversation: how did the pantry, print room and facilities team do, what did it cost, and what should change.",
    keywords: [
      "office services reporting",
      "facility management client report",
      "sla compliance report office",
      "monthly operations report",
    ],
    heroVisual: "analytics",
    sections: [
      {
        type: "prose",
        heading: "From Timestamps to a Story",
        paragraphs: [
          "Because every request is timed and every action logged, ZapBuzzer reporting is built on real events, not survey answers. A monthly report can show how many coffee, print, IT, facilities and courier requests each office handled, how many were on time, how many escalated, and how requesters rated the service.",
          "For facility companies, the same data becomes a client-facing service report. With white-label on Enterprise, it can carry your brand rather than ours.",
        ],
      },
      {
        type: "features",
        heading: "What a Good Monthly Report Covers",
        items: [
          { title: "Volume", body: "Requests per category, per location, per week." },
          { title: "Timeliness", body: "Average accept time and on-time delivery rate." },
          { title: "Escalations", body: "How many went overdue and where." },
          { title: "Quality", body: "Average ratings per team." },
          { title: "People", body: "Scorecards that credit top performers." },
          { title: "Cost", body: "Owner-only spend, for example on team lunches." },
        ],
      },
      {
        type: "visual",
        visual: "scorecard",
        heading: "Recognition Belongs in the Report",
        body: "Staff scorecards make good work visible. Calling out the print room staffer with the best on-time record is as useful as flagging the slowest queue.",
      },
      {
        type: "scenario",
        heading: "Preparing a Client Review",
        persona: "Deepak, Admin Head at a Facility Services Firm",
        setting: "Monthly review with a client whose office his team services.",
        timeline: [
          { time: "Day 28", event: "Deepak pulls the month’s requests for the client’s location." },
          { time: "Day 28", event: "He notes on-time delivery, escalations and the average rating." },
          { time: "Day 29", event: "He adds two improvements: an extra pantry shift at 4 pm and faster AC response." },
          { time: "Day 30", event: "The client sees facts, not anecdotes, and renews the contract." },
        ],
        outcome: "Reporting turns service quality into something both sides can agree on.",
      },
      {
        type: "metrics",
        heading: "Headline Numbers to Track Month Over Month",
        items: [
          { metric: "On-Time Delivery %", meaning: "The single best summary of service quality." },
          { metric: "Average Accept Time", meaning: "How quickly someone takes ownership." },
          { metric: "Escalation Count", meaning: "Where processes or staffing need attention." },
          { metric: "Average Rating", meaning: "How requesters feel about the service." },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Feeding Your Own Reporting Tools",
        body: "If your group already has a reporting tool, the REST API and webhooks on Enterprise let you send request data into it automatically. We share the technical details during onboarding.",
      },
      {
        type: "stats",
        heading: "For Reference: Our Pilot Offices, Month One",
        items: [
          { value: "32s", label: "Average Accept Time" },
          { value: "96%", label: "On-Time Delivery" },
          { value: "4.8★", label: "Average Rating" },
        ],
      },
      {"type":"audience","heading":"Who Reads Which Report","items":[{"role":"Group COO","benefit":"A one-page view of on-time %, accept time and escalations per location, enough to decide where attention goes next month."},{"role":"Location Admin","benefit":"Their own site’s numbers by team and hour, used to adjust rosters and SLA targets rather than to defend them."},{"role":"Facility Company Account Manager","benefit":"Client-ready figures for each site they run, so the quarterly review starts from shared facts instead of anecdotes."},{"role":"Owner or Finance","benefit":"Request cost alongside volume, visible only to owners, for questions like what lunch orders for the sales floor actually cost."}]},
      {"type":"checklist","heading":"Before a Report Leaves the Building","intro":"A short pass that stops a report from starting the wrong conversation.","items":["Check the period matches the one you compared against last time, including any public holidays.","Note anything unusual: an office move, a new print room, a team short-staffed for a week.","Read escalations alongside volume; ten escalations on 2,000 requests is a different story from ten on 200.","Name the staff who earned the best ratings, not only the problems.","Strip owner-only cost data if the report is going to team leads or clients.","End with one or two changes you will try, so next month’s report has something to test."]},
      {"type":"prose","heading":"Reports That Change Something","paragraphs":["The test of a report is whether anyone does anything differently after reading it. A table of thirty numbers rarely passes that test. A short note that says ‘IT accept time slips after 2pm because the desk takes lunch in shifts that overlap badly’ usually does.","Because every request in ZapBuzzer moves through the same states with timestamps, the same report format works for every location and every month. That consistency is what lets a group spot a site drifting before its staff or its clients notice."]},
    ],
    faqs: [
      {"q":"How Often Should We Produce a Group Report?","a":"Monthly suits most groups, with a short weekly glance at escalations for the first few weeks after a site goes live. Quarterly works well for client reviews at facility companies. The data is the same; only the period changes."},
      {"q":"Can Location Admins Build Their Own Reports?","a":"Admins work with the data their role allows, which is usually their own location. Group-wide views stay with group roles. Permissions are set per role, so you decide how wide each person’s view is."},
      { q: "Are Reports Included on Pro?", a: "Yes, audit logs and reports are part of Pro. Enterprise adds API and webhook access, white-label and a dedicated CSM." },
      { q: "Can We Brand Reports for Our Clients?", a: "Enterprise includes white-label and a custom domain, so what your clients see can carry your brand. Talk to us about how far branding goes for your use case." },
      { q: "Can We Combine ZapBuzzer Data With Other Systems?", a: "On Enterprise you can use the REST API and webhooks to bring request data into your own tools. Details come with onboarding." },
      { q: "Do Reports Include Costs?", a: "Cost data is owner-only. Owners can include it in their own reporting; staff never see it." },
      { q: "Can Reports Show Which Site Misses Its SLAs Most Often?", a: "Yes. Every request is timed against its deadline, so reports can show on-time delivery and escalations by location, team and request type." },
      { q: "Can Reports Show Our Busiest Hours?", a: "Yes. Analytics show when the office buzzes most, which helps plan pantry, print and facilities staffing around real peaks." },
    ],
    related: ["enterprise", "enterprise/enterprise-analytics", "sla-and-escalation/sla-reporting", "features/request-reports", "developers/api-documentation", "integrations/white-label", "pricing/enterprise-plan"],
    cta: { title: "Get Reports That End Arguments", body: "Book a walkthrough and see the data behind a monthly service report." },
  },
  {
    path: "enterprise/enterprise-support",
    title: "Enterprise Support and Dedicated CSM",
    description:
      "What support looks like on ZapBuzzer Enterprise: a dedicated customer success manager, rollout help, reviews of your analytics, and a direct line to our team.",
    h1: "A Named Person Who Knows Your Offices",
    eyebrow: "Enterprise · Support",
    lead:
      "Enterprise customers get a dedicated customer success manager. Not a ticket number: someone who knows your sites, your catalogues and your rollout, and helps you get more out of ZapBuzzer each month.",
    keywords: [
      "enterprise customer success manager",
      "office software support",
      "zapbuzzer enterprise support",
      "dedicated csm facility software",
    ],
    heroVisual: "delivery",
    sections: [
      {
        type: "prose",
        heading: "What a Dedicated CSM Does",
        paragraphs: [
          "Your CSM is part rollout planner, part operations adviser and part point of contact for everything Enterprise. They help pick your pilot office, review catalogues, set sensible SLAs, and plan the sequence for the rest of the group.",
          "Once you are live, they look at your analytics with you: where accept times are slipping, which site escalates most, which team deserves credit. When you need SSO (company sign-in), white-label (your own branding), API access or an on-prem setup on your own servers, they bring in the right people.",
        ],
      },
      {
        type: "features",
        heading: "What Is Included",
        items: [
          { title: "Rollout Planning", body: "Pilot selection, sequencing and readiness checks for each site." },
          { title: "Configuration Reviews", body: "Catalogues, teams, routing, SLAs and escalation chains." },
          { title: "Regular Check-Ins", body: "Walk through analytics and agree improvements." },
          { title: "Enterprise Options", body: "Coordination for SSO and SAML, white-label, custom domain, API and webhooks, and on-prem." },
          { title: "Direct Contact", body: "A named person, backed by the team at hello@zapbuzzer.com." },
        ],
      },
      {
        type: "comparison",
        heading: "Support by Plan",
        columns: ["Free and Pro", "Enterprise"],
        rows: [
          { label: "Contact", a: "hello@zapbuzzer.com, replies within one business day", b: "Dedicated CSM plus the same team" },
          { label: "Onboarding", a: "Self-serve, live in an afternoon", b: "Guided rollout across sites" },
          { label: "Reviews", a: "On request", b: "Regular analytics check-ins" },
          { label: "Enterprise Options", a: "—", b: "SSO, white-label, API, on-prem scoped with you" },
        ],
      },
      {
        type: "visual",
        visual: "delivery",
        heading: "Support, the ZapBuzzer Way",
        body: "We built a product about requests getting accepted, delivered and rated. We try to run support the same way: someone owns your question, tells you who is on it, and closes the loop.",
      },
      {
        type: "scenario",
        heading: "A New Site Wobbles",
        persona: "Priya, Office Manager",
        setting: "The group’s third office went live two weeks ago and on-time delivery is lower than expected.",
        timeline: [
          { time: "Tue", event: "Priya emails her CSM with the concern." },
          { time: "Wed", event: "The CSM reviews analytics with her: most late requests are print jobs between 9 and 10." },
          { time: "Wed", event: "They agree a second print staffer for that hour and a clearer SLA for large colour jobs." },
          { time: "+2 weeks", event: "On-time delivery for that site recovers." },
        ],
        outcome: "A specific fix in days, instead of a vague sense that the new site is not working.",
      },
      {
        type: "checklist",
        heading: "To Get the Most From Your CSM",
        items: [
          "Share your list of sites and priorities early",
          "Name one internal owner for ZapBuzzer",
          "Book a monthly analytics review",
          "Raise Enterprise options (SSO, API, on-prem) at the start, not later",
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Not on Enterprise?",
        body: "Everyone can reach us at hello@zapbuzzer.com. We are based in Pune and reply within one business day.",
      },
      {"type":"workflow","heading":"The First Ninety Days With a CSM","intro":"A common shape for an Enterprise engagement. Your CSM adjusts it to your offices.","steps":[{"title":"Kick-Off","body":"Agree the sites, the order they go live, who owns each location and which Enterprise options matter, such as SSO or white-label."},{"title":"Pilot Site","body":"One office goes live first. The CSM reviews its catalogue, teams and SLAs with the local admin after the first week."},{"title":"Rollout Waves","body":"Further sites follow in groups, each copying what worked at the pilot and adjusting for local teams."},{"title":"First Review","body":"Around the end of the quarter, look at accept time, on-time % and escalations per site and decide what to change next."}]},
      {"type":"checklist","heading":"What to Send When You Raise an Issue","intro":"Small details save a round of emails.","items":["Which location and team are affected.","An example request, with roughly when it was buzzed.","What you expected to happen and what happened instead.","Whether it affects everyone or one person or device.","Any recent change to routing, roles or SLAs."]},
      {"type":"prose","heading":"Where Support Usually Helps Most","paragraphs":["Most questions from large customers are not about the app misbehaving. They are about setup decisions: should IT and facilities be one team or two at a smaller site, how short can the pantry SLA be before it escalates every morning, who should sit at step two of the chain.","That is where a CSM who has seen many offices is useful. They can tell you what similar sites chose and what happened, so you skip a few weeks of trial and error."]},
    ],
    faqs: [
      {"q":"Can We Change Our CSM?","a":"If the fit is not right, tell us at hello@zapbuzzer.com and we will discuss it. The aim is a person who knows your offices well."},
      {"q":"Do Free and Pro Users Get Help Too?","a":"Yes. Write to hello@zapbuzzer.com and we reply within one business day. The difference on Enterprise is a named person who knows your setup."},
      { q: "Is a Dedicated CSM Only on Enterprise?", a: "Yes. A dedicated CSM is part of the Enterprise plan. Free and Pro customers get help from our team by email." },
      { q: "Do You Offer an Uptime Commitment?", a: "ZapBuzzer runs at 99.9% uptime. For contractual terms on Enterprise, talk to us about your requirements." },
      { q: "Will the CSM Help With SSO and API Setup?", a: "Yes. They coordinate the Enterprise options, bringing in our technical team and working with your IT team." },
      { q: "How Do We Start?", a: "Email hello@zapbuzzer.com or use the contact page with a short note about your offices. We will set up a call and introduce your CSM once you move ahead." },
      { q: "How Quickly Does the ZapBuzzer Team Reply to Support Emails?", a: "We reply within one business day at hello@zapbuzzer.com. Enterprise customers also have a dedicated CSM as their named point of contact." },
      { q: "Does the CSM Stay Involved After Rollout?", a: "Yes. The CSM supports each site as it goes live and remains your point of contact afterwards, including reviewing analytics across sites with you." },
    ],
    related: ["enterprise", "enterprise/enterprise-rollout", "pricing/enterprise-plan", "contact-us", "book-a-demo", "resource-hub/faq"],
    cta: { title: "Meet Your CSM", body: "Tell us about your group and we will introduce the person who will help you roll out." },
  },
];
