// AUTO-GENERATED by scripts/gen-pages-index.mjs — do not edit.
import type { PageContent } from "../types";
import { pages as p_admin } from "./admin";
import { pages as p_analytics } from "./analytics";
import { pages as p_compare } from "./compare";
import { pages as p_core } from "./core";
import { pages as p_courier } from "./courier";
import { pages as p_enterprise } from "./enterprise";
import { pages as p_facilities } from "./facilities";
import { pages as p_features } from "./features";
import { pages as p_features2 } from "./features2";
import { pages as p_guides } from "./guides";
import { pages as p_integrations } from "./integrations";
import { pages as p_it } from "./it";
import { pages as p_mobile } from "./mobile";
import { pages as p_notifications } from "./notifications";
import { pages as p_pantry } from "./pantry";
import { pages as p_print } from "./print";
import { pages as p_problems } from "./problems";
import { pages as p_resources } from "./resources";
import { pages as p_roles } from "./roles";
import { pages as p_sla } from "./sla";
import { pages as p_workflows } from "./workflows";

export const allPages: PageContent[] = [p_admin, p_analytics, p_compare, p_core, p_courier, p_enterprise, p_facilities, p_features, p_features2, p_guides, p_integrations, p_it, p_mobile, p_notifications, p_pantry, p_print, p_problems, p_resources, p_roles, p_sla, p_workflows].flat();
