import type { PageContent } from "../types";

export const pages: PageContent[] = [
  {
    path: "resource-hub",
    title: "Resources: Pricing, Guides and Comparisons",
    description:
      "Everything you need to evaluate ZapBuzzer: plans, billing, a product tour, FAQs, comparisons, customer stories, practical operations guides and a glossary.",
    h1: "Resources for Running a Quieter Office",
    eyebrow: "Resources",
    lead:
      "You might be pricing a rollout, convincing a founder or just trying to stop the pantry WhatsApp group from exploding. Either way, start here: plans, comparisons, guides and plain answers, all in one place.",
    keywords: ["zapbuzzer resources", "office operations guides", "internal request management resources", "zapbuzzer pricing", "office efficiency guide"],
    heroVisual: "request-dashboard",
    sections: [
      {
        type: "prose",
        heading: "Start With the Question You Actually Have",
        paragraphs: [
          "People arrive here for different reasons. An office manager wants to know if the Free plan covers one floor. A CEO wants proof that requests will actually get faster. An admin head wants to know how SLA escalation works before trusting it with facilities complaints. We have organised this section around those questions rather than around our product menu.",
          "Everything here sticks to what ZapBuzzer does today. Where something depends on your plan, we say so. Where something is only on Enterprise, we describe what it is for and tell you to talk to us rather than guessing at details.",
        ],
      },
      {
        type: "features",
        heading: "Plans and Billing",
        items: [
          { title: "Free Plan", body: "Free forever for one floor: up to 10 staff, one location, web and mobile app, email notifications, 30 days of history." },
          { title: "Pro Plan", body: "₹99 per seat per month. Unlimited staff, multiple locations, Telegram and WhatsApp pings, SLA with escalation chain, full analytics, audit logs and reports." },
          { title: "Enterprise Plan", body: "Custom pricing for groups and facility companies: SSO and SAML (sign in with your company login), white-label and custom domain (your brand and web address), REST API and webhooks (connect your own systems), a dedicated CSM and an on-prem option." },
          { title: "Billing and Seats", body: "How per-seat billing works, cancelling, currencies and the 14-day free trial." },
        ],
      },
      {
        type: "features",
        heading: "Understand the Product",
        items: [
          { title: "Product Tour", body: "Walk through one request from tap to rating, screen by screen." },
          { title: "Product FAQ", body: "Short answers to the questions we hear most often in demos." },
          { title: "Comparisons", body: "ZapBuzzer against manual requests, WhatsApp groups, phone calls and traditional helpdesks." },
          { title: "Customer Stories", body: "What pilot offices saw and what real users have said, plus typical scenarios." },
        ],
      },
      {
        type: "features",
        heading: "Guides for Office Operations",
        intro: "Long-form, practical guides you can use whether or not you ever sign up.",
        items: [
          { title: "Office Efficiency Guide", body: "Where time leaks in a normal office day, and how to measure and fix it." },
          { title: "Internal Request Management Guide", body: "How to set up a request process: what people can ask for, who gets it, who owns it and how it is closed." },
          { title: "Workplace Operations Guide", body: "Running pantry, print, IT, facilities and courier as one operation." },
          { title: "SLA Management Guide", body: "Setting realistic deadlines for office requests and escalating without blame." },
          { title: "Office Automation Guide", body: "What to automate in office services, and what to leave human." },
          { title: "Glossary", body: "Plain definitions for terms like first-accept-wins, SLA breach and escalation chain." },
        ],
      },
      {
        type: "visual",
        visual: "request-timeline",
        heading: "One Idea Runs Through Every Resource",
        body: "A request should travel from the person who needs something to the person who can do it, with a clear owner and a clock. The guides explain the thinking; the product does it in one tap.",
        points: ["Buzzed", "Accepted", "Started with ETA", "Delivered with photo", "Rated 1–5★"],
      },
      {
        type: "stats",
        heading: "ZapBuzzer at a Glance",
        items: [
          { value: "200+", label: "Offices Onboarded" },
          { value: "1.2M", label: "Requests Routed" },
          { value: "14", label: "Cities" },
          { value: "99.9%", label: "Uptime" },
        ],
      },
      {
        type: "audience",
        heading: "Suggested Reading by Role",
        items: [
          { role: "Office Manager", benefit: "Internal request management guide, Free plan, product tour." },
          { role: "Founder or CEO", benefit: "Customer stories, Pro plan, office efficiency guide." },
          { role: "Admin or Facilities Head", benefit: "SLA management guide, workplace operations guide, vs helpdesk." },
          { role: "IT or Procurement", benefit: "Enterprise plan, billing and seats, product FAQ." },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Prefer to Just Try It?",
        body: "The 14-day free trial needs no credit card and no setup call. Create an account, bring your colleagues in, and the first request can go out that same afternoon. A read-only demo is also available from the sign-in page.",
      },
      {"type":"workflow","heading":"A Sensible Evaluation Path in Four Steps","intro":"Most teams who end up using ZapBuzzer well follow roughly the same order. You can skip steps, but this sequence avoids surprises.","steps":[{"title":"Read One Guide","body":"Pick the guide that matches your biggest headache, such as SLA management if facilities complaints drag on, and note what your office does today."},{"title":"Take the Tour","body":"Follow one coffee from tap to rating so you know what requesters and staff actually see."},{"title":"Check the Plan Fit","body":"Count the staff who handle requests and your locations. Ten or fewer on one floor fits Free; more than that, or WhatsApp alerts and escalation, points to Pro."},{"title":"Run It for Real","body":"Use the 14-day trial on one request type for a week before deciding on anything else."}]},
      {"type":"callout","tone":"info","title":"What You Will Not Find Here","body":"No invented case studies and no made-up numbers. The figures on these pages come from our pilot offices and company totals, and the scenarios are clearly labelled as typical examples."},
    ],
    faqs: [
      { q: "Which Page Should I Send to My Finance Team?", a: "The billing and seats page. It explains per-seat pricing, cancellation, currencies and the trial in one place, without product detail they do not need." },
      { q: "Is There a Page That Compares ZapBuzzer With What We Use Today?", a: "Yes. The comparisons cover manual requests, WhatsApp groups, phone and intercom calls, and traditional helpdesks, each with an honest view of where the old way still works." },
      { q: "Where Should I Start If I Am New to ZapBuzzer?", a: "The product tour shows one request end to end in a few minutes. After that, the Free and Pro plan pages explain what you get on each." },
      { q: "Are the Guides Only Useful If We Buy ZapBuzzer?", a: "No. The guides cover office operations in general, such as how to set request deadlines or design a catalogue. They mention ZapBuzzer where it helps, but the advice stands on its own." },
      { q: "How Do I Get Enterprise Details?", a: "Email hello@zapbuzzer.com or book a demo. We reply within one business day." },
      { q: "Is There a Demo I Can Click Around?", a: "Yes. A read-only demo is available from the sign-in page, so you can look at real screens without creating an account." },
      { q: "Which Guide Should an Admin or Facilities Head Read First?", a: "The SLA management guide, then the workplace operations guide. Together they cover setting realistic deadlines, escalating without blame and running all service teams as one operation." },
      { q: "Where Can I Look Up Terms Like First-Accept-Wins or SLA Breach?", a: "The glossary gives plain definitions of office request terms, with a note on how each shows up in ZapBuzzer and which plan includes it." },
    ],
    related: ["pricing", "resources/product-tour", "compare", "customers", "resources/internal-request-management-guide", "resources/glossary", "free-trial"],
    cta: { title: "Ready When You Are", body: "Start a 14-day free trial or book a demo with the team." },
  },
  {
    path: "pricing/free-plan",
    title: "Free Plan: ZapBuzzer for One Floor",
    description:
      "ZapBuzzer’s Free plan is free forever for up to 10 staff in one location, with web and mobile apps, email notifications and 30 days of request history.",
    h1: "Try Buzzer With One Floor, Free Forever",
    eyebrow: "Pricing · Free",
    lead:
      "The Free plan is for small offices and for teams that want to prove the idea on one floor before rolling it out. It is free forever, not a timed trial, and it has real limits that we spell out below.",
    keywords: ["zapbuzzer free plan", "free office request app", "free pantry request system", "free internal request tool", "office buzzer free"],
    heroVisual: "mobile-app",
    template: "pricing",
    sections: [
      {
        type: "table",
        heading: "What the Free Plan Includes",
        headers: ["Item", "Free Plan"],
        rows: [
          ["Price", "Free forever"],
          ["Staff", "Up to 10"],
          ["Locations", "1"],
          ["Apps", "Web app and mobile app"],
          ["Notifications", "Email"],
          ["Request history", "Last 30 days"],
          ["Core flow", "Catalogue, one-tap requests, first-accept-wins, ETA, delivery and ratings"],
        ],
      },
      {
        type: "prose",
        heading: "Who the Free Plan Is For",
        paragraphs: [
          "A single-floor office with a pantry person, someone who handles printing and an admin who takes care of everything else. A startup that has just moved into its first proper office and wants to set good habits early. Or a larger company’s office manager who wants to run a quiet pilot on one floor before asking for budget.",
          "In each case the Free plan gives you the core of ZapBuzzer: people tap what they need, the right staff are notified, the first to accept owns it, and the requester sees who is coming and rates the delivery afterwards.",
        ],
      },
      {
        type: "workflow",
        heading: "What a Request Looks Like on Free",
        steps: [
          { title: "Tap What You Need", body: "An employee picks coffee, prints or IT help from the catalogue, adds a note and chooses a destination." },
          { title: "Staff Are Notified", body: "The responsible staff get the request in the app and by email. Notifications repeat until someone accepts." },
          { title: "First to Accept Owns It", body: "Whoever is free taps Accept. The requester sees their name, photo and ETA." },
          { title: "Delivered and Rated", body: "Staff mark it delivered, optionally with a photo, and the requester rates 1–5★." },
        ],
      },
      {
        type: "visual",
        visual: "mobile-app",
        heading: "Same App, Same One-Tap Grid",
        body: "Free users get the same web app and Android app as Pro. Staff on the move do not miss requests, because the mobile app still rings when the phone is locked or set to silent.",
      },
      {
        type: "comparison",
        heading: "Free vs Pro at a Glance",
        columns: ["Free", "Pro"],
        rows: [
          { label: "Price", a: "Free forever", b: "₹99 / seat / month" },
          { label: "Staff", a: "Up to 10", b: "Unlimited" },
          { label: "Locations", a: "1", b: "Multiple" },
          { label: "Notifications", a: "Email", b: "Telegram and WhatsApp added" },
          { label: "SLA and Escalation Chain", a: "Not included", b: "Included" },
          { label: "Analytics and Scorecards", a: "Not included", b: "Full analytics and scorecards" },
          { label: "Audit Logs and Reports", a: "Not included", b: "Included" },
          { label: "History", a: "Last 30 days", b: "Beyond 30 days" },
        ],
      },
      {
        type: "scenario",
        heading: "A Typical Scenario: A 9-person Studio",
        persona: "Tanvi, Design",
        setting: "Small design studio on one floor, one office assistant handling pantry and IT bits.",
        timeline: [
          { time: "11:40", event: "Tanvi realises there is no HDMI cable in the meeting room and taps IT." },
          { time: "11:40", event: "The assistant gets the request in the app and by email." },
          { time: "11:41", event: "She accepts; Tanvi sees she is on it." },
          { time: "11:43", event: "Cable delivered in 3 minutes, rated 5★." },
        ],
        outcome: "Everything a small studio needs, without paying for features built for multi-floor offices.",
      },
      {
        type: "checklist",
        heading: "Signs You Have Outgrown Free",
        items: [
          "You have more than 10 staff who handle requests",
          "You want to add a second floor, branch or building",
          "Staff live on Telegram or WhatsApp and miss email",
          "You need deadlines that escalate to a manager automatically",
          "You want history older than 30 days or full scorecards",
          "Someone has asked for an audit log",
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Want to See Pro Before Deciding?",
        body: "The 14-day free trial lets you try ZapBuzzer’s paid features with no credit card and no setup call.",
      },
      {"type":"features","heading":"Getting the Most Out of Ten Staff","intro":"Ten staff go further than they sound if you are deliberate about who handles requests.","items":[{"title":"Count Handlers Carefully","body":"List the people who will accept requests: the pantry person, the office assistant, whoever looks after printing and IT bits. That list is what you are fitting within the limit."},{"title":"Keep the Catalogue Short","body":"Start with the five or six things people ask for every day. A short grid gets used; a long one gets ignored."},{"title":"Use Clear Destinations","body":"Name rooms the way people say them, such as Boss Cabin or Meeting Room 2, so deliveries never go to the wrong desk."},{"title":"Install the Mobile App","body":"Because Free notifies by email alongside the apps, make sure staff have the mobile app installed so requests ring through even on silent."}]},
    ],
    faqs: [
      { q: "Can a Free Workspace Have More Than One Team?", a: "Yes. Pantry, print, IT and facilities requests can each route to the right people, as long as the total staff fit within 10 and you work from one location." },
      { q: "Is the Free Plan a Time-Limited Trial?", a: "No. Free is free forever, not a timed trial. You can stay on it as long as you fit within its limits of 10 staff and one location." },
      { q: "What Happens to Requests Older Than 30 Days?", a: "The Free plan shows the last 30 days of history. If you need a longer record for reviews or reporting, Pro is the plan for that." },
      { q: "Can I Get WhatsApp Alerts on Free?", a: "No. Free uses email notifications along with the web and mobile apps. Telegram and WhatsApp pings are part of Pro." },
      { q: "Do I Need a Credit Card to Start on Free?", a: "No. Create an account, add your colleagues and begin sending requests." },
      { q: "Can I Upgrade Later Without Losing Setup?", a: "Your account and workspace live on our server, so moving to Pro is a plan change rather than a fresh setup. Email us if you want help with the switch." },
      { q: "Does the Free Plan Include the Mobile App?", a: "Yes. Free users get the same web app and Android app as Pro, and the mobile app still rings when a phone is locked or set to silent." },
      { q: "What Are the Signs We Have Outgrown the Free Plan?", a: "More than 10 staff handling requests, a second floor or branch, staff who miss email and want Telegram or WhatsApp, or a need for escalation, history beyond 30 days or audit logs." },
    ],
    related: ["pricing", "pricing/pro", "pricing/billing", "features/one-tap-requests", "use-cases/office-manager", "sign-up", "free-trial"],
    cta: { title: "Start Free on One Floor", body: "Sign up, invite up to 10 staff and send your first request today." },
  },
  {
    path: "pricing/pro-plan",
    title: "Pro Plan: ₹99 per Seat for the Whole Office",
    description:
      "ZapBuzzer Pro is ₹99 per seat per month: unlimited staff, multiple locations, Telegram and WhatsApp pings, SLA escalation, full analytics and audit logs.",
    h1: "The Whole Office, the Way It Should Be",
    eyebrow: "Pricing · Pro",
    lead:
      "Pro is our most popular plan. It takes the core one-tap flow and adds the things a growing office needs once requests matter: deadlines that escalate, pings where staff actually look, and records that hold up when someone asks what happened.",
    keywords: ["zapbuzzer pro plan", "office request software price", "per seat office request tool", "sla escalation office requests", "whatsapp telegram office alerts"],
    heroVisual: "analytics",
    template: "pricing",
    sections: [
      {
        type: "table",
        heading: "What Pro Includes",
        headers: ["Item", "Pro Plan"],
        rows: [
          ["Price", "₹99 / seat / month"],
          ["Staff", "Unlimited"],
          ["Locations", "Multiple"],
          ["Notifications", "App and email, plus Telegram and WhatsApp"],
          ["Deadlines", "SLA with escalation chain"],
          ["Reporting", "Full analytics and scorecards"],
          ["Records", "Audit logs and reports"],
          ["Trial", "14 days free, no credit card"],
        ],
      },
      {
        type: "features",
        heading: "What You Get Beyond Free",
        items: [
          { title: "Telegram and WhatsApp Pings", body: "One request goes to app, Telegram, WhatsApp and email at once, and repeats until someone accepts." },
          { title: "SLA and Escalation Chain", body: "Each request has an SLA, a time limit for finishing it. If it runs over, it moves up a list of managers you choose, so someone deals with it instead of it being forgotten." },
          { title: "Full Analytics and Scorecard", body: "See who is fastest, who earns 5★, and when the office buzzes most." },
          { title: "Audit Logs and Reports", body: "Every action is logged, and reports summarise how requests are handled." },
          { title: "Multi-Location", body: "Run several floors, branches or buildings in one workspace." },
          { title: "Unlimited Staff", body: "Add every pantry, print, IT, facilities and reception staff member." },
        ],
      },
      {
        type: "visual",
        visual: "escalation",
        heading: "Nothing Rots in Someone’s DMs",
        body: "On Pro, an overdue request does not just sit there. It climbs your escalation chain, so a facilities complaint that is not fixed in 15 minutes lands with a manager automatically.",
        points: ["Deadline per request", "Automatic escalation when overdue", "Chain of managers you define"],
      },
      {
        type: "scenario",
        heading: "A Typical Scenario: The Freezing Conference Room",
        persona: "Om, Engineer",
        setting: "Conference Room B AC stuck at 16°C before a client meeting.",
        timeline: [
          { time: "09:30", event: "Om taps Facilities with a note about the AC." },
          { time: "09:30", event: "Deepak’s team is pinged on app, WhatsApp and Telegram." },
          { time: "09:31", event: "Deepak accepts; the SLA timer is running." },
          { time: "09:45", event: "If the AC is not fixed within 15 minutes, the request escalates to the next person in the chain." },
        ],
        outcome: "Om does not need to chase. The system does it for him.",
      },
      {
        type: "prose",
        heading: "How ₹99 per Seat Adds Up",
        paragraphs: [
          "Pro is billed per seat per month. A seat is a person using ZapBuzzer in your workspace. Because there are no setup fees and no consultant, the seat price is the cost. You can cancel anytime.",
          "Most offices weigh this against the time currently lost to chase calls and walks to the pantry. Pilot offices saw phone calls drop 87% in the first month, with a 32-second average accept time. Your numbers will depend on your office, which is why the 14-day trial exists.",
        ],
      },
      {
        type: "stats",
        heading: "Pilot Offices, First Month",
        items: [
          { value: "32s", label: "Average Accept Time" },
          { value: "96%", label: "On-Time Delivery" },
          { value: "−87%", label: "Phone Calls" },
          { value: "4.8★", label: "Average Staff Rating" },
        ],
      },
      {
        type: "audience",
        heading: "Who Pro Is Built For",
        items: [
          { role: "Growing Offices", benefit: "More than 10 staff, or more than one floor or branch." },
          { role: "Admin and Facilities Heads", benefit: "Deadlines and escalation that work without daily follow-up." },
          { role: "Founders and CEOs", benefit: "Analytics on how the office actually runs." },
          { role: "Office Managers", benefit: "Audit logs and reports when someone asks what happened." },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Need SSO, White-Label or an API?",
        body: "Those are part of Enterprise, built for groups and facility companies. Pro covers everything a single company’s office needs day to day.",
      },
      {"type":"checklist","heading":"Before You Move a Team Onto Pro","intro":"A short checklist that makes the first month on Pro useful rather than noisy.","items":["Decide which channels each team really reads: Telegram, WhatsApp, email or the app","Write down a realistic deadline for your top three request types","Agree the escalation chain for each team, ideally no more than two or three steps","Pick who reviews analytics and scorecards, and how often","Tell staff that scorecards are for fair credit, not for surveillance","Add your second floor or branch as a separate location from day one"]},
      {"type":"prose","heading":"Where Pro Pays for Itself First","paragraphs":["In most offices it is escalation, not analytics, that people notice first. The facilities complaint that used to be raised three times now reaches a manager on its own. The analytics matter more by the second month, once there is enough history to see busy hours and the slow request types."]},
    ],
    faqs: [
      { q: "Can Different Locations Have Different Escalation Chains?", a: "Pro supports multiple locations and an escalation chain you define, so overdue requests at each site can reach the people responsible there. We can help you plan this during the trial." },
      { q: "What Counts as a Seat?", a: "A seat is a person using ZapBuzzer in your workspace. Pro is priced at ₹99 per seat per month." },
      { q: "Is There a Setup Fee?", a: "No. There are no setup fees and no consultant. Most offices are fully set up within a single afternoon." },
      { q: "Can I Try Pro Before Paying?", a: "Yes. The 14-day free trial needs no credit card and no setup call." },
      { q: "Can I Pay in Currencies Other Than Rupees?", a: "ZapBuzzer offers pricing in INR, USD, EUR and GBP. See the billing page for how this works." },
      { q: "Is There a Lock-In Period on Pro?", a: "No. Pro is pay per seat and you can cancel anytime." },
      { q: "Does Pro Include the API?", a: "No. The REST API and webhooks are part of Enterprise." },
      { q: "Which Pro Feature Do Offices Notice First?", a: "Usually escalation. A facilities complaint that used to be raised three times now reaches a manager on its own. Analytics tend to matter more from the second month, once there is history." },
    ],
    related: ["pricing", "pricing/free", "pricing/enterprise", "pricing/billing", "sla/escalation-chains", "notifications/multi-channel", "analytics", "free-trial"],
    cta: { title: "Try Pro Free for 14 Days", body: "You will not need a card or an onboarding call. Bring your colleagues in this afternoon." },
  },
  {
    path: "pricing/enterprise-plan",
    title: "Enterprise Plan for Groups and Facility Companies",
    description:
      "ZapBuzzer Enterprise offers custom pricing with SSO and SAML, white-label and custom domain, REST API and webhooks, a dedicated CSM and an on-prem option.",
    h1: "Built for Groups, Campuses and Facility Companies",
    eyebrow: "Pricing · Enterprise",
    lead:
      "Enterprise is for organisations that run many offices, or run office services for other companies. It includes everything in Pro, plus options for company sign-in, your own branding, connecting your systems and choosing where the app runs. Pricing is custom, so the right next step is a conversation.",
    keywords: ["zapbuzzer enterprise", "facility management request software", "white label office request app", "sso saml office app", "on-prem request management"],
    heroVisual: "roles",
    template: "pricing",
    sections: [
      {
        type: "table",
        heading: "What Enterprise Adds",
        headers: ["Capability", "What It Is For"],
        rows: [
          ["SSO and SAML", "Staff sign in with your organisation’s existing identity system"],
          ["White-label", "Present ZapBuzzer under your own brand, useful for facility companies"],
          ["Custom domain", "Serve the app from a domain you control"],
          ["REST API and webhooks", "Connect requests and events to your own systems"],
          ["Dedicated CSM", "A named customer success manager for rollout and ongoing help"],
          ["On-prem option", "Run ZapBuzzer within your own infrastructure where required"],
          ["Pricing", "Custom"],
        ],
      },
      {
        type: "prose",
        heading: "Who Usually Needs Enterprise",
        paragraphs: [
          "Two kinds of organisations. First, groups with many offices across cities, where IT needs single sign-on and central control, and where requests may need to flow into other internal systems. Second, facility management companies who provide pantry, housekeeping or front-desk services to client offices and want to offer request handling under their own name.",
          "If you are a single office, or a company with a few floors, Pro almost certainly covers you. We would rather tell you that than sell you a plan you do not need.",
        ],
      },
      {
        type: "visual",
        visual: "roles",
        heading: "Central Control Across Many Sites",
        body: "Permissions for each role, and the audit log of every action, work across every location. Enterprise adds company sign-in and your own branding on top, so IT and operations can manage large rollouts.",
      },
      {
        type: "workflow",
        heading: "How an Enterprise Engagement Works",
        steps: [
          { title: "Talk to Us", body: "Email hello@zapbuzzer.com or book a demo. Tell us about your sites, headcount and requirements." },
          { title: "Scope", body: "We work out which Enterprise options you need, such as SSO, white-label or on-prem, and agree pricing." },
          { title: "Pilot", body: "Many organisations start with one site to confirm fit before wider rollout." },
          { title: "Rollout", body: "Your dedicated CSM helps plan the rollout site by site." },
        ],
      },
      {
        type: "scenario",
        heading: "A Typical Scenario: A Facility Company",
        persona: "Operations Head, Facility Services Provider",
        setting: "Runs pantry and front-desk staff for several client offices.",
        timeline: [
          { time: "Week 1", event: "Discussion with ZapBuzzer about white-label and custom domain needs." },
          { time: "Week 2", event: "Pilot at one client office under the provider’s own brand." },
          { time: "Month 2", event: "Rollout to further client offices with the CSM’s help." },
        ],
        outcome: "Client employees request through a branded app; the provider sees performance across sites.",
      },
      {
        type: "checklist",
        heading: "Questions to Bring to the First Call",
        items: [
          "How many sites and roughly how many seats?",
          "Which identity provider does IT use for sign-in?",
          "Do you need the app under your own brand or domain?",
          "Which internal systems should receive request data?",
          "Is cloud hosting acceptable, or is on-prem required?",
          "Who will own the rollout on your side?",
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Technical Details on Request",
        body: "We share specifics for SSO, the API, webhooks and on-prem deployment during scoping, based on your setup. Please talk to us rather than guessing.",
      },
      {"type":"comparison","heading":"Pro or Enterprise? A Quick Test","columns":["Pro Is Enough When","Enterprise Fits When"],"rows":[{"label":"Sign-In","a":"Staff are happy with ZapBuzzer accounts","b":"IT requires sign-in through your identity provider"},{"label":"Brand","a":"ZapBuzzer’s own app is fine","b":"Client offices should see your brand and domain"},{"label":"Systems","a":"Requests live in ZapBuzzer","b":"Requests or events must reach your own systems"},{"label":"Hosting","a":"Cloud is acceptable","b":"Policy requires running it on your own infrastructure"},{"label":"Support","a":"Email support is enough","b":"You want a named person for a multi-site rollout"}]},
      {"type":"audience","heading":"Who Usually Joins the Enterprise Conversation","items":[{"role":"Head of Administration","benefit":"Wants consistent service standards across every site."},{"role":"IT and Security","benefit":"Needs answers on sign-in, hosting and data flows before approving."},{"role":"Facility Company Leadership","benefit":"Wants to offer request handling to clients under its own brand."},{"role":"Procurement","benefit":"Needs custom pricing agreed against sites and seats."}]},
    ],
    faqs: [
      { q: "We Are a Single Office With Strict IT Rules. Do We Need Enterprise?", a: "Only if you need one of its capabilities, such as SSO and SAML or on-prem hosting. If not, Pro covers a single office well, and we will say so on the call." },
      { q: "Can a Facility Company Manage Several Client Offices?", a: "That is one of the main reasons Enterprise exists. White-label and a custom domain let you present the service under your brand; we scope the details with you." },
      { q: "How Much Does Enterprise Cost?", a: "Enterprise pricing is custom and depends on your sites, seats and the capabilities you need. Contact us and we reply within one business day." },
      { q: "Does Enterprise Include Everything in Pro?", a: "Yes. Enterprise builds on Pro and adds SSO and SAML, white-label branding on your own custom domain, webhooks and a REST API, a dedicated CSM and an on-prem option." },
      { q: "Can We Pilot One Site First?", a: "Yes, and we recommend it. A single-site pilot confirms fit before you commit to a wider rollout." },
      { q: "Where Can I Find API Documentation?", a: "API and webhook details are shared with Enterprise customers during scoping. Get in touch to discuss what you want to connect." },
      { q: "Can Enterprise Run on Our Own Infrastructure?", a: "Yes, there is an on-prem option for organisations whose policy requires it. Deployment specifics are shared during scoping, so talk to us about your setup." },
      { q: "What Does the Dedicated CSM Do on Enterprise?", a: "A named customer success manager helps plan the rollout site by site and supports you afterwards. It is included with Enterprise." },
    ],
    related: ["pricing", "pricing/pro", "enterprise", "integrations/sso-saml", "integrations/white-label", "developers/api", "demo", "contact"],
    cta: { title: "Talk to Us About Enterprise", body: "Email hello@zapbuzzer.com or book a demo. We reply within one business day." },
  },
  {
    path: "pricing/billing-and-seats",
    title: "Billing, Seats, Currencies and Free Trial",
    description:
      "How ZapBuzzer billing works: pay per seat monthly, cancel anytime, no setup fees, pricing in INR, USD, EUR or GBP, and a 14-day trial with no credit card.",
    h1: "Billing and Seats, Explained Simply",
    eyebrow: "Pricing · Billing",
    lead:
      "Pay per seat. Cancel anytime. That is most of it. This page covers the rest: what a seat is, how the trial works, which currencies you can choose and what to do if you have questions.",
    keywords: ["zapbuzzer billing", "per seat billing", "zapbuzzer free trial", "zapbuzzer currencies", "cancel zapbuzzer"],
    heroVisual: "request-dashboard",
    template: "pricing",
    sections: [
      {
        type: "prose",
        heading: "Per-Seat Billing",
        paragraphs: [
          "ZapBuzzer Pro costs ₹99 per seat per month. A seat is a person using ZapBuzzer in your workspace. You pay for the people you add, so a 30-person office pays for 30 seats and a 300-person office pays for 300.",
          "There are no setup fees and no consultant to hire. Most offices finish setup within one afternoon, so the seat price is the whole cost of Pro. Enterprise is priced separately on a custom basis.",
        ],
      },
      {
        type: "table",
        heading: "Billing at a Glance",
        headers: ["Topic", "How It Works"],
        rows: [
          ["Free plan", "Free forever, a single location with a maximum of 10 staff"],
          ["Pro plan", "₹99 per seat per month"],
          ["Enterprise", "Custom pricing"],
          ["Setup fees", "None"],
          ["Cancellation", "Cancel anytime"],
          ["Currencies", "INR, USD, EUR, GBP"],
          ["Free trial", "14 days, with no card required and no onboarding call"],
        ],
      },
      {
        type: "workflow",
        heading: "How the 14-day Free Trial Works",
        steps: [
          { title: "Sign Up", body: "Create your workspace. No credit card and no setup call are needed." },
          { title: "Invite Your Team", body: "Add the pantry, print, IT, facilities or reception staff and a few requesters." },
          { title: "Use It for Real", body: "Route actual requests for two weeks and see how accept and delivery times look." },
          { title: "Decide", body: "Choose a plan that fits, or stay on Free if your office fits its limits." },
        ],
      },
      {
        type: "visual",
        visual: "request-dashboard",
        heading: "Judge It on Your Own Requests",
        body: "During the trial the dashboard shows live requests, who accepted them and how long they took. That is a better basis for a pricing decision than any brochure.",
      },
      {
        type: "prose",
        heading: "Currencies",
        paragraphs: [
          "ZapBuzzer offers pricing in Indian rupees, US dollars, euros and British pounds. Pro is listed at ₹99 per seat per month. If you want to pay in USD, EUR or GBP, choose that currency when you set up billing, or contact us if you need help.",
        ],
      },
      {
        type: "scenario",
        heading: "A Typical Scenario: Growing From One Floor",
        persona: "Priya, Office Manager",
        setting: "Started on Free with the pantry team on one floor.",
        timeline: [
          { time: "Month 1", event: "Pantry and print requests run on Free for 8 staff." },
          { time: "Month 3", event: "The office takes a second floor and wants WhatsApp pings and escalation." },
          { time: "Month 3", event: "Priya moves the workspace to Pro and pays per seat." },
        ],
        outcome: "No migration, no setup fee. The bill grows with the team.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Questions About Invoices or Payment?",
        body: "Email hello@zapbuzzer.com with your workspace name and question. We reply within one business day.",
      },
      {"type":"table","heading":"Rough Monthly Cost on Pro","intro":"Pro is a straight multiplication of seats by ₹99. These are simple illustrations, not quotes.","headers":["Seats","Monthly Cost on Pro"],"rows":[["10","₹990"],["25","₹2,475"],["50","₹4,950"],["100","₹9,900"]]},
      {"type":"prose","heading":"Counting Seats Before You Start","paragraphs":["Before you invite everyone, make a quick list of who will actually use ZapBuzzer: the people who send requests and the pantry, print, IT, facilities and reception staff who handle them. That list is your seat count, and it is easy to check against the bill.","Because there are no setup fees, starting is not a big commitment. If a new floor opens or a team shrinks, the number of people in your workspace changes and the bill follows it. If anything about a charge is unclear, email us with your workspace name."]},
      {"type":"checklist","heading":"Before the Trial Ends","items":["Check how many people actually used ZapBuzzer during the two weeks","Decide whether you fit Free’s limits of 10 staff and one location","If not, choose your billing currency: INR, USD, EUR or GBP","Confirm who in the office owns the subscription","Note the features you relied on, such as WhatsApp pings or escalation"]},
    ],
    faqs: [
      { q: "What Happens When the 14-day Trial Ends?", a: "You choose a plan. If your office fits within 10 staff and one location, you can carry on with the Free plan; otherwise move to Pro and pay per seat." },
      { q: "Does the Bill Change If We Add People?", a: "Pro is priced per seat, so adding people adds seats. If you want to understand how a specific change will show up, email hello@zapbuzzer.com and we will explain." },
      { q: "Who Should Own Billing in the Workspace?", a: "Usually the workspace owner, who is also the person who can see request spend. Many offices make the office manager or admin head the owner." },
      { q: "Is a Credit Card Needed to Start the 14-day Trial?", a: "No. The 14-day free trial needs no credit card and no setup call." },
      { q: "Can I Cancel My Subscription at Any Time?", a: "Yes. ZapBuzzer is pay per seat with cancel anytime." },
      { q: "Can I Be Billed in USD, EUR or GBP Instead of Rupees?", a: "Yes. INR, USD, EUR and GBP are offered; choose your currency when you set up billing, or contact us if you need help." },
      { q: "Is There Anything to Pay on Top of the Seat Price?", a: "No. There are no setup fees and no consultant, so the seat price is the whole cost of Pro. You sign up and invite your team." },
      { q: "How Is Enterprise Billed?", a: "Enterprise pricing is custom. We agree it with you during scoping." },
    ],
    related: ["pricing", "pricing/free", "pricing/pro", "pricing/enterprise", "free-trial", "contact"],
    cta: { title: "Start Your 14-day Trial", body: "No credit card. Cancel anytime." },
  },
  {
    path: "resource-hub/product-tour",
    title: "Product Tour: One Request, Tap to Rating",
    description:
      "Take a tour of ZapBuzzer: the employee catalogue, multi-channel pings, first-accept-wins, ETA tracking, delivery photos, ratings, SLA timers and analytics.",
    h1: "Follow One Coffee Through ZapBuzzer",
    eyebrow: "Product Tour",
    lead:
      "The fastest way to understand ZapBuzzer is to follow a single request. Aarav is in a board call and wants coffee in the Boss Cabin. Here is every screen it touches, and what each person sees.",
    keywords: ["zapbuzzer product tour", "zapbuzzer demo", "how zapbuzzer works", "office request app tour", "internal request crm walkthrough"],
    heroVisual: "request-timeline",
    sections: [
      {
        type: "visual",
        visual: "catalog",
        heading: "Stop 1: The Catalogue",
        body: "Aarav opens the app and sees what he can ask for: coffee, tea, juice, snacks and dry fruits, plus prints, IT help, facilities and courier. What he orders most often needs only a single tap. He picks Coffee, adds “two cups, one without sugar”, chooses Boss Cabin and taps Buzz.",
      },
      {
        type: "visual",
        visual: "notification-flow",
        heading: "Stop 2: The Right Team Gets Pinged",
        body: "The request goes to the whole pantry team at once. On Free that means the app and email; on Pro it also arrives on Telegram and WhatsApp. If nobody accepts, the notifications repeat.",
      },
      {
        type: "visual",
        visual: "acceptance",
        heading: "Stop 3: First to Accept Owns It",
        body: "Raj is free and taps Accept 12 seconds later. The request is his. Everyone else on the team sees it is taken, so nobody makes a second pot.",
      },
      {
        type: "visual",
        visual: "sla-timer",
        heading: "Stop 4: The Clock Is Running",
        body: "Every request is timed. On Pro, the request also has an SLA, the time limit for finishing it. If it runs over, it escalates to a manager through your escalation chain (the list of people to alert, in order). Raj taps Started and sets an ETA, which Aarav sees along with Raj’s name and photo.",
      },
      {
        type: "visual",
        visual: "delivery",
        heading: "Stop 5: Delivered and Rated",
        body: "Raj marks the request delivered, optionally attaching a photo. Aarav gets a prompt to rate from 1 to 5 stars. Four minutes, no phone calls, one hot coffee.",
      },
      {
        type: "visual",
        visual: "analytics",
        heading: "Stop 6: What the Owner Sees",
        body: "Every request adds to analytics: accept times, delivery times, ratings, busy hours. Scorecards show who is fastest and who earns 5★, and the owner can see request costs such as a team lunch. Full analytics and scorecards are on Pro.",
      },
      {
        type: "workflow",
        heading: "The Same Flow for Every Team",
        steps: [
          { title: "Print Room", body: "Kavya uploads a PDF, sets 24 colour copies and a destination; prints arrive before her demo." },
          { title: "IT", body: "Tanvi taps IT for an HDMI cable; Priya brings it in 3 minutes." },
          { title: "Facilities", body: "Om reports the AC stuck at 16°C; Deepak is pinged and, on Pro, an unfixed issue moves up the chain after 15 minutes." },
          { title: "Courier", body: "Neha at reception taps Courier Pickup; the mailroom logs it with an audit trail." },
        ],
      },
      {
        type: "visual",
        visual: "audit-log",
        heading: "Behind the Scenes: Roles and Audit",
        body: "Admins decide what each role can see and do, and every action is logged. Spend is visible to the owner only. Audit logs and reports are part of Pro.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Click Through It Yourself",
        body: "A read-only demo is available from the sign-in page. Or start the 14-day free trial and send your own first request.",
      },
      {"type":"table","heading":"Who Sees What at Each Stop","intro":"The same request looks different depending on your role. Here is the coffee from Aarav’s, Raj’s and the owner’s point of view.","headers":["Stop","Aarav (Requester)","Raj (Pantry)","Owner"],"rows":[["Buzzed","Request sent, waiting for someone","New request alert, repeating","Live request on the dashboard"],["Accepted","Raj’s name and photo","The request is his","Accept time recorded"],["Started","ETA on screen","Timer running","In progress"],["Delivered","Rating prompt","Optional delivery photo","Delivery time recorded"],["Rated","Done","Rating on his scorecard","Feeds analytics and scorecards"]]},
      {"type":"scenario","heading":"The Tour, Minute by Minute","persona":"Aarav, CEO","setting":"Board call in the Boss Cabin; coffee for two.","timeline":[{"time":"10:14:00","event":"Aarav taps Coffee, adds a note and chooses Boss Cabin."},{"time":"10:14:00","event":"The pantry team is pinged at once."},{"time":"10:14:12","event":"Raj accepts; everyone else sees it is taken."},{"time":"10:15","event":"Raj taps Started and shares an ETA."},{"time":"10:18","event":"Delivered; Aarav rates it after the call."}],"outcome":"Four minutes from tap to cup, and Aarav never left the call."},
      {"type":"checklist","heading":"What to Try When You Open the Demo","items":["Find the catalogue and look at how items are grouped","Follow a request’s states from Buzzed to Rated","Open a staff scorecard and see what it measures","Check where request history and analytics live"]},
    ],
    faqs: [
      { q: "What Details Travel With a Request in the Tour?", a: "Every request carries the item, an optional note such as “one without sugar” and a destination, so staff do not have to call back for details." },
      { q: "How Quickly Do Staff Usually Respond?", a: "Pilot offices averaged a 32-second accept time in their first month. Your own numbers will show up in the dashboard from the first request." },
      { q: "Is There a Live Demo I Can Try?", a: "Yes. The read-only demo on the sign-in page lets you explore the screens without signing up." },
      { q: "Does the Tour Show Free or Pro?", a: "Both. The core flow is the same on Free. Telegram and WhatsApp pings, SLA escalation, full analytics and audit logs are Pro features, and the tour notes this where it applies." },
      { q: "Does the Tour Work the Same on the Android App and the Web App?", a: "Yes. The flow is the same on both: the Android app for people on the move, and the web app in a browser." },
      { q: "Can We Customise the Catalogue?", a: "The catalogue is built around your office’s own items, such as your pantry menu and service teams, so people see what is actually available." },
      { q: "What Does the Owner See at the End of the Tour?", a: "Every request feeds analytics: accept times, delivery times, ratings and busy hours. The owner can also see request costs such as a team lunch. Full analytics and scorecards are on Pro." },
      { q: "Does the Tour Apply to Print, IT and Facilities Too?", a: "Yes. The same flow covers Kavya’s 24 colour copies, Tanvi’s HDMI cable, Om’s stuck AC and Neha’s courier pickup; only the catalogue item and team change." },
    ],
    related: ["how-it-works", "resources", "features", "features/first-accept-wins", "workflows/coffee-request", "demo", "free-trial"],
    cta: { title: "Send Your Own First Request", body: "Start a 14-day free trial and run the tour on your own floor." },
  },
  {
    path: "resource-hub/faq",
    title: "ZapBuzzer Product FAQ",
    description:
      "Answers to common questions about ZapBuzzer: what it is, how routing and first-accept work, notifications, plans, the mobile app, setup time and support.",
    h1: "Questions We Hear in Almost Every Demo",
    eyebrow: "FAQ",
    lead:
      "Short, honest answers about what ZapBuzzer does, what it does not do and which plan includes what. If your question is not here, email hello@zapbuzzer.com.",
    keywords: ["zapbuzzer faq", "office request app questions", "zapbuzzer help", "how does zapbuzzer work", "zapbuzzer plans faq"],
    heroVisual: "staff-queue",
    sections: [
      {
        type: "prose",
        heading: "What ZapBuzzer Is",
        paragraphs: [
          "ZapBuzzer is an internal-request CRM for offices: a system that keeps track of every request people make to the office’s service teams. Employees tap what they need, such as coffee, prints, IT help, a facilities fix or a courier pickup. The right team is pinged, the first person to accept owns the request, and the requester sees who is on it and rates them when done.",
          "It is not a glorified Telegram bot, and it is not a generic to-do app. Requests have states, owners and timers, and everything adds up to history and analytics.",
        ],
      },
      {
        type: "table",
        heading: "Which Plan Includes What",
        headers: ["Capability", "Free", "Pro", "Enterprise"],
        rows: [
          ["Staff", "Up to 10", "Unlimited", "Unlimited"],
          ["Locations", "1", "Multiple", "Multiple"],
          ["Email notifications", "Yes", "Yes", "Yes"],
          ["Telegram and WhatsApp", "No", "Yes", "Yes"],
          ["SLA and escalation chain", "No", "Yes", "Yes"],
          ["Full analytics and scorecard", "No", "Yes", "Yes"],
          ["Audit logs and reports", "No", "Yes", "Yes"],
          ["SSO, white-label, API, on-prem", "No", "No", "Yes"],
        ],
      },
      {
        type: "visual",
        visual: "staff-queue",
        heading: "What Staff See",
        body: "Staff see open requests with item, note, destination and time. They tap Accept on what they can handle, then Started with an ETA, then Delivered.",
      },
      {
        type: "workflow",
        heading: "The Request Lifecycle",
        steps: [
          { title: "Buzzed", body: "The employee sends the request." },
          { title: "Accepted", body: "The first staff member to accept owns it." },
          { title: "Started", body: "Work begins and an ETA is shared." },
          { title: "Delivered", body: "Marked done, optionally with a photo." },
          { title: "Rated", body: "The requester rates 1–5★." },
        ],
      },
      {
        type: "scenario",
        heading: "A Typical Scenario: Courier at the Gate",
        persona: "Neha, Reception",
        setting: "A courier is waiting at the gate for an outgoing package.",
        timeline: [
          { time: "16:10", event: "Neha taps Courier Pickup." },
          { time: "16:10", event: "The mailroom is notified." },
          { time: "16:12", event: "The pickup is logged with an audit trail." },
        ],
        outcome: "Reception does not have to chase anyone, and there is a record if the package is questioned later.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Still Have a Question?",
        body: "Email hello@zapbuzzer.com. We are based in Pune and reply within one business day.",
      },
      {"type":"features","heading":"Quick Answers by Team","intro":"The same flow covers every service team, with a few details that matter for each.","items":[{"title":"Pantry","body":"Coffee, tea, juice, snacks and dry fruits from a catalogue, with usual orders one tap away and owner-only cost visibility for things like team lunches."},{"title":"Print Room","body":"Upload a PDF, set copies and colour, and choose where prints should be delivered."},{"title":"IT","body":"Quick asks like an HDMI cable or a stuck projector route straight to the IT desk."},{"title":"Facilities","body":"AC too cold or a light out goes to facilities; on Pro, overdue requests escalate."},{"title":"Reception and Mailroom","body":"Courier pickups are logged with an audit trail."}]},
      {"type":"glossary","heading":"Three Terms That Come Up in Every Demo","terms":[{"term":"First-Accept-Wins","definition":"A request goes to the whole team and the first person to tap Accept owns it."},{"term":"Escalation Chain","definition":"The people an overdue request moves up through on Pro."},{"term":"Scorecard","definition":"A summary for each staff member of their speed and ratings. Full scorecards are on Pro."}]},
    ],
    faqs: [
      { q: "What Exactly Is ZapBuzzer?", a: "An internal-request CRM for offices. Employees tap what they need, such as coffee, prints, IT help, a facilities fix or a courier pickup. The right team is pinged, the first to accept owns it, and the requester rates them when done." },
      { q: "How Does a Request Move From Tap to Done?", a: "It is buzzed, accepted by the first free staff member, started with an ETA, marked delivered (optionally with a photo) and rated 1–5★. Every step is timed." },
      { q: "Where Do Staff Receive New Requests?", a: "In the app and by email on every plan, and also on Telegram and WhatsApp on Pro. Notifications repeat until someone accepts." },
      { q: "Can Two Staff End Up Doing the Same Request?", a: "No. Requests go to the whole team, but the first person to tap Accept owns it and the others see it is taken." },
      { q: "What If a Request Is Never Accepted or Runs Late?", a: "Notifications repeat until someone accepts, and every request has a deadline. Overdue requests escalate to a manager automatically; the full escalation chain is part of Pro." },
      { q: "How Much Does ZapBuzzer Cost, and Is There a Trial?", a: "Free is free forever for up to 10 staff in one location, Pro is ₹99 per seat per month and Enterprise is custom. You can try it free for 14 days with no credit card." },
      { q: "Will the Mobile App Ring If My Phone Is on Silent?", a: "Yes. The Android app still rings when the phone is locked or set to silent. Anyone can also use the web app in a browser, as accounts live on the server." },
      { q: "How Do We Get Started With ZapBuzzer?", a: "Sign up, invite your team and send the first request. Most offices are up and running in an afternoon. There are no setup fees, no consultant and no setup call." },
    ],
    related: ["resource-hub", "resources/product-tour", "pricing", "how-it-works", "mobile-app", "contact", "free-trial"],
    cta: { title: "See It for Yourself", body: "Open the read-only demo or start a 14-day free trial." },
  },
  {
    path: "customer-stories",
    title: "Customer Stories and Pilot Results",
    description:
      "How offices use ZapBuzzer: pilot results, real words from Acme HQ’s founder and staff, the offices on board and typical scenarios across pantry and print.",
    h1: "What Offices Changed When They Stopped Chasing Requests",
    eyebrow: "Customers",
    lead:
      "ZapBuzzer runs in 200+ offices across 14 cities. Below are the results from our pilot offices, the words of people who use it every day and the typical scenarios we see over and over.",
    keywords: ["zapbuzzer customers", "zapbuzzer case studies", "office request software reviews", "zapbuzzer results", "acme hq zapbuzzer"],
    heroVisual: "scorecard",
    sections: [
      {
        type: "stats",
        heading: "Pilot Offices, First Month",
        items: [
          { value: "32s", label: "Average Accept Time" },
          { value: "96%", label: "On-Time Delivery" },
          { value: "−87%", label: "Phone Calls" },
          { value: "4.8★", label: "Average Staff Rating" },
        ],
        note: "Measured across ZapBuzzer pilot offices during their first month.",
      },
      {
        type: "prose",
        heading: "Offices Using ZapBuzzer",
        paragraphs: [
          "Acme HQ, Northwind, Lumen Labs, Volt & Co, Brightpath and Meridian are among the offices running on ZapBuzzer. Across all customers, ZapBuzzer has routed 1.2 million requests in 14 cities at 99.9% uptime.",
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Aarav Sharma, Founder & CEO, Acme HQ (Pune)",
        body: "“The office runs quieter. Nobody’s shouting names down the hall. Coffee arrives before anyone asks twice.”",
      },
      {
        type: "audience",
        heading: "In Their Words",
        items: [
          { role: "Priya, Office Manager", benefit: "“Coffee arrives before anyone asks twice. The pantry WhatsApp group is finally quiet.”" },
          { role: "Kavya, Sales Lead", benefit: "“Print jobs land at my desk before the client even sits down. Zero chase calls.”" },
          { role: "Deepak, Admin Head", benefit: "“Facilities tickets auto-escalate now. Nothing rots in someone’s DMs.”" },
        ],
      },
      {
        type: "visual",
        visual: "before-after",
        heading: "The Before and After We Hear Most",
        body: "The old way, “Raju, two coffees in the boss cabin”, took 25 minutes and 3 phone calls, and the coffee arrived cold. With ZapBuzzer the same order took 4 minutes and no phone calls, and the coffee arrived hot.",
      },
      {
        type: "scenario",
        heading: "Typical Scenario: Coffee During a Board Call",
        persona: "Aarav, CEO",
        setting: "In a board call, wants coffee in the Boss Cabin.",
        timeline: [
          { time: "10:14", event: "Aarav taps Coffee → Boss Cabin." },
          { time: "10:14", event: "The pantry sees it on Telegram." },
          { time: "10:14", event: "Raj accepts in 12 seconds." },
          { time: "10:18", event: "Coffee delivered; Aarav rates it." },
        ],
        outcome: "This is a typical scenario that illustrates the flow, not a specific customer case study.",
      },
      {
        type: "scenario",
        heading: "Typical Scenario: Prints Before a Pitch",
        persona: "Kavya, Sales",
        setting: "Pitch in 10 minutes, deck not printed.",
        timeline: [
          { time: "10:50", event: "Kavya uploads the PDF and requests 24 colour copies." },
          { time: "10:51", event: "The print room accepts." },
          { time: "10:58", event: "Prints arrive before the demo." },
        ],
        outcome: "A typical scenario showing how print requests work.",
      },
      {
        type: "scenario",
        heading: "Typical Scenario: Lunch for 12",
        persona: "Vivek, Operations",
        setting: "Team lunch for 12.",
        timeline: [
          { time: "12:05", event: "Vivek picks items and adds a note." },
          { time: "12:06", event: "The pantry queues the order and accepts." },
          { time: "12:40", event: "Lunch delivered; Vivek rates it; the owner sees the cost." },
        ],
        outcome: "A typical scenario showing pantry orders with owner-only cost visibility.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Want to Compare Notes With Us?",
        body: "Book a demo and we will walk through how offices like yours usually roll ZapBuzzer out.",
      },
      {"type":"metrics","heading":"How to Read the Pilot Numbers","intro":"Each figure measures a different part of a request’s life. Here is what they mean in plain terms.","items":[{"metric":"32s Average Accept Time","meaning":"From someone tapping Buzz to a staff member owning the request. It shows whether the right team is actually being reached."},{"metric":"96% On-Time Delivery","meaning":"The share of requests finished within their deadline. It shows whether the work, not just the response, keeps pace."},{"metric":"−87% Phone Calls","meaning":"The fall in calls once requests moved into ZapBuzzer, most of which were calls asking where something was."},{"metric":"4.8★ Average Staff Rating","meaning":"How requesters rated deliveries. It shows the speed did not come at the cost of the people doing the work."}]},
      {"type":"workflow","heading":"How Offices Usually Roll Out","intro":"There is no single pattern, but most offices we onboard go through something like this.","steps":[{"title":"One Request Type","body":"Coffee or prints first, because they are frequent and everyone notices when they get faster."},{"title":"One Floor","body":"A single floor or team proves the habit before the rest of the office joins."},{"title":"More Teams","body":"IT, facilities and courier follow once requesters trust that a tap works."},{"title":"Deadlines and Review","body":"On Pro, SLA deadlines, escalation and a monthly look at analytics come once there is history."}]},
      {"type":"callout","tone":"warning","title":"A Note on What Is Real Here","body":"The quotes on this page are from real users and the numbers are from our pilot offices and company totals. The scenarios are typical examples to show the flow; we do not present them as named case studies."},
    ],
    faqs: [
      { q: "Which Kinds of Offices Use ZapBuzzer?", a: "Offices with real service teams: a pantry, a print room, IT and facilities help, and reception handling couriers. The product was built in a Pune office tired of phone tag." },
      { q: "What Do Customers Usually Start With?", a: "Most start with one frequent request type, such as coffee or prints, on one floor, then add more teams once people trust the flow." },
      { q: "Where Do the Pilot Numbers Come From?", a: "They were measured across ZapBuzzer pilot offices in their first month: requests accepted in 32 seconds on average, 96% of deliveries on time, 87% fewer phone calls and a 4.8★ average staff rating." },
      { q: "Are the Scenarios Real Customer Stories?", a: "They are typical scenarios that show how ZapBuzzer is used day to day. The quotes on this page are from real users." },
      { q: "How Many Offices Use ZapBuzzer?", a: "More than 200 offices across 14 cities, with 1.2 million requests routed so far." },
      { q: "Can I Talk to the Team About Results for My Office?", a: "Yes. Book a demo or email hello@zapbuzzer.com and we reply within one business day." },
      { q: "Which Offices Are Named as ZapBuzzer Customers?", a: "Acme HQ, Northwind, Lumen Labs, Volt & Co, Brightpath and Meridian are among the offices running on ZapBuzzer." },
      { q: "What Does the 4.8★ in the Pilot Results Measure?", a: "It is the average rating requesters gave deliveries in pilot offices’ first month. It shows faster service did not come at the cost of the people doing the work." },
    ],
    related: ["clients", "resources", "compare", "why-zapbuzzer", "use-cases/ceo", "pricing", "demo"],
    cta: { title: "Make Your Office Quieter", body: "Try it free for 14 days, with no card required and no onboarding call." },
  },
  {
    path: "resource-hub/glossary",
    title: "Glossary of Office Request and SLA Terms",
    description:
      "Plain-language definitions of office request management terms: first-accept-wins, SLA, escalation chain, ETA, catalogue, scorecard, audit log, seat and more.",
    h1: "Office Request Terms, in Plain Language",
    eyebrow: "Glossary",
    lead:
      "Office work comes with its own jargon, and ZapBuzzer adds a few words of its own. Here is what each term means in everyday words, with a note on where it shows up in the product.",
    keywords: ["office request glossary", "sla glossary", "first accept wins meaning", "escalation chain definition", "internal request management terms"],
    heroVisual: "request-timeline",
    sections: [
      {
        type: "glossary",
        heading: "Terms a to Z",
        terms: [
          { term: "Accept", definition: "Tapping Accept claims a request. Once a staff member accepts it, the job is theirs." },
          { term: "Accept Time", definition: "How long it takes from a request being sent to someone accepting it. Pilot offices averaged 32 seconds." },
          { term: "Analytics", definition: "Charts and numbers showing how many requests come in, how fast they are handled, how they are rated and when the office is busiest. Full analytics are on Pro." },
          { term: "Audit Log", definition: "A running record of every action in the workspace: what was done, who did it and when. Part of Pro." },
          { term: "Auto-Escalation", definition: "When a request goes past its deadline, it is passed to a manager automatically, so nobody has to chase it." },
          { term: "Boss Cabin", definition: "A common example of a destination: the room where a request should be delivered." },
          { term: "Buzz", definition: "Sending a request in ZapBuzzer. Pick an item, add a note, tap Buzz." },
          { term: "Catalogue", definition: "The menu of things employees can ask for, such as coffee, prints, IT help or courier pickup." },
          { term: "Category", definition: "A group of similar requests, such as pantry, print, IT, facilities or courier. It decides which team gets the request." },
          { term: "Chase Call", definition: "A phone call made just to ask whether someone is working on your request. ZapBuzzer aims to remove these." },
          { term: "Courier Pickup", definition: "A request for the mailroom or reception to collect or send a package, logged with an audit trail." },
          { term: "Custom Domain", definition: "Running the app on your own web address. Available on Enterprise." },
          { term: "Delivered", definition: "The stage when the job is done. Staff can attach a photo to show it." },
          { term: "Destination", definition: "Where a request should go, such as a cabin, desk or meeting room." },
          { term: "Dedicated CSM", definition: "A named customer success manager: one person at ZapBuzzer who helps you roll out and keep things running. Enterprise." },
          { term: "Escalation Chain", definition: "The list of people, in order, that an overdue request is passed to until someone deals with it. Part of Pro." },
          { term: "ETA", definition: "Estimated time of arrival: when staff expect to deliver, shared as they start the job." },
          { term: "First-Accept-Wins", definition: "The request goes to everyone on the team, and the first person to tap Accept gets the job." },
          { term: "Internal Request", definition: "A request from one person in an organisation to a service team in the same organisation." },
          { term: "Internal-Request CRM", definition: "Software that keeps track of requests inside the office, with an owner, a stage, a timer and a history for each one. It works the way a sales CRM does for customers." },
          { term: "Location", definition: "An office site in a workspace. Free covers one location; Pro supports multiple." },
          { term: "Multi-Channel Notification", definition: "One alert sent to several places at once. On Pro: app, Telegram, WhatsApp and email." },
          { term: "On-Prem", definition: "Running the software on your own servers instead of in the cloud. An Enterprise option." },
          { term: "On-Time Delivery", definition: "The share of requests delivered within their deadline. Pilot offices reached 96%." },
          { term: "Owner", definition: "The workspace owner, who can see spend. Also used for the staff member who owns a request." },
          { term: "Rating", definition: "The 1–5★ score a requester gives after delivery." },
          { term: "Repeat Notification", definition: "An alert that keeps coming until someone accepts the request." },
          { term: "REST API", definition: "A way for your own software to connect to ZapBuzzer and exchange data with it. Enterprise." },
          { term: "Role", definition: "A set of permissions that decides what someone can see and do, such as owner, manager, staff or employee." },
          { term: "SAML", definition: "A standard that lets staff sign in with your organisation’s existing login. It is used for single sign-on. Enterprise." },
          { term: "Scorecard", definition: "A summary for each staff member showing their speed, ratings and how often they deliver on time. Full scorecards on Pro." },
          { term: "Seat", definition: "A person using ZapBuzzer in your workspace. Pro is billed per seat per month." },
          { term: "SLA", definition: "Short for service level agreement. In ZapBuzzer, it is the time limit for finishing a request. Part of Pro." },
          { term: "SLA Breach", definition: "When a request goes past its time limit without being finished." },
          { term: "Spend Visibility", definition: "A view, for the owner only, of what requests cost, such as a lunch order." },
          { term: "SSO", definition: "Single sign-on: staff log in with the work account they already use. Enterprise." },
          { term: "Started", definition: "The stage when work begins, usually with an ETA." },
          { term: "Webhook", definition: "An automatic message sent to another system when something happens in ZapBuzzer. Enterprise." },
          { term: "White-Label", definition: "Showing the app under your own brand instead of ZapBuzzer’s. Enterprise." },
          { term: "Workspace", definition: "Your organisation’s account in ZapBuzzer, holding staff, catalogue and requests." },
        ],
      },
      {
        type: "visual",
        visual: "request-timeline",
        heading: "The Lifecycle in One Line",
        body: "Buzzed, Accepted, Started with ETA, Delivered with optional photo, Rated 1–5★. Every request is timed from start to finish.",
      },
      {
        type: "scenario",
        heading: "A Typical Scenario in Glossary Terms",
        persona: "Om, Engineer",
        setting: "AC stuck at 16°C in a meeting room.",
        timeline: [
          { time: "14:02", event: "Om buzzes a facilities request with a destination." },
          { time: "14:03", event: "Deepak accepts; first-accept-wins makes him the owner." },
          { time: "14:17", event: "On Pro, if not fixed within the 15-minute SLA, auto-escalation moves it up the escalation chain." },
        ],
        outcome: "Six glossary terms in one fifteen-minute window.",
      },
    ],
    faqs: [
      { q: "Is an SLA a Contract?", a: "In office request management, an SLA is usually an internal deadline rather than a legal contract. In ZapBuzzer, it is the time a request should be completed within, available on Pro." },
      { q: "What Is the Difference Between Accept Time and Delivery Time?", a: "Accept time measures how fast someone claims a request. Delivery time measures how long until the job is done." },
      { q: "Is a Seat the Same as a User?", a: "Yes, a seat is a person using ZapBuzzer in your workspace." },
      { q: "Which Glossary Items Are Enterprise-Only?", a: "Enterprise is the only plan with SSO and SAML, white-labelling, a custom domain, webhooks and the REST API, a dedicated CSM and the on-prem option." },
      { q: "What Does First-Accept-Wins Mean in Plain Terms?", a: "A request goes to the whole team and the first person to tap Accept owns it. Everyone else sees it is taken, so nobody duplicates the work." },
      { q: "How Is Auto-Escalation Different From an Escalation Chain?", a: "Auto-escalation moves an overdue request to a manager without anyone chasing. An escalation chain, on Pro, is the ordered list of people it keeps moving up through if it is still not handled." },
      { q: "What Does ‘Owner’ Mean in ZapBuzzer?", a: "It has two uses: the workspace owner, who can see spend, and the staff member who has accepted and owns a particular request." },
      { q: "What Is an Internal-Request CRM?", a: "Software that manages requests from employees to service teams in the same organisation, with owners, states, timers and history, much as a sales CRM does for customers." },
    ],
    related: ["resource-hub", "resources/faq", "resources/sla-management-guide", "features/first-accept-wins", "sla", "pricing"],
    cta: { title: "See the Terms in Action", body: "Start a 14-day free trial and watch a request go from Buzzed to Rated." },
  },
  {
    path: "sitemap",
    title: "Sitemap: Every ZapBuzzer Page",
    description:
      "The complete list of ZapBuzzer pages: features, solutions by team, notifications, SLA, analytics, admin, mobile, enterprise, use cases, workflows, resources.",
    h1: "Every Page on the Site",
    eyebrow: "Sitemap",
    lead: "Looking for something specific? Every page on zapbuzzer.com is listed below, grouped by section.",
    keywords: ["zapbuzzer sitemap", "zapbuzzer pages", "site map"],
    template: "sitemap",
    sections: [
      {
        type: "prose",
        heading: "How the Site Is Organised",
        paragraphs: [
          "Product features describe what ZapBuzzer does. Solutions are organised by the team handling requests: pantry, print room, IT, facilities and courier. Notifications, SLA, analytics and admin cover how requests are delivered, timed, measured and controlled. Use cases and workflows show ZapBuzzer from the point of view of a role or a single request. Resources hold pricing, comparisons, guides and the glossary.",
        ],
      },
    ],
    faqs: [
      { q: "How Is the ZapBuzzer Site Organised?", a: "Features describe what ZapBuzzer does; Solutions are grouped by team; Notifications, SLA, analytics and admin cover delivery, timing, measurement and permissions; Use cases and workflows show roles and single requests; Resources hold pricing and guides." },
      { q: "Where Do I Find Pages for a Specific Team Like the Print Room?", a: "Under Solutions, which are organised by the team handling requests: pantry, print room, IT, facilities and courier." },
      { q: "Where Are Pricing and Plan Details Listed?", a: "In the Resources section, alongside billing and seats, comparisons, customer stories, guides and the glossary." },
      { q: "What Is the Difference Between Use Cases and Workflows on the Site?", a: "Use cases show ZapBuzzer from the point of view of a role or an office problem. Workflows follow a single request, such as a coffee or a print job, from tap to rating." },
      { q: "Which Pages Explain SLA Deadlines and Escalation?", a: "The SLA section covers deadlines and automatic escalation, and the SLA management guide in Resources explains how to set realistic deadlines for office requests." },
      { q: "Where Can I Find Quick Answers to Common Questions?", a: "The product FAQ in Resources has short answers to the questions we hear most in demos, and most pages end with FAQs on their own topic." },
      { q: "I Can’t Find the Page I Need. Who Can I Ask?", a: "Email hello@zapbuzzer.com. The team is based in Pune and replies within one business day." },
      { q: "Can I See the Product Without Reading Every Page?", a: "Yes. The read-only demo on the sign-in page lets you click through real screens, and the product tour follows one request from tap to rating." },
    ],
    related: ["resource-hub", "features", "pricing", "contact"],
  },
];
