/**
 * The single source of truth for all 200 URLs on the site.
 * [path, short navigation label]. Path "" is the homepage.
 */
export interface GroupDef {
  id: string;
  name: string;
  /** Hub page path used as breadcrumb parent for members. */
  hub: string;
  pages: [path: string, label: string][];
}

export const groups: GroupDef[] = [
  {
    id: "core",
    name: "ZapBuzzer",
    hub: "",
    pages: [
      ["", "Home"],
      ["how-it-works", "How It Works"],
      ["features", "Features"],
      ["product", "Product Overview"],
      ["why-zapbuzzer", "Why ZapBuzzer"],
      ["demo", "Book a Demo"],
      ["clients", "Clients"],
      ["pricing", "Pricing"],
      ["mobile-app", "Mobile App"],
      ["enterprise", "Enterprise"],
      ["about", "About"],
      ["contact", "Contact"],
      ["sign-in", "Sign In"],
      ["sign-up", "Sign Up"],
      ["free-trial", "Free Trial"],
    ],
  },
  {
    id: "features",
    name: "Product Features",
    hub: "features",
    pages: [
      ["features/one-tap-requests", "One-Tap Requests"],
      ["features/request-management", "Request Management"],
      ["features/request-catalog", "Request Catalog"],
      ["features/request-routing", "Request Routing"],
      ["features/first-accept-wins", "First-Accept-Wins"],
      ["features/request-assignment", "Request Assignment"],
      ["features/request-tracking", "Request Tracking"],
      ["features/real-time-updates", "Real-Time Updates"],
      ["features/request-timers", "Request Timers"],
      ["features/eta-tracking", "ETA Tracking"],
      ["features/request-status", "Request Status"],
      ["features/delivery-confirmation", "Delivery Confirmation"],
      ["features/request-ratings", "Request Ratings"],
      ["features/request-history", "Request History"],
      ["features/request-reports", "Request Reports"],
    ],
  },
  {
    id: "pantry",
    name: "Pantry",
    hub: "solutions/pantry",
    pages: [
      ["solutions/pantry", "Pantry Management"],
      ["solutions/pantry/catalog", "Pantry Catalog"],
      ["solutions/pantry/coffee-requests", "Coffee Requests"],
      ["solutions/pantry/tea-requests", "Tea Requests"],
      ["solutions/pantry/snacks-requests", "Snacks Requests"],
      ["solutions/pantry/lunch-requests", "Lunch Requests"],
      ["solutions/pantry/office-refreshments", "Office Refreshments"],
      ["solutions/pantry/ordering-workflow", "Pantry Ordering Workflow"],
      ["solutions/pantry/staff-management", "Pantry Staff Management"],
      ["solutions/pantry/request-tracking", "Pantry Request Tracking"],
    ],
  },
  {
    id: "print",
    name: "Print Room",
    hub: "solutions/print-room",
    pages: [
      ["solutions/print-room", "Print Room"],
      ["solutions/print-room/print-requests", "Print Requests"],
      ["solutions/print-room/pdf-print-requests", "PDF Print Requests"],
      ["solutions/print-room/color-printing", "Color Printing"],
      ["solutions/print-room/copy-management", "Copy Management"],
      ["solutions/print-room/print-queue", "Print Queue"],
      ["solutions/print-room/request-tracking", "Print Request Tracking"],
      ["solutions/print-room/staff-workflow", "Print Room Staff Workflow"],
      ["solutions/print-room/sla", "Print SLA Management"],
      ["solutions/print-room/analytics", "Print Analytics"],
    ],
  },
  {
    id: "it",
    name: "IT Support",
    hub: "solutions/it-support",
    pages: [
      ["solutions/it-support", "IT Support"],
      ["solutions/it-support/request-management", "IT Request Management"],
      ["solutions/it-support/projector-support", "Projector Support"],
      ["solutions/it-support/hdmi-requests", "HDMI Requests"],
      ["solutions/it-support/meeting-room-support", "Meeting Room IT Support"],
      ["solutions/it-support/hardware-requests", "Hardware Requests"],
      ["solutions/it-support/software-requests", "Software Support Requests"],
      ["solutions/it-support/ticket-routing", "IT Ticket Routing"],
      ["solutions/it-support/sla", "IT SLA Management"],
      ["solutions/it-support/analytics", "IT Support Analytics"],
    ],
  },
  {
    id: "facilities",
    name: "Facilities",
    hub: "solutions/facilities",
    pages: [
      ["solutions/facilities", "Facilities Management"],
      ["solutions/facilities/requests", "Facilities Requests"],
      ["solutions/facilities/ac-requests", "AC Requests"],
      ["solutions/facilities/conference-room-issues", "Conference Room Issues"],
      ["solutions/facilities/maintenance-requests", "Maintenance Requests"],
      ["solutions/facilities/office-equipment", "Office Equipment Requests"],
      ["solutions/facilities/routing", "Facilities Routing"],
      ["solutions/facilities/escalation", "Facilities Escalation"],
      ["solutions/facilities/sla", "Facilities SLA"],
      ["solutions/facilities/analytics", "Facilities Analytics"],
    ],
  },
  {
    id: "courier",
    name: "Courier & Reception",
    hub: "solutions/courier",
    pages: [
      ["solutions/courier", "Courier Management"],
      ["solutions/courier/pickup", "Courier Pickup"],
      ["solutions/courier/mailroom", "Mailroom Requests"],
      ["solutions/courier/reception", "Reception Requests"],
      ["solutions/courier/delivery-requests", "Delivery Requests"],
      ["solutions/courier/incoming-workflow", "Incoming Courier Workflow"],
      ["solutions/courier/outgoing-workflow", "Outgoing Courier Workflow"],
      ["solutions/courier/tracking", "Courier Tracking"],
      ["solutions/courier/reception-workflow", "Reception Workflow"],
      ["solutions/courier/mailroom-analytics", "Mailroom Analytics"],
    ],
  },
  {
    id: "notifications",
    name: "Notifications",
    hub: "notifications",
    pages: [
      ["notifications", "Notification Management"],
      ["notifications/multi-channel", "Multi-Channel Notifications"],
      ["notifications/telegram", "Telegram Integration"],
      ["notifications/whatsapp", "WhatsApp Notifications"],
      ["notifications/email", "Email Notifications"],
      ["notifications/push", "Mobile Push Notifications"],
      ["notifications/routing", "Notification Routing"],
      ["notifications/escalation", "Notification Escalation"],
      ["notifications/preferences", "Notification Preferences"],
      ["notifications/workflow", "Notification Workflow"],
    ],
  },
  {
    id: "sla",
    name: "SLA & Escalation",
    hub: "sla",
    pages: [
      ["sla", "SLA Management"],
      ["sla/timers", "SLA Timers"],
      ["sla/tracking", "SLA Tracking"],
      ["sla/breach-detection", "SLA Breach Detection"],
      ["sla/automatic-escalation", "Automatic Escalation"],
      ["sla/manager-escalation", "Manager Escalation"],
      ["sla/escalation-chains", "Escalation Chains"],
      ["sla/overdue-requests", "Overdue Requests"],
      ["sla/reporting", "SLA Reporting"],
      ["sla/analytics", "SLA Analytics"],
    ],
  },
  {
    id: "analytics",
    name: "Analytics",
    hub: "analytics",
    pages: [
      ["analytics", "Analytics Overview"],
      ["analytics/requests", "Request Analytics"],
      ["analytics/staff", "Staff Analytics"],
      ["analytics/team-performance", "Team Performance"],
      ["analytics/response-time", "Response Time Analytics"],
      ["analytics/acceptance-time", "Acceptance Time Analytics"],
      ["analytics/delivery-time", "Delivery Time Analytics"],
      ["analytics/on-time-performance", "On-Time Performance"],
      ["analytics/ratings", "Rating Analytics"],
      ["analytics/office-activity", "Office Activity Analytics"],
    ],
  },
  {
    id: "admin",
    name: "Administration",
    hub: "admin",
    pages: [
      ["admin", "Admin Dashboard"],
      ["admin/roles-and-permissions", "Roles & Permissions"],
      ["admin/owner-dashboard", "Owner Dashboard"],
      ["admin/staff-dashboard", "Staff Dashboard"],
      ["admin/employee-dashboard", "Employee Dashboard"],
      ["admin/manager-dashboard", "Manager Dashboard"],
      ["admin/team-management", "Team Management"],
      ["admin/staff-assignment", "Staff Assignment"],
      ["admin/audit-logs", "Audit Logs"],
      ["admin/spend-visibility", "Spend Visibility"],
    ],
  },
  {
    id: "mobile",
    name: "Mobile App",
    hub: "mobile-app",
    pages: [
      ["mobile-app/android", "Android App"],
      ["mobile-app/requests", "Mobile Requests"],
      ["mobile-app/notifications", "Mobile Notifications"],
      ["mobile-app/staff-assignment", "Mobile Staff Assignment"],
      ["mobile-app/request-tracking", "Mobile Request Tracking"],
      ["mobile-app/request-acceptance", "Mobile Request Acceptance"],
      ["mobile-app/delivery-tracking", "Mobile Delivery Tracking"],
      ["mobile-app/ratings", "Mobile Ratings"],
      ["mobile-app/staff-workflow", "Mobile Staff Workflow"],
      ["mobile-app/office-management", "Mobile Office Management"],
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    hub: "enterprise",
    pages: [
      ["enterprise/rollout", "Enterprise Rollout"],
      ["enterprise/security", "Enterprise Security"],
      ["enterprise/administration", "Enterprise Administration"],
      ["enterprise/analytics", "Enterprise Analytics"],
      ["enterprise/multi-location", "Multi-Location"],
      ["enterprise/user-management", "Enterprise User Management"],
      ["enterprise/permissions", "Enterprise Permissions"],
      ["enterprise/audit-logs", "Enterprise Audit Logs"],
      ["enterprise/reporting", "Enterprise Reporting"],
      ["enterprise/support", "Enterprise Support"],
    ],
  },
  {
    id: "integrations",
    name: "Integrations & API",
    hub: "integrations",
    pages: [
      ["integrations", "Integrations"],
      ["developers/api", "API Overview"],
      ["developers/rest-api", "REST API"],
      ["developers/authentication", "API Authentication"],
      ["developers/api-requests", "API Requests"],
      ["developers/webhooks", "Webhooks"],
      ["developers/webhook-events", "Webhook Events"],
      ["integrations/custom-domain", "Custom Domain"],
      ["integrations/white-label", "White Label"],
      ["integrations/sso-saml", "SSO & SAML"],
    ],
  },
  {
    id: "roles",
    name: "Use Cases by Role",
    hub: "use-cases",
    pages: [
      ["use-cases/ceo", "CEO"],
      ["use-cases/founder", "Founder"],
      ["use-cases/office-manager", "Office Manager"],
      ["use-cases/hr", "HR Team"],
      ["use-cases/admin-team", "Admin Team"],
      ["use-cases/it-manager", "IT Manager"],
      ["use-cases/facilities-manager", "Facilities Manager"],
      ["use-cases/reception", "Reception Team"],
      ["use-cases/sales", "Sales Team"],
      ["use-cases/operations", "Operations Team"],
    ],
  },
  {
    id: "problems",
    name: "Office Problems We Solve",
    hub: "use-cases",
    pages: [
      ["use-cases/stop-office-chase-calls", "Stop Chase Calls"],
      ["use-cases/reduce-whatsapp-requests", "Reduce WhatsApp Requests"],
      ["use-cases/reduce-phone-calls", "Reduce Phone Calls"],
      ["use-cases/prevent-lost-requests", "Prevent Lost Requests"],
      ["use-cases/improve-response-time", "Improve Response Time"],
      ["use-cases/track-office-requests", "Track Office Requests"],
      ["use-cases/staff-accountability", "Staff Accountability"],
      ["use-cases/sla-compliance", "SLA Compliance"],
      ["use-cases/pantry-operations", "Better Pantry Operations"],
      ["use-cases/facilities-operations", "Better Facilities Operations"],
    ],
  },
  {
    id: "workflows",
    name: "Workflows",
    hub: "workflows",
    pages: [
      ["workflows/coffee-request", "Coffee Request"],
      ["workflows/print-request", "Print Request"],
      ["workflows/it-support", "IT Support"],
      ["workflows/ac-issue", "AC Issue"],
      ["workflows/projector-request", "Projector Request"],
      ["workflows/hdmi-request", "HDMI Request"],
      ["workflows/courier-pickup", "Courier Pickup"],
      ["workflows/lunch-request", "Lunch Request"],
      ["workflows/emergency-summon", "Emergency Summon"],
      ["workflows", "Office Service Workflow"],
    ],
  },
  {
    id: "resources",
    name: "Resources",
    hub: "resources",
    pages: [
      ["resources", "Resources"],
      ["pricing/free", "Free Plan"],
      ["pricing/pro", "Pro Plan"],
      ["pricing/enterprise", "Enterprise Plan"],
      ["pricing/billing", "Billing & Seats"],
      ["resources/product-tour", "Product Tour"],
      ["resources/faq", "Product FAQ"],
      ["compare", "Feature Comparison"],
      ["compare/manual-requests", "vs Manual Requests"],
      ["compare/whatsapp", "vs WhatsApp"],
      ["compare/phone-calls", "vs Phone Calls"],
      ["compare/helpdesk", "vs Traditional Helpdesk"],
      ["customers", "Customer Stories"],
      ["resources/office-efficiency-guide", "Office Efficiency Guide"],
      ["resources/internal-request-management-guide", "Internal Request Management Guide"],
      ["resources/workplace-operations-guide", "Workplace Operations Guide"],
      ["resources/sla-management-guide", "SLA Management Guide"],
      ["resources/office-automation-guide", "Office Automation Guide"],
      ["resources/glossary", "Glossary"],
      ["sitemap", "Sitemap"],
    ],
  },
];

export const allPaths = groups.flatMap((g) => g.pages.map(([p]) => p));

export const labelFor = (path: string) =>
  groups.flatMap((g) => g.pages).find(([p]) => p === path)?.[1] ?? path;

export const groupOf = (path: string) =>
  groups.find((g) => g.pages.some(([p]) => p === path));
