/**
 * The single source of truth for all 200 URLs on the site.
 * [path, short navigation label]. Path "" is the homepage.
 */
export interface GroupDef {
  id: string;
  name: string;
  /** Hub page path used as breadcrumb parent for members. */
  hub: string;
  pages: [path: string, label: string][];
}

export const groups: GroupDef[] = [
  {
    id: "core",
    name: "ZapBuzzer",
    hub: "",
    pages: [
      ["", "Home"],
      ["how-it-works", "How It Works"],
      ["features", "Features"],
      ["overview", "Overview"],
      ["why-zapbuzzer", "Why ZapBuzzer"],
      ["book-a-demo", "Book a Demo"],
      ["clients", "Clients"],
      ["pricing", "Pricing"],
      ["mobile-app", "Mobile App"],
      ["enterprise", "Enterprise"],
      ["about-us", "About Us"],
      ["contact-us", "Contact Us"],
      ["sign-in", "Sign In"],
      ["sign-up", "Sign Up"],
      ["free-trial", "Free Trial"],
    ],
  },
  {
    id: "features",
    name: "Product Features",
    hub: "features",
    pages: [
      ["features/one-tap-requests", "One-Tap Requests"],
      ["features/request-management", "Request Management"],
      ["features/request-catalog", "Request Catalog"],
      ["features/request-routing", "Request Routing"],
      ["features/first-accept-wins", "First-Accept-Wins"],
      ["features/request-assignment", "Request Assignment"],
      ["features/request-tracking", "Request Tracking"],
      ["features/real-time-updates", "Real-Time Updates"],
      ["features/request-timers", "Request Timers"],
      ["features/eta-tracking", "ETA Tracking"],
      ["features/request-status", "Request Status"],
      ["features/delivery-confirmation", "Delivery Confirmation"],
      ["features/request-ratings", "Request Ratings"],
      ["features/request-history", "Request History"],
      ["features/request-reports", "Request Reports"],
    ],
  },
  {
    id: "pantry",
    name: "Pantry",
    hub: "solutions/pantry",
    pages: [
      ["solutions/pantry", "Pantry"],
      ["solutions/pantry/pantry-catalog", "Pantry Catalog"],
      ["solutions/pantry/coffee-requests", "Coffee Requests"],
      ["solutions/pantry/tea-requests", "Tea Requests"],
      ["solutions/pantry/snacks-requests", "Snacks Requests"],
      ["solutions/pantry/lunch-requests", "Lunch Requests"],
      ["solutions/pantry/office-refreshments", "Office Refreshments"],
      ["solutions/pantry/pantry-ordering-workflow", "Pantry Ordering Workflow"],
      ["solutions/pantry/pantry-staff-management", "Pantry Staff Management"],
      ["solutions/pantry/pantry-request-tracking", "Pantry Request Tracking"],
    ],
  },
  {
    id: "print",
    name: "Print Room",
    hub: "solutions/print-room",
    pages: [
      ["solutions/print-room", "Print Room"],
      ["solutions/print-room/print-requests", "Print Requests"],
      ["solutions/print-room/pdf-print-requests", "PDF Print Requests"],
      ["solutions/print-room/color-printing", "Color Printing"],
      ["solutions/print-room/copy-management", "Copy Management"],
      ["solutions/print-room/print-queue", "Print Queue"],
      ["solutions/print-room/print-request-tracking", "Print Request Tracking"],
      ["solutions/print-room/print-room-staff-workflow", "Print Room Staff Workflow"],
      ["solutions/print-room/print-sla-management", "Print SLA Management"],
      ["solutions/print-room/print-analytics", "Print Analytics"],
    ],
  },
  {
    id: "it",
    name: "IT Support",
    hub: "solutions/it-support",
    pages: [
      ["solutions/it-support", "IT Support"],
      ["solutions/it-support/it-request-management", "IT Request Management"],
      ["solutions/it-support/projector-support", "Projector Support"],
      ["solutions/it-support/hdmi-requests", "HDMI Requests"],
      ["solutions/it-support/meeting-room-it-support", "Meeting Room IT Support"],
      ["solutions/it-support/hardware-requests", "Hardware Requests"],
      ["solutions/it-support/software-support-requests", "Software Support Requests"],
      ["solutions/it-support/it-ticket-routing", "IT Ticket Routing"],
      ["solutions/it-support/it-sla-management", "IT SLA Management"],
      ["solutions/it-support/it-support-analytics", "IT Support Analytics"],
    ],
  },
  {
    id: "facilities",
    name: "Facilities",
    hub: "solutions/facilities",
    pages: [
      ["solutions/facilities", "Facilities"],
      ["solutions/facilities/facilities-requests", "Facilities Requests"],
      ["solutions/facilities/ac-requests", "AC Requests"],
      ["solutions/facilities/conference-room-issues", "Conference Room Issues"],
      ["solutions/facilities/maintenance-requests", "Maintenance Requests"],
      ["solutions/facilities/office-equipment-requests", "Office Equipment Requests"],
      ["solutions/facilities/facilities-routing", "Facilities Routing"],
      ["solutions/facilities/facilities-escalation", "Facilities Escalation"],
      ["solutions/facilities/facilities-sla", "Facilities SLA"],
      ["solutions/facilities/facilities-analytics", "Facilities Analytics"],
    ],
  },
  {
    id: "courier",
    name: "Courier & Reception",
    hub: "solutions/courier-and-reception",
    pages: [
      ["solutions/courier-and-reception", "Courier & Reception"],
      ["solutions/courier-and-reception/courier-pickup", "Courier Pickup"],
      ["solutions/courier-and-reception/mailroom-requests", "Mailroom Requests"],
      ["solutions/courier-and-reception/reception-requests", "Reception Requests"],
      ["solutions/courier-and-reception/delivery-requests", "Delivery Requests"],
      ["solutions/courier-and-reception/incoming-courier-workflow", "Incoming Courier Workflow"],
      ["solutions/courier-and-reception/outgoing-courier-workflow", "Outgoing Courier Workflow"],
      ["solutions/courier-and-reception/courier-tracking", "Courier Tracking"],
      ["solutions/courier-and-reception/reception-workflow", "Reception Workflow"],
      ["solutions/courier-and-reception/mailroom-analytics", "Mailroom Analytics"],
    ],
  },
  {
    id: "notifications",
    name: "Notifications",
    hub: "notifications",
    pages: [
      ["notifications", "Notifications"],
      ["notifications/multi-channel-notifications", "Multi-Channel Notifications"],
      ["notifications/telegram-integration", "Telegram Integration"],
      ["notifications/whatsapp-notifications", "WhatsApp Notifications"],
      ["notifications/email-notifications", "Email Notifications"],
      ["notifications/mobile-push-notifications", "Mobile Push Notifications"],
      ["notifications/notification-routing", "Notification Routing"],
      ["notifications/notification-escalation", "Notification Escalation"],
      ["notifications/notification-preferences", "Notification Preferences"],
      ["notifications/notification-workflow", "Notification Workflow"],
    ],
  },
  {
    id: "sla",
    name: "SLA & Escalation",
    hub: "sla-and-escalation",
    pages: [
      ["sla-and-escalation", "SLA & Escalation"],
      ["sla-and-escalation/sla-timers", "SLA Timers"],
      ["sla-and-escalation/sla-tracking", "SLA Tracking"],
      ["sla-and-escalation/sla-breach-detection", "SLA Breach Detection"],
      ["sla-and-escalation/automatic-escalation", "Automatic Escalation"],
      ["sla-and-escalation/manager-escalation", "Manager Escalation"],
      ["sla-and-escalation/escalation-chains", "Escalation Chains"],
      ["sla-and-escalation/overdue-requests", "Overdue Requests"],
      ["sla-and-escalation/sla-reporting", "SLA Reporting"],
      ["sla-and-escalation/sla-analytics", "SLA Analytics"],
    ],
  },
  {
    id: "analytics",
    name: "Analytics",
    hub: "analytics",
    pages: [
      ["analytics", "Analytics"],
      ["analytics/request-analytics", "Request Analytics"],
      ["analytics/staff-analytics", "Staff Analytics"],
      ["analytics/team-performance", "Team Performance"],
      ["analytics/response-time-analytics", "Response Time Analytics"],
      ["analytics/acceptance-time-analytics", "Acceptance Time Analytics"],
      ["analytics/delivery-time-analytics", "Delivery Time Analytics"],
      ["analytics/on-time-performance", "On-Time Performance"],
      ["analytics/rating-analytics", "Rating Analytics"],
      ["analytics/office-activity-analytics", "Office Activity Analytics"],
    ],
  },
  {
    id: "admin",
    name: "Administration",
    hub: "administration",
    pages: [
      ["administration", "Administration"],
      ["administration/roles-and-permissions", "Roles & Permissions"],
      ["administration/owner-dashboard", "Owner Dashboard"],
      ["administration/staff-dashboard", "Staff Dashboard"],
      ["administration/employee-dashboard", "Employee Dashboard"],
      ["administration/manager-dashboard", "Manager Dashboard"],
      ["administration/team-management", "Team Management"],
      ["administration/staff-assignment", "Staff Assignment"],
      ["administration/audit-logs", "Audit Logs"],
      ["administration/spend-visibility", "Spend Visibility"],
    ],
  },
  {
    id: "mobile",
    name: "Mobile App",
    hub: "mobile-app",
    pages: [
      ["mobile-app/android-app", "Android App"],
      ["mobile-app/mobile-requests", "Mobile Requests"],
      ["mobile-app/mobile-notifications", "Mobile Notifications"],
      ["mobile-app/mobile-staff-assignment", "Mobile Staff Assignment"],
      ["mobile-app/mobile-request-tracking", "Mobile Request Tracking"],
      ["mobile-app/mobile-request-acceptance", "Mobile Request Acceptance"],
      ["mobile-app/mobile-delivery-tracking", "Mobile Delivery Tracking"],
      ["mobile-app/mobile-ratings", "Mobile Ratings"],
      ["mobile-app/mobile-staff-workflow", "Mobile Staff Workflow"],
      ["mobile-app/mobile-office-management", "Mobile Office Management"],
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    hub: "enterprise",
    pages: [
      ["enterprise/enterprise-rollout", "Enterprise Rollout"],
      ["enterprise/security", "Security"],
      ["enterprise/enterprise-administration", "Enterprise Administration"],
      ["enterprise/enterprise-analytics", "Enterprise Analytics"],
      ["enterprise/multi-location", "Multi-Location"],
      ["enterprise/enterprise-user-management", "Enterprise User Management"],
      ["enterprise/enterprise-permissions", "Enterprise Permissions"],
      ["enterprise/enterprise-audit-logs", "Enterprise Audit Logs"],
      ["enterprise/enterprise-reporting", "Enterprise Reporting"],
      ["enterprise/enterprise-support", "Enterprise Support"],
    ],
  },
  {
    id: "integrations",
    name: "Integrations & API",
    hub: "integrations",
    pages: [
      ["integrations", "Integrations"],
      ["developers/api-documentation", "API Documentation"],
      ["developers/rest-api", "REST API"],
      ["developers/api-authentication", "API Authentication"],
      ["developers/api-requests", "API Requests"],
      ["developers/webhooks", "Webhooks"],
      ["developers/webhook-events", "Webhook Events"],
      ["integrations/custom-domain", "Custom Domain"],
      ["integrations/white-label", "White Label"],
      ["integrations/sso-and-saml", "SSO & SAML"],
    ],
  },
  {
    id: "roles",
    name: "Use Cases by Role",
    hub: "use-cases",
    pages: [
      ["use-cases/ceo", "CEO"],
      ["use-cases/founder", "Founder"],
      ["use-cases/office-manager", "Office Manager"],
      ["use-cases/hr-team", "HR Team"],
      ["use-cases/admin-team", "Admin Team"],
      ["use-cases/it-manager", "IT Manager"],
      ["use-cases/facilities-manager", "Facilities Manager"],
      ["use-cases/reception-team", "Reception Team"],
      ["use-cases/sales-team", "Sales Team"],
      ["use-cases/operations-team", "Operations Team"],
    ],
  },
  {
    id: "problems",
    name: "Office Problems We Solve",
    hub: "use-cases",
    pages: [
      ["use-cases/stop-chase-calls", "Stop Chase Calls"],
      ["use-cases/reduce-whatsapp-requests", "Reduce WhatsApp Requests"],
      ["use-cases/reduce-phone-calls", "Reduce Phone Calls"],
      ["use-cases/prevent-lost-requests", "Prevent Lost Requests"],
      ["use-cases/improve-response-time", "Improve Response Time"],
      ["use-cases/track-office-requests", "Track Office Requests"],
      ["use-cases/staff-accountability", "Staff Accountability"],
      ["use-cases/sla-compliance", "SLA Compliance"],
      ["use-cases/better-pantry-operations", "Better Pantry Operations"],
      ["use-cases/better-facilities-operations", "Better Facilities Operations"],
    ],
  },
  {
    id: "workflows",
    name: "Workflows",
    hub: "workflows",
    pages: [
      ["workflows/coffee-request", "Coffee Request"],
      ["workflows/print-request", "Print Request"],
      ["workflows/it-support", "IT Support"],
      ["workflows/ac-issue", "AC Issue"],
      ["workflows/projector-request", "Projector Request"],
      ["workflows/hdmi-request", "HDMI Request"],
      ["workflows/courier-pickup", "Courier Pickup"],
      ["workflows/lunch-request", "Lunch Request"],
      ["workflows/emergency-summon", "Emergency Summon"],
      ["workflows", "Workflows"],
    ],
  },
  {
    id: "resources",
    name: "Resources",
    hub: "resource-hub",
    pages: [
      ["resource-hub", "Resource Hub"],
      ["pricing/free-plan", "Free Plan"],
      ["pricing/pro-plan", "Pro Plan"],
      ["pricing/enterprise-plan", "Enterprise Plan"],
      ["pricing/billing-and-seats", "Billing & Seats"],
      ["resource-hub/product-tour", "Product Tour"],
      ["resource-hub/faq", "FAQ"],
      ["feature-comparison", "Feature Comparison"],
      ["feature-comparison/vs-manual-requests", "Vs Manual Requests"],
      ["feature-comparison/vs-whatsapp", "Vs WhatsApp"],
      ["feature-comparison/vs-phone-calls", "Vs Phone Calls"],
      ["feature-comparison/vs-helpdesk", "Vs Helpdesk"],
      ["customer-stories", "Customer Stories"],
      ["resource-hub/office-efficiency-guide", "Office Efficiency Guide"],
      ["resource-hub/internal-request-management-guide", "Internal Request Management Guide"],
      ["resource-hub/workplace-operations-guide", "Workplace Operations Guide"],
      ["resource-hub/sla-management-guide", "SLA Management Guide"],
      ["resource-hub/office-automation-guide", "Office Automation Guide"],
      ["resource-hub/glossary", "Glossary"],
      ["sitemap", "Sitemap"],
    ],
  },
];

export const allPaths = groups.flatMap((g) => g.pages.map(([p]) => p));

export const labelFor = (path: string) =>
  groups.flatMap((g) => g.pages).find(([p]) => p === path)?.[1] ?? path;

export const groupOf = (path: string) =>
  groups.find((g) => g.pages.some(([p]) => p === path));
