import { site } from "@/lib/site";

/** Page FAQs for standalone (non-registry) pages. Exactly 8 per page; questions must be unique site-wide. */
export const standaloneFaqs: Record<string, { q: string; a: string }[]> = {
  "/": [
    { q: "In One Sentence, What Does ZapBuzzer Do?", a: "It lets staff ask for everyday office help, such as refreshments, printing, IT, facilities or courier pickups, with one tap, and gives every request one owner, a deadline and a rating, so nothing depends on someone remembering a phone call." },
    { q: "What Happens After an Employee Taps Buzz?", a: "The request goes to the right team, such as the pantry, print room or IT desk, with the item, a note and a destination like the boss cabin. Staff accept it, start it with an ETA and mark it delivered, and the requester rates the work from one to five stars." },
    { q: "Which Channels Do ZapBuzzer Alerts Arrive On?", a: "Alerts go out on the app, Telegram, WhatsApp and email at the same time, and they repeat until someone accepts. The Free plan includes email notifications; Telegram and WhatsApp pings come with Pro." },
    { q: "Why Not Just Keep Using a WhatsApp Group?", a: "A message in a group belongs to nobody. There’s no owner, no deadline and no history you can measure. In ZapBuzzer each request is claimed by exactly one person, timed, escalated if it runs late and counted in your reports. On Pro, staff can still receive the alerts on WhatsApp and Telegram." },
    { q: "What Does First-Accept-Wins Mean for My Team?", a: "Each request is sent to the whole team and the first free person to tap Accept owns it. The requester sees their name, photo and ETA, so there is no “I thought you’d do it” and no duplicate trips." },
    { q: "What Stops a Request From Being Forgotten?", a: "Every request has a deadline. If it runs late, it is passed up to a manager automatically (escalation), and Pro adds a full escalation chain. Analytics and scorecards then show response times and ratings for each person." },
    { q: "How Is It Priced, and Is There a Free Trial?", a: "The Free plan covers one location and up to 10 staff. Pro costs ₹99 per seat per month and adds unlimited staff, multiple locations, Telegram and WhatsApp alerts, escalation chains, analytics and audit logs. Enterprise is custom-priced. There is a 14-day free trial with no credit card." },
    { q: "How Long Does Setup Take, and Is There a Mobile App?", a: "Most offices are up and running in an afternoon, with no setup fees or consultant. Staff use the web app or the Android app, which rings through even when the phone is on silent or locked." },
  ],
  blog: [
    { q: "What Does the ZapBuzzer Blog Cover?", a: "Practical writing on office requests: how pantry, print, IT, facilities and front-desk teams work, how to set up SLAs and escalation, and how ZapBuzzer handles each step." },
    { q: "How Are Blog Articles Organised by Topic?", a: "Articles sit in four categories: Office operations, Playbooks, Product explainers, and People & culture. The “Browse by topic” cards show each category with its article count." },
    { q: "How Do I Search the Blog for a Specific Topic?", a: "Use the search box under “All articles” and type a word such as escalation, pantry or print. You can combine the search with a category filter to narrow the list further." },
    { q: "Can I Share a Filtered List of Blog Articles?", a: "Yes. The search and category filter are saved in the page address, so copying the URL shares exactly the filtered view you are looking at." },
    { q: "Which Blog Article Should I Read First?", a: "Start with the featured article at the top of the page, under “Start here”. Two further picks sit beside it, each with its category and reading time." },
    { q: "What Are the Playbooks Articles on the Blog?", a: "Playbooks are step-by-step setups you can copy into your own office. Product explainers are different: they describe how one part of ZapBuzzer works and why." },
    { q: "Do Blog Articles Show How Long They Take to Read?", a: "Yes. Each article card shows an estimated reading time in minutes, and the featured article also shows its publication date." },
    { q: "How Can I Try the Ideas From the Blog in My Own Office?", a: "Open a free workspace for one floor and up to 10 staff, or try Pro free for 14 days. Neither needs a credit card or a setup call." },
  ],
  careers: [
    { q: "Are There Any Open Positions Right Now?", a: "Yes. The current openings are Sales Executive, Software Developer Coordinator, Email Marketing Executive, Business Development Executive and Prompt Engineer, listed under Open Positions on this page. You can also send a general application and we will keep it in mind." },
    { q: "Where Would I Be Working If I Joined ZapBuzzer?", a: "ZapBuzzer is based in Pune, Maharashtra, India. Location and remote-work details are given with each role when it is posted." },
    { q: "What Should I Include in a General Application?", a: "Your name, the area you want to work in, a link to your CV or LinkedIn profile, and a few lines on why internal office requests interest you. Links to work you are proud of help most." },
    { q: "Do You Offer Internships?", a: "Internships are not currently listed. If one opens, it will be posted here like any other role." },
    { q: "Can I Attach My CV?", a: "The form opens your email app with your details pre-filled, so you can attach a CV there before sending. A link to an online CV or portfolio works just as well." },
    { q: "Which Areas of Work Can I Apply to at ZapBuzzer?", a: "Engineering, product and design, customer success, sales and partnerships, marketing and content, and operations. These describe the kinds of work it takes to run ZapBuzzer, not open roles, and you can also choose “Not sure yet” on the form." },
    { q: "What Are the Steps in the ZapBuzzer Hiring Process?", a: "You apply or introduce yourself, a person reads your application, and if there is a possible fit we set up a first conversation. Depending on the role, there is then a practical step, followed by a clear decision either way." },
    { q: "How Soon Will I Hear Back About My Application?", a: `We aim to reply within one business day to every message. You can also write directly to ${site.email} with “Careers” in the subject line.` },
  ],
  media: [
    { q: "Who Should Journalists Contact?", a: `Email ${site.email} with “Media” in the subject line, or use the media enquiry form on this page. We aim to reply within one business day.` },
    { q: "Where Can I Download the Logo and Brand Assets?", a: "Logos, brand colours, approved descriptions and usage guidelines are on the Press Kit page. Please use those files rather than screenshots of the website." },
    { q: "Can I Quote Figures About ZapBuzzer?", a: "Yes, the figures on this page are the ones ZapBuzzer publishes on its website. Please quote them as stated, including the context, for example that the pilot results are from pilot offices in their first month." },
    { q: "Can You Put Me in Touch With a Customer?", a: "Ask in your enquiry. Customer introductions depend on the customer’s permission, so we cannot promise one, but we will ask on your behalf." },
    { q: "Can I Try the Product for a Story?", a: "Yes. A read-only demo is available without signing up, and the 14-day trial needs no credit card. If you need a guided walkthrough, mention it in your enquiry." },
    { q: "What Kinds of Media Requests Can I Send?", a: "The enquiry form covers interview requests, a comment or quote, a product walkthrough, a fact check or anything else. Add your publication, your deadline and what your story is about so we can give you what you need." },
    { q: "Which Story Angles Can ZapBuzzer Speak To?", a: "The cost of office phone tag, internal requests as a CRM problem, fair credit for support staff, and why first-accept-wins beats assigning requests by rota." },
    { q: "Has ZapBuzzer Been Covered in the Press?", a: "We do not list any press coverage yet. If you write about ZapBuzzer, send us the link once it is published and we will add it to this page." },
  ],
  vendors: [
    { q: "Does ZapBuzzer Have a Formal Partner Programme?", a: "Not yet. We do not run a published partner programme with tiers, margins or certification. Each conversation is handled individually, and we will tell you plainly what we can offer." },
    { q: "Can I Resell ZapBuzzer to My Clients?", a: "Resale terms are not published. If reselling is what you have in mind, say so in your enquiry and we will discuss whether and how it could work for your clients." },
    { q: "Can ZapBuzzer Run Under My Company’s Brand?", a: "White-label and custom domain are part of the Enterprise plan. Pricing for Enterprise is custom, so it is best discussed on a call once we understand your setup." },
    { q: "I Supply Coffee, Snacks or Printing. Do I Need to Use ZapBuzzer?", a: "No. Offices use ZapBuzzer to send requests to whoever handles them, which is often their own staff. If your team serves an office directly, joining that office’s workspace is the office’s decision." },
    { q: "Is There an API I Can Build Against?", a: "A REST API and webhooks are available on the Enterprise plan. Public API documentation is not published in detail, so tell us your use case and we will tell you what is possible." },
    { q: "How Quickly Will I Hear Back?", a: "We aim to reply within one business day. If the enquiry needs a call, we will suggest times in that first reply." },
    { q: "Which Kinds of Vendors and Partners Does ZapBuzzer Work With?", a: "Facility management companies, office service providers such as pantry, print, courier and IT field-support firms, implementation and workplace consultants, and technology or integration partners. If you do not fit these, write to us anyway." },
    { q: "Can I Call Myself a ZapBuzzer Partner After an Enquiry?", a: "No. Please do not present yourself as an official ZapBuzzer partner unless that has been agreed with us in writing, and follow the brand guidelines on the Press Kit page if you mention ZapBuzzer publicly." },
  ],
  "press-kit": [
    { q: "Which Brand Files Can I Download From the Press Kit?", a: "The ZapBuzzer app icon as a 1024 × 1024 PNG with a transparent background, a text file of approved descriptions, and a text file of brand colours and typefaces." },
    { q: "Is There a Vector or Horizontal ZapBuzzer Logo?", a: "Not yet. Only the PNG app icon is available; a vector version and a horizontal wordmark lockup have not been published. On the website the icon sits beside the name “ZapBuzzer” set in bold text." },
    { q: "How Should I Write the Company Name?", a: "Write it as ZapBuzzer: one word, capital Z and capital B. Avoid Zap Buzzer, Zapbuzzer or ZAPBUZZER in running text." },
    { q: "What Are ZapBuzzer’s Brand Colours?", a: "The logo uses Logo blue #0E3E9F, Bell orange #FB800A and Bell off-white #F0F4F7. Website interface colours, including Indigo accent #5C5FE6, are listed on this page with hex and RGB values you can copy." },
    { q: "Which Typefaces Does the ZapBuzzer Website Use?", a: "Headings are set in Poppins and body text in Inter. Both are listed in the brand colours and type download." },
    { q: "How May I Use the ZapBuzzer App Icon?", a: "Use it at its original proportions with clear space of at least a quarter of its width, on plain light or dark backgrounds. Do not stretch, rotate, recolour, crop or add effects to it." },
    { q: "Can I Write My Own Description of ZapBuzzer?", a: "Please use the approved tagline, one-line and short descriptions as written, or quote facts exactly as published on zapbuzzer.com. Do not add figures, customer names or features that are not on the website." },
    { q: "Are Product Screenshots or Team Photos Available for Press?", a: `Not yet. Approved app screenshots and founder or team photos have not been published. If you need one for a story, email ${site.email} or use the form on the Media page.` },
  ],
  explore: [
    { q: "What Is the Explore All Pages Page For?", a: "It lists every page on the ZapBuzzer website in one place, grouped by section, so you can scan features, solutions, workflows, use cases, guides, company pages and the blog without clicking through menus." },
    { q: "How Do I Find a Page by Name on Explore?", a: "Type into the “Search pages…” box above the list. The page names filter as you type, and sections with no matching pages are hidden." },
    { q: "How Are Pages Grouped on the Explore Page?", a: "Pages are grouped under the same sections used in the site navigation, plus Company and Blog. Each section heading shows its pages together so related topics sit side by side." },
    { q: "Can I Collapse Sections on the Explore Page?", a: "Yes. Click the page count beside a section heading to collapse or expand that section, or use the “Collapse all” button to fold every section at once and “Expand all” to open them again." },
    { q: "Is There a Quicker Way to Search the Whole Site?", a: "Yes. Use the search button in the header, or press Ctrl+K (⌘K on a Mac), to open site search from any page without coming to Explore." },
    { q: "Does the Explore Page Include Blog Articles?", a: "The Blog appears as its own section in the list. To search inside articles by topic or category, use the search and filters on the blog page itself." },
    { q: "How Many Pages Are Listed on Explore?", a: "The total is shown at the top of the page and in the stats bar, along with the number of sections. The count updates automatically whenever pages are added to the site." },
    { q: "I Can’t Find What I Need on Explore. What Next?", a: `Try a shorter or different word in the search box, or open site search with Ctrl+K. If you still cannot find it, email ${site.email} and we will point you to the right page.` },
  ],
};
